-- Matricula componente Kettle en tabla ETAPAS_CARGA_ODS 
INSERT INTO TOPAZETL.ETAPAS_CARGA_ODS (ID_ETAPA, DE_ETAPA, COMPONENTE_KETTLE)
VALUES (101, 'CARGA DATA ENTRYS DATA MART RIESGOS', '101-Carga_BDS_ETAPA_101');




-- Matricula componente Kettle en tabla FASES_CARGA_ODS
INSERT INTO TOPAZETL.FASES_CARGA_ODS (ID_ETAPA, ID_FASE, DE_FASE, COMPONENTE_KETTLE)
VALUES (101, 1, 'CARGA ODS DATA ENTRY RIESGOS', '101-1-ETAPA_101_FASE_1_Carga_ODS_DE_Riesgos');

INSERT INTO TOPAZETL.FASES_CARGA_ODS (ID_ETAPA, ID_FASE, DE_FASE, COMPONENTE_KETTLE)
VALUES (101, 2, 'CARGA BDS DATA ENTRY RIESGOS', '101-2-ETAPA_101_FASE_2_Carga_BDS_DE_Riesgos');


-- Matricula componente Kettle en tabla SUBFASES_CARGA_ODS


-- SubFases ODS DATA ENTRY RIESGOS

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 101, 1, 1, 'CARGA ODS DATA ENTRY CANAL COBRANZA', '101-1-1-ETAPA_101_FASE_1_SUBFASE_1_Carga_ODS_Canal_Cobranza'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 101, 1, 2, 'CARGA ODS DATA ENTRY CIERRE 32', '101-1-2-ETAPA_101_FASE_1_SUBFASE_2_Carga_ODS_Cierre_32'); 


-- SubFases BDS DATA ENTRY RIESGOS

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 101, 2, 1, 'CARGA BDS DATA ENTRY CANAL COBRANZA', '101-2-1-ETAPA_101_FASE_2_SUBFASE_1_Carga_BDS_Canal_Cobranza'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 101, 2, 2, 'CARGA BDS DATA ENTRY CIERRE 32', '101-2-2-ETAPA_101_FASE_2_SUBFASE_2_Carga_BDS_Cierre_32'); 


COMMIT;