-- Matricula componente Kettle en tabla FASES_CARGA_ODS

INSERT INTO TOPAZETL.FASES_CARGA_ODS (ID_ETAPA, ID_FASE, DE_FASE, COMPONENTE_KETTLE)
VALUES (100, 4, 'CARGA TABLAS BDS COBRANZAS', '100-4-ETAPA_100_FASE_4_Carga_BDS_Cobranzas');


-- Matricula componente Kettle en tabla SUBFASES_CARGA_ODS

-- SubFases BDS Cobranzas

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 4, 1, 'CARGA DIMENSIONES DIARIAS', '100-4-1-ETAPA_100_FASE_4_SUBFASE_1_Carga_D_Gen_Criterio'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 4, 2, 'CHEQUEO FIN DE MES', '100-4-2-ETAPA_100_FASE_4_SUBFASE_2_Chequeo_Fin_Mes'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 4, 3, 'CARGA DIMENSIONES MENSUALES', '100-4-3-ETAPA_100_FASE_4_SUBFASE_3_Carga_D_Gen_Cliente'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 4, 4, 'CARGA FACT COBRANZAS', '100-4-4-ETAPA_100_FASE_4_SUBFASE_4_Carga_F_Rie_Cobranza'); 

-- NUEVOS REGISTROS EN TOPAZETL.TABLAS_TRUNCO_RETOMA PARA BDS  

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 4, 1, 'D_GEN_CRITERIO', 'BDS', 0);


COMMIT;