--CARGAR ETAPAS
INSERT INTO TOPAZETL.ETAPAS_CARGA_ODS VALUES (200,'CARGA ODS BROAD CONTABLE','200-Carga_ODS_ETAPA_200',0);

--CARGAR FASES
INSERT INTO TOPAZETL.FASES_CARGA_ODS VALUES (200,0,'CONTROL FIN DE CADENA','200-0-ETAPA_200_FASE_0_Control_Fin_Cadena',0);
INSERT INTO TOPAZETL.FASES_CARGA_ODS VALUES (200,1,'CARGAS TABLAS DETALLE CONTABLE EN STAGE','200-1-ETAPA_200_FASE_1_Carga_Stage',0);
INSERT INTO TOPAZETL.FASES_CARGA_ODS VALUES (200,2,'CARGAS TABLAS TEMP DETALLE CONTABLE EN ODS','200-2-ETAPA_200_FASE_2_Carga_ODS',0);
INSERT INTO TOPAZETL.FASES_CARGA_ODS VALUES (200,3,'CARGAS HISTORICAS DETALLE CONTABLE EN ODS','200-3-ETAPA_200_FASE_3_Carga_Diaria',0);

--CARGAR SUB FASES
INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS VALUES (200,0,1,'CONTROL FIN DE CADENA','200-0-1-ETAPA_200_FASE_0_SUBFASE_1_Control_Fin_Cadena',0);
INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS VALUES (200,1,1,'CARGAS TABLAS DETALLE CONTABLE EN STAGE','200-1-1-ETAPA_200_FASE_1_SUBFASE_1_Carga_Stage',0);
INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS VALUES (200,2,1,'CARGAS TABLAS TEMP DETALLE CONTABLE EN ODS','200-2-1-ETAPA_200_FASE_2_SUBFASE_1_Carga_ODS',0);
INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS VALUES (200,3,1,'CARGAS HISTORICAS DETALLE CONTABLE EN ODS','200-3-1-ETAPA_200_FASE_3_SUBFASE_1_Carga_Diaria',0);

--CARGAR TABLAS TRUNCADAS
INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA VALUES (200,1,1,'T_GRL_DETALLE_CONTABILIDAD','STG',0);
INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA VALUES (200,2,1,'TD_DETALLE_CONTABILIDAD','ODS',0);

--CARGAR ESTADISTICAS
INSERT INTO TOPAZETL.TABLAS_GENERAR_ESTADISTICAS VALUES ('ODS','HD_DETALLE_CONTABILIDAD','S','P_HD_DETALLE_CONTAB_','DIARIA');
COMMIT;