-- Matricula componente Kettle en tabla ETAPAS_CARGA_ODS
INSERT INTO TOPAZETL.ETAPAS_CARGA_ODS (ID_ETAPA, DE_ETAPA, COMPONENTE_KETTLE)
VALUES (100, 'CARGA BDS DATA MART RIESGOS', '100-Carga_BDS_ETAPA_100');


-- Matricula componente Kettle en tabla FASES_CARGA_ODS
INSERT INTO TOPAZETL.FASES_CARGA_ODS (ID_ETAPA, ID_FASE, DE_FASE, COMPONENTE_KETTLE)
VALUES (100, 1, 'CONTROL FIN PROCESOS PREDECESORES', '100-1-ETAPA_100_FASE_1_Control_Fin_Procesos_Predecesores');

INSERT INTO TOPAZETL.FASES_CARGA_ODS (ID_ETAPA, ID_FASE, DE_FASE, COMPONENTE_KETTLE)
VALUES (100, 2, 'CARGA TABLAS BDS ADMISION', '100-2-ETAPA_100_FASE_2_Carga_BDS_Admision');

INSERT INTO TOPAZETL.FASES_CARGA_ODS (ID_ETAPA, ID_FASE, DE_FASE, COMPONENTE_KETTLE)
VALUES (100, 3, 'CARGA TABLAS BDS COSECHAS', '100-3-ETAPA_100_FASE_3_Carga_BDS_Cosechas');


-- Matricula componente Kettle en tabla SUBFASES_CARGA_ODS

-- SubFases Control de Dependencias
INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 1, 1, 'CONTROL FIN PROCESOS PREDECESORES', '100-1-1-ETAPA_100_FASE_1_SUBFASE_1_Control_Fin_Procesos_Predecesores');

-- SubFases BDS Admisión

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 2, 1, 'CARGA FACT RIESGOS ADMISION CREDITO', '100-2-1-ETAPA_100_FASE_2_SUBFASE_1_Carga_F_Rie_Admision_Creditos'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 2, 2, 'CARGA TABLA RIESGOS DESEMBOLSO'    , '100-2-2-ETAPA_100_FASE_2_SUBFASE_2_Carga_C_Desembolso_Rie'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 2, 3, 'CARGA TABLA RIESGOS SOLICITUDES DIARIA', '100-2-3-ETAPA_100_FASE_2_SUBFASE_3_Carga_C_Rie_Solicitudes_Dia'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 2, 4, 'CARGA DIMENSIONES ADMISION', '100-2-4-ETAPA_100_FASE_2_SUBFASE_4_Carga_Dimensiones'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 2, 5, 'CARGA LISTA RIESGOS PRESTAMOS EXTORNADOS', '100-2-5-ETAPA_100_FASE_2_SUBFASE_5_Carga_L_Rie_Prestamos_Extornados'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 2, 6, 'CARGA LISTA RIESGOS AUSENTE HM_EGP', '100-2-6-ETAPA_100_FASE_2_SUBFASE_6_Carga_L_Rie_Ausente_Hm_Egp'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 2, 7, 'CARGA TEMP FACT RIESGOS ADMISION CREDITOS', '100-2-7-ETAPA_100_FASE_2_SUBFASE_7_Carga_T_Rie_Admision_Creditos'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 2, 8, 'CHEQUEO FIN DE MES', '100-2-8-ETAPA_100_FASE_2_SUBFASE_8_Chequeo_Fin_Mes'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 2, 9, 'CARGA FACT RIESGOS PRESTAMOS REFINANCIADOS', '100-2-9-ETAPA_100_FASE_2_SUBFASE_9_Carga_F_Rie_Prestamos_Refinanciados'); 


-- SubFases BDS Cosechas

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 3, 1, 'CARGA FACT RIESGOS REFINANCIADOS EXTREMO', '100-3-1-ETAPA_100_FASE_3_SUBFASE_1_Carga_F_Rie_Ref_Extremo'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 3, 2, 'CARGA FACT RIESGOS COSECHA DIARIA', '100-3-2-ETAPA_100_FASE_3_SUBFASE_2_Carga_F_Rie_Cosecha_D'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 3, 3, 'CARGA FACT RIESGOS COSECHA MENSUAL', '100-3-3-ETAPA_100_FASE_3_SUBFASE_3_Carga_F_Rie_Cosecha_M'); 

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 100, 3, 4, 'VERIFICA FIN DE MES', '100-3-4-ETAPA_100_FASE_3_SUBFASE_4_Chequeo_Fin_Mes'); 


-- NUEVOS REGISTROS EN TOPAZETL.TABLAS_TRUNCO_RETOMA PARA BDS  

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 4, 'D_GEN_FUNCIONARIO', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 4, 'D_GEN_LINEA_CREDITO', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 4, 'D_GEN_CATEGORIA_PERSONA', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 4, 'D_GEN_SEGMENTO_NEGOCIO', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 4, 'D_GEN_TIPO_CAMBIO', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 4, 'D_GEN_TIPO_VIVIENDA', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 4, 'D_GEN_MOTIVO_CANCELA_PRESTAMO', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 4, 'D_GEN_TIPO_CREDITO', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 1, 'T_RIE_ADMISION_CREDITOS', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (100, 2, 7, 'T_RIE_ADMISION_CREDITOS', 'BDS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (10, 2, 1, 'MD_MOTIVO_CANCELA_PRESTAMO', 'ODS', 0);

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES (10, 2, 1, 'MD_TIPO_VIVIENDA', 'ODS', 0);

COMMIT;