-- ==============================
-- Matricula Estadisticas
-- ==============================

INSERT INTO TOPAZETL.TABLAS_GENERAR_ESTADISTICAS (ESQUEMA, NOMBRE_TABLA, TIENE_PARTICION, NOMBRE_PARTICION, TIPO_PARTICION)
VALUES ('ODS', 'MD_ESTADO_SOLICITUD', 'N','','');

INSERT INTO TOPAZETL.TABLAS_GENERAR_ESTADISTICAS (ESQUEMA, NOMBRE_TABLA, TIENE_PARTICION, NOMBRE_PARTICION, TIPO_PARTICION)
VALUES ('ODS', 'MD_TIPO_PERSONA', 'N','','');

INSERT INTO TOPAZETL.TABLAS_GENERAR_ESTADISTICAS (ESQUEMA, NOMBRE_TABLA, TIENE_PARTICION, NOMBRE_PARTICION, TIPO_PARTICION)
VALUES ('ODS', 'HD_SOLICITUDES', 'S','P_SOLICITUDES_','DIARIA');

INSERT INTO TOPAZETL.TABLAS_GENERAR_ESTADISTICAS (ESQUEMA, NOMBRE_TABLA, TIENE_PARTICION, NOMBRE_PARTICION, TIPO_PARTICION)
VALUES ('ODS', 'HD_PRESTAMOS_REFINANCIADOS', 'N','','');

INSERT INTO TOPAZETL.TABLAS_GENERAR_ESTADISTICAS (ESQUEMA, NOMBRE_TABLA, TIENE_PARTICION, NOMBRE_PARTICION, TIPO_PARTICION)
VALUES ('ODS', 'HD_CLIENTES', 'S','P_HD_CLIENTES_','DIARIA');

INSERT INTO TOPAZETL.TABLAS_GENERAR_ESTADISTICAS (ESQUEMA, NOMBRE_TABLA, TIENE_PARTICION, NOMBRE_PARTICION, TIPO_PARTICION)
VALUES ('ODS', 'TP_BITACORA_PRE_PRESTAMO', 'N','','');

INSERT INTO TOPAZETL.BASE_TIEMPO (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUB_FASE, MINUTOS) 
VALUES (1,2,7,'CARGA TABLA HD_SOLICITUDES',10);

INSERT INTO TOPAZETL.BASE_TIEMPO (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUB_FASE, MINUTOS) 
VALUES (1,2,8,'CARGA TABLA HD_CLIENTES',15);

INSERT INTO TOPAZETL.BASE_TIEMPO (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUB_FASE, MINUTOS) 
VALUES (12,4,4,'TABLA HD_PRESTAMOS_REFINANCIADOS',120);

COMMIT;

