CREATE OR REPLACE VIEW TOPAZETL.VW_BITACORA_INDICADOR AS
----------------------------------------------------------------------------------------------------------------------------------
-- RESUMEN
-- Proyecto : 00000
-- Nombre : VW_BITACORA_INDICADOR
-- Autor :  TOPAZETL
-- Fecha de Creación :
-- Descripción : Vista de indicador de bitacora
----------------------------------------------------------------------------------------------------------------------------------
-- Modificaciones
-- Requerimiento       Responsable        Fecha       Descripción
-- CASO-21515          Marco Castilla     05/08/2020  Se agrega query para leer de la nueva tabla TOPAZETL.PARAMETROS_CARGA_BDS
----------------------------------------------------------------------------------------------------------------------------------
SELECT S.FECHA_PROCESO, S.ID_ETAPA, S.ID_FASE, S.ID_SUBFASE, X.DE_SUBFASE, s.HORA_INICIO_PROCESO, s.hora_fin_proceso,
       CASE WHEN S.ESTADO_CARGA = 'T' THEN 'FINALIZADO'
            WHEN S.ESTADO_CARGA = 'C' THEN 'EN EJECUCIÓN'
            WHEN S.ESTADO_CARGA = 'I' THEN 'IGNORADO'
            WHEN S.ESTADO_CARGA = 'A' THEN 'ABORTADO'
            WHEN S.ESTADO_CARGA = 'E' THEN 'ERROR'
            WHEN S.ESTADO_CARGA = 'R' THEN 'EN REINICIO'  END ESTADO,
CASE WHEN S.ESTADO_CARGA !='T' THEN ROUND((SYSDATE - S.HORA_INICIO_PROCESO) * 24 * 60)
          ELSE ROUND((S.HORA_FIN_PROCESO - S.HORA_INICIO_PROCESO) * 24 * 60) END MINUTOS_EJECUTADO,
          T.MINUTOS MINUTOS_OPTIMO,
     CASE WHEN S.ESTADO_CARGA = 'T' AND (ROUND((S.HORA_FIN_PROCESO - S.HORA_INICIO_PROCESO) * 24 * 60))> T.MINUTOS THEN 1
          WHEN S.ESTADO_CARGA != 'T' AND (ROUND((SYSDATE - S.HORA_INICIO_PROCESO) * 24 * 60))> T.MINUTOS THEN 1 ELSE 0 END INDICADOR,
CASE WHEN S.ESTADO_CARGA != 'T' AND (ROUND((SYSDATE - S.HORA_INICIO_PROCESO) * 24 * 60))> T.MINUTOS THEN 1 ELSE 0 END SEMAFORO
FROM TOPAZETL.BITACORA_SUBFASES_ODS s
INNER JOIN TOPAZETL.BASE_TIEMPO T ON  T.ID_ETAPA = S.ID_ETAPA AND T.ID_FASE = S.ID_FASE AND T.ID_SUBFASE = S.ID_SUBFASE
INNER JOIN TOPAZETL.SUBFASES_CARGA_ODS X ON X.ID_ETAPA = S.ID_ETAPA AND X.ID_FASE = S.ID_FASE AND X.ID_SUBFASE = S.ID_SUBFASE
WHERE  S.FECHA_PROCESO = (SELECT MAX(FECHAPROCESO) FROM TOPAZETL.PARAMETROS_CARGA_ODS WHERE ESTADO_CARGA IN ('C','R','E'))
--@CASO-21515 INI : 08/05/2020 Se agrega query para leer de la nueva tabla TOPAZETL.PARAMETROS_CARGA_BDS
union
SELECT S.FECHA_PROCESO, S.ID_ETAPA, S.ID_FASE, S.ID_SUBFASE, X.DE_SUBFASE, s.HORA_INICIO_PROCESO, s.hora_fin_proceso,
       CASE WHEN S.ESTADO_CARGA = 'T' THEN 'FINALIZADO'
            WHEN S.ESTADO_CARGA = 'C' THEN 'EN EJECUCIÓN'
            WHEN S.ESTADO_CARGA = 'I' THEN 'IGNORADO'
            WHEN S.ESTADO_CARGA = 'A' THEN 'ABORTADO'
            WHEN S.ESTADO_CARGA = 'E' THEN 'ERROR'
            WHEN S.ESTADO_CARGA = 'R' THEN 'EN REINICIO'  END ESTADO,
CASE WHEN S.ESTADO_CARGA !='T' THEN ROUND((SYSDATE - S.HORA_INICIO_PROCESO) * 24 * 60)
          ELSE ROUND((S.HORA_FIN_PROCESO - S.HORA_INICIO_PROCESO) * 24 * 60) END MINUTOS_EJECUTADO,
          T.MINUTOS MINUTOS_OPTIMO,
     CASE WHEN S.ESTADO_CARGA = 'T' AND (ROUND((S.HORA_FIN_PROCESO - S.HORA_INICIO_PROCESO) * 24 * 60))> T.MINUTOS THEN 1
          WHEN S.ESTADO_CARGA != 'T' AND (ROUND((SYSDATE - S.HORA_INICIO_PROCESO) * 24 * 60))> T.MINUTOS THEN 1 ELSE 0 END INDICADOR,
CASE WHEN S.ESTADO_CARGA != 'T' AND (ROUND((SYSDATE - S.HORA_INICIO_PROCESO) * 24 * 60))> T.MINUTOS THEN 1 ELSE 0 END SEMAFORO
FROM TOPAZETL.BITACORA_SUBFASES_ODS s
INNER JOIN TOPAZETL.BASE_TIEMPO T ON  T.ID_ETAPA = S.ID_ETAPA AND T.ID_FASE = S.ID_FASE AND T.ID_SUBFASE = S.ID_SUBFASE
INNER JOIN TOPAZETL.SUBFASES_CARGA_ODS X ON X.ID_ETAPA = S.ID_ETAPA AND X.ID_FASE = S.ID_FASE AND X.ID_SUBFASE = S.ID_SUBFASE
WHERE  S.FECHA_PROCESO = (SELECT MAX(FECHAPROCESO) FROM TOPAZETL.PARAMETROS_CARGA_BDS WHERE ESTADO_CARGA IN ('C','R','E'))
--@CASO-21515 FIN : 08/05/2020 Se agrega query para leer de la nueva tabla TOPAZETL.PARAMETROS_CARGA_BDS
;