-- ==============================
-- Matricula tablas truncadas STG
-- ==============================

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES ( 1, 1, 3, 'T_AU_ESTADOSAUTONOMIAS', 'STG', 0);

-- ==============================
-- Matricula tablas truncadas ODS
-- ==============================

INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES ( 1, 2, 1, 'MD_ESTADO_SOLICITUD', 'ODS', 0);


INSERT INTO TOPAZETL.TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO, ESQUEMA_TABLA, TZ_LOCK)
VALUES ( 10, 2, 1, 'MD_TIPO_PERSONA', 'ODS', 0);

-- ==============================
-- Matricula Subfases
-- ==============================

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 1, 2, 7, 'CARGA TABLA HD_SOLICITUDES', '1-2-7-ETAPA_1_FASE_2_SUBFASE_7_Carga_ODS');

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 1, 2, 8, 'CARGA TABLA HD_CLIENTES ', '1-2-8-ETAPA_1_FASE_2_SUBFASE_8_Carga_ODS');

INSERT INTO TOPAZETL.SUBFASES_CARGA_ODS (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_SUBFASE, COMPONENTE_KETTLE)
VALUES ( 12, 4, 4, 'CARGA TABLA HD_PRESTAMOS_REFINANCIADOS', '12-4-4-ETAPA_12_FASE_4_SUBFASE_4_Carga_Diaria');

COMMIT;