-- Create/Recreate indexes 
CREATE INDEX STG.T_TMP_MONTOS_SALDOS_N1 ON STG.T_TMP_MONTOS_SALDOS (CUENTA) TABLESPACE STG_IDX_01;
CREATE INDEX STG.T_TMP_MONTOS_SALDOS_HIST_N1 ON STG.T_TMP_MONTOS_SALDOS_HIST (CUENTA_HIST) TABLESPACE STG_IDX_01;
CREATE INDEX ODS.T_MD_SOLICITUDES_N1 ON ODS.MD_SOLICITUDES (FE_REGI_SOLI) TABLESPACE ODS_IDX_01;