-- =========================
-- STG.T_SL_SOLICITUDCREDITO
-- =========================
ALTER TABLE STG.T_SL_SOLICITUDCREDITO
  ADD (
        C5231                     DATE
      , TIPO_CREDITO              VARCHAR2(2)
      , DEUDA_SOLICITUD           NUMBER(15,2)
      , ACTECONINTERNA            VARCHAR2(8)
      , ADICIONALREFINANCIADO     NUMBER(15,2)
      , ALE_ANA_CAL               NUMBER(2)
      , ALE_ANA_FEC               DATE
      , ALE_ANA_SUS               VARCHAR2(200)
      , ALE_SUP_CAL               NUMBER(2)
      , ALE_SUP_FEC               DATE
      , C2841                     NUMBER(11,7)
      , C4794                     VARCHAR2(1)
      , C5003                     VARCHAR2(8)
      , C5009                     VARCHAR2(5)
      , C5022                     VARCHAR2(600)
      , C5025                     DATE
      , C5026                     NUMBER(2)
      , C5028                     NUMBER(3)
      , C5029                     NUMBER(2)
      , C5030                     VARCHAR2(4)
      , C5031                     NUMBER(15,2)
      , C5033                     VARCHAR2(60)
      , C5034                     NUMBER(3)
      , C5037                     NUMBER(15,2)
      , C5038                     NUMBER(4)
      , C5040                     VARCHAR2(1)
      , C5041                     NUMBER(11,7)
      , C5042                     NUMBER(15,2)
      , C5043                     VARCHAR2(50)
      , C5045                     NUMBER(6)
      , C5047                     VARCHAR2(8)
      , C5049                     NUMBER(2)
      , C5050                     VARCHAR2(1)
      , C5059                     VARCHAR2(8)
      , C5064                     VARCHAR2(8)
      , C5070                     VARCHAR2(8)
      , C5183                     DATE
      , C5186                     NUMBER(8)
      , C5190                     DATE
      , C5221                     NUMBER(6)
      , C5222                     VARCHAR2(8)
      , C5225                     NUMBER(11,7)
      , C5226                     DATE
      , C5227                     VARCHAR2(8)
      , C5230                     VARCHAR2(2)
      , C5233                     VARCHAR2(1)
      , C5270                     VARCHAR2(1)
      , C5271                     VARCHAR2(20)
      , C5272                     VARCHAR2(60)
      , C5273                     NUMBER(4)
      , C5274                     VARCHAR2(60)
      , C5275                     VARCHAR2(60)
      , C5280                     NUMBER(2)
      , C5283                     VARCHAR2(4)
      , C6945                     NUMBER(15,2)
      , CAR_USU_DESEM             NUMBER(5)
      , CAR_USU_DIS               NUMBER(5)
      , CODACTCIIU                NUMBER(4)
      , CODACTCONTR               VARCHAR2(7)
      , CODBANCODESEMBOLSO        NUMBER(5)
      , CONTCARTADESMX            VARCHAR2(1)
      , CON_CAR_DES_BAN           VARCHAR2(1)
      , CTA_CTBLE_DES_BAN         NUMBER(15)
      , CUENTADESEMBOLSO          FLOAT
      , CUO_MAX_DIS               NUMBER(15,2)
      , CUO_MAX_LIN               NUMBER(15,2)
      , DEBITO_AUTOMATICO         VARCHAR2(1)
      , DEUDA_ACTUAL              NUMBER(15,2)
      , DEVOLUCION_SD             NUMBER(15,2)
      , DIADEPAGO                 NUMBER(2)
      , FECHINIACTICLI            DATE
      , FEC_DER_HUB               DATE
      , FLG_ADM_HUB               NUMBER(1)
      , FORMAPROVISION            VARCHAR2(1)
      , HOR_DER_HUB               VARCHAR2(10)
      , IDGRUPOCOBRO              NUMBER(12)
      , IMPCARTADESMB             VARCHAR2(1)
      , INI_USU_DESEM             VARCHAR2(8)
      , INT_CAPITALIZA            NUMBER(15,2)
      , LINEAFINANC               FLOAT
      , LUGARDESEMB               NUMBER(3)
      , MAR_HUB                   NUMBER(5)
      , MB_COBRANZA_JTS_OID       NUMBER(15)
      , MB_PRECANCELACION_MIGRADO VARCHAR2(1)
      , MB_VIVIENDA               VARCHAR2(1)
      , MICROSEGURO               VARCHAR2(1)
      , MIGRADO                   VARCHAR2(1)
      , MODALIDADDESEMBOLSO       VARCHAR2(600)
      , MODDISP                   NUMBER(1)
      , MONTOCONDONACION          NUMBER(15,2)
      , MONTO_A_DESCONTAR         NUMBER(15,2)
      , MONTO_FLAT                NUMBER(15,2)
      , MONTO_ITF                 NUMBER(15,2)
      , NODOCCONOCDEUDA           VARCHAR2(1)
      , NOFIRMACONYGAR            VARCHAR2(1)
      , NOFIRMACONYTIT            VARCHAR2(1)
      , NROACTA                   NUMBER(8)
      , NROLIN                    FLOAT
      , NROOPERACION              NUMBER(8)
      , OPCIONESREFINANCIACION    NUMBER(2)
      , PAGOMINIMO                NUMBER(15,2)
      , PARENTESCO                VARCHAR2(1)
      , PLAZODISP                 NUMBER(5)
      , POLIZA                    NUMBER(10)
      , PORCENTAJEITF             NUMBER(11,10)
      , PORCENTAJE_FLAT           NUMBER(6,2)
      , REVOLVENTE                VARCHAR2(1)
      , RIESGO_TOTAL              NUMBER(15,2)
      , RIESGO_VINCULADO          NUMBER(15,2)
      , SALDO_MIBANCO             NUMBER(15,2)
      , SEGMENTO_COMERCIAL        NUMBER(5)
      , SIN_DESGRAVAMEN           NUMBER(2)
      , SOLICCABECERA             NUMBER(8)
      , SUCBANCODESEMBOLSO        VARCHAR2(50)
      , SUSTENTADO                VARCHAR2(2)
      , TCAMBIO                   NUMBER(11,7)
      , TIPOCALIFICAC             VARCHAR2(1)
      , TIPOREVOLVENTE            VARCHAR2(1)
      , USUDESEMB                 NUMBER(5)
      , USU_MOD_CON               VARCHAR2(8)
      );

COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5231 IS   'FECHA APROBACCION '  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.TIPO_CREDITO  IS   'TIPO DE CREDITO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.DEUDA_SOLICITUD IS   'DEUDA DE LA SOLICTUD'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.ACTECONINTERNA  IS   'ACTIVIDAD ECONOMICA INTERNA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.ADICIONALREFINANCIADO IS  'ADICIONAL REFINANCIADO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.ALE_ANA_CAL IS   'CALIFICACION DE RIESGO DEL ANALISTA A ALERTAS DE VINCULACION: 1-BAJO, 2-MEDIO, 3-ALTO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.ALE_ANA_FEC IS   'FECHA EN QUE ANALISTA CALIFICO ALERTAS DE VINCULACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.ALE_ANA_SUS IS   'SUSTENTO DEL ANALISTA POR LA CALIFICACION DE ALERTAS'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.ALE_SUP_CAL IS   'CALIFICACION DE RIESGO DEL SUPERVISOR A ALERTAS DE VINCULACION: 1-BAJO, 2-MEDIO, 3-ALTO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.ALE_SUP_FEC IS   'FECHA EN QUE SUPERVISOR CLASIFICO ALERTAS DE VINCULACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C2841 IS   'TASA INT.COMP.MORA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C4794 IS   'MODALIDAD DE COBRO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5003 IS   'COD. OFICIAL'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5009 IS   'DESTINO DEL CREDITO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5022 IS   'OBSERVACIONES'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5025 IS   'FECHA DE PAGO SOLICITADA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5026 IS   'SECTOR ECONOMICO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5028 IS   'CANTIDAD DE CUOTAS OFICIAL'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5029 IS   'NRO.ASEGURADOS'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5030 IS   'DESTINO SIB'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5031 IS   'MONTO DESTINADO A ACTIVO FIJO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5033 IS   'NOMBRE DEL TITULAR'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5034 IS   'PERIODO APROBADO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5037 IS   'CUOTA APROBADA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5038 IS   'NRO. CUOTAS APROBADAS'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5040 IS   'NUMERO O MONTO DE CUOTA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5041 IS   'TASA DE MORA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5042 IS   'VALUO HIPOTECARIO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5043 IS   'CG NOMBRE BENEFICIARIO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5045 IS   ' NUM.PAGO POR CAJA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5047 IS   'USUARIO RECOMENDACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5049 IS   'PARAM.LIM.PAGO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5050 IS   'MULTIDESEMBOLSO ?'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5059 IS   'USUARIO INGRESO SOLICITUD'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5064 IS   'USUARIO RETORNA DE APROBACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5070 IS   'USUARIO EVALUACION PRESOLICITUD'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5183 IS   'FECHA PAGO PRIMERA CUOTA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5186 IS   'CANTIDAD DE CUOTAS'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5190 IS   'FECHA RECEPCION PRESOLICITUD'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5221 IS   'COD. DESTINO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5222 IS   'USUARIO INGRESO PRESOLICITUD'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5225 IS   'FACTOR SEGURO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5226 IS   'FECHA ULTIMA MODIFICACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5227 IS   'USUARIO ULTIMA MODIFICACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5230 IS   'FRECUENCIA DE PAGO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5233 IS   'INDIVIDUAL O GRUPAL'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5270 IS   'TIPO DOC. FIRMA A RUEGO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5271 IS   'NRO. DOC. FIRMA A RUEGO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5272 IS   'NOMBRE DE FIRMA A RUEGO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5273 IS   'PROFESION U OFICIO FIRMA A RUEGO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5274 IS   'NOMBRE DE POR QUIEN  FIRMA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5275 IS   'DOMICILIO FIRMA A RUEGO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5280 IS   'DESEMBOLSOS REALIZADOS'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C5283 IS   'TIPO DE GARANTIA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.C6945 IS   'GASTO PRELI. HIPOTECARIOS'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CAR_USU_DESEM IS   'CARGO DEL USUARIO DEL DESEMBOLSO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CAR_USU_DIS IS   'CARGO DEL USUARIO DE LA DISPOSICION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CODACTCIIU  IS   'COD. ACTIVIDAD CIIU'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CODACTCONTR IS   'COD. ACTIVIDAD ORGANISMO CONTRALOR'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CODBANCODESEMBOLSO  IS   'CODIGO DE BANCO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CONTCARTADESMX  IS   'CONTABILIZACION CARTAS DESEMBOLSO MIXTO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CON_CAR_DES_BAN IS   'CONTABILIZACION DE CARTAS DESEMBOLSOS VIA BANCO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CTA_CTBLE_DES_BAN IS   'CUENTA CONTABLE DESEMBOLSOS VIA BANCO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CUENTADESEMBOLSO  IS   'NRO. DE CUENTA (DESEMBOLSO)'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CUO_MAX_DIS IS   'CUOTA MAXIMA DE DISPOSICION DE EFECTIVO.'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.CUO_MAX_LIN IS   'CUOTA MAXIMA DE LINEA DE CREDITO.'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.DEBITO_AUTOMATICO IS   'DEBITO AUTOMATICO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.DEUDA_ACTUAL  IS   'DEUDA ACTUAL DEL CLIENTE'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.DEVOLUCION_SD IS   'DEVOLUCION SEGURO DE DESGRAVAMEN'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.DIADEPAGO IS   'DIA DE PAGO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.FECHINIACTICLI  IS   'FEC. DE INICIO DE ACTIVIDAD DEL CLI'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.FEC_DER_HUB IS   'FECHA DE DERIVACION A HUB'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.FLG_ADM_HUB IS   'FLAG ADMINISTRADOR HUB'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.FORMAPROVISION  IS   'FORMA DE PROVISION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.HOR_DER_HUB IS   'HORA DE DERIVACION A HUB'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.IDGRUPOCOBRO  IS   'IDGRUPOCOBRO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.IMPCARTADESMB IS   'IMP DE CARTA DESMB   '  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.INI_USU_DESEM IS   'INICIALES DEL USUARIO DEL DESEMBOLSO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.INT_CAPITALIZA  IS   'INTERES CAPITALIZA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.LINEAFINANC IS   'COD. LINEA FINANCIAMIENTO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.LUGARDESEMB IS   'LUGAR DE DESEMBOLSO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MAR_HUB IS   'MARCA HUB'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MB_COBRANZA_JTS_OID IS   'MB COBRANZA JTS OID'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MB_PRECANCELACION_MIGRADO IS   'MB PRECANCELACION MIGRADO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MB_VIVIENDA IS   'MB VIVIENDA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MICROSEGURO IS   'MICROSEGUROS S/N'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MIGRADO IS   'MIGRADO  '  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MODALIDADDESEMBOLSO IS   'MODALIDAD DESEMB'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MODDISP IS   'MODALIDAD DE DISPOSICION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MONTOCONDONACION  IS   'MONTO CONDONACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MONTO_A_DESCONTAR IS   'MONTO A DESCONTAR'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MONTO_FLAT  IS   'MONTO COMISION FLAT'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.MONTO_ITF IS   'MONTO ITF  '  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.NODOCCONOCDEUDA IS   'NO ENTREGA DOC. CONOCIMIENTO DEUDA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.NOFIRMACONYGAR  IS   'POSIBLES VALORES: N: NO APLICA, S: SOLICITUD DE NO FIRMA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.NOFIRMACONYTIT  IS   'POSIBLES VALORES: N: NO APLICA, S: SOLICITUD DE NO FIRMA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.NROACTA IS   'NRO ACTA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.NROLIN  IS   'NUMERO DE LINEA DE CREDITO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.NROOPERACION  IS   'NUMERO DE OPERACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.OPCIONESREFINANCIACION  IS   'OPCIONES REFINANCIACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.PAGOMINIMO  IS   'MONTO PAGO MINIMO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.PARENTESCO  IS   'PARENTESCO EN CASO EL DOCUMENTO SEA DE TIPO FAMILIAR'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.PLAZODISP IS   'PLAZO MAXIMO DE DISPOSICION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.POLIZA  IS   'POLIZA SEGURO DESGRAVAMEN'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.PORCENTAJEITF IS   'PORCENTAJE ITF'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.PORCENTAJE_FLAT IS   'PORCENTAJE MONTO COMISION FLAT'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.REVOLVENTE  IS   'REVOLVENTE/NO REVOLVENTE'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.RIESGO_TOTAL  IS   'RIESGO TOTAL'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.RIESGO_VINCULADO  IS   'RIESGO VINCULADO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.SALDO_MIBANCO IS   'SALDO MI BANCO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.SEGMENTO_COMERCIAL  IS   'SEGMENTO COMERCIAL'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.SIN_DESGRAVAMEN IS   'FLAG SIN DESGRAVAMEN'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.SOLICCABECERA IS   'SOLICITUD CABECERA'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.SUCBANCODESEMBOLSO  IS   'SUC BANCO DESMB'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.SUSTENTADO  IS   'CODIGO DEL DOCUMENTO SUSTENTADO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.TCAMBIO IS   'TIPO DE CAMBIO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.TIPOCALIFICAC IS   'TIPO DE CALIFICACION'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.TIPOREVOLVENTE  IS   'TIPO REVOLVENTE'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.USUDESEMB IS   'USUARIO DESEMBOLSO'  ;
COMMENT ON COLUMN STG.T_SL_SOLICITUDCREDITO.USU_MOD_CON IS   'USUARIO MODIFICACION DE CONGLOMERADO.'  ;


-- =========================
-- STG.T_DESEMBOLSO
-- =========================
ALTER TABLE STG.T_DESEMBOLSO RENAME COLUMN FE_VALOR TO FE_APER_CUEN;

COMMENT ON COLUMN  STG.T_DESEMBOLSO.FE_APER_CUEN IS 'FECHA APERTURA DE LA CUENTA';


ALTER TABLE STG.T_DESEMBOLSO
  ADD (
    NU_LINE_CRED  NUMBER(15)
  , MO_CUOTA      NUMBER(15,2)
  , NU_CUOTAS     NUMBER(15)
  , FE_DESEMBOLSO DATE
  , CO_REFINANCIACION VARCHAR2(1)
  , CO_USUA_TOPA_DESE VARCHAR2(10) 
  );

COMMENT ON COLUMN  STG.T_DESEMBOLSO.NU_LINE_CRED IS 'NUMERO DE LINEA DE CREDITO';
COMMENT ON COLUMN  STG.T_DESEMBOLSO.MO_CUOTA IS 'MONTO CUOTA';
COMMENT ON COLUMN  STG.T_DESEMBOLSO.NU_CUOTAS IS 'NUMERO DE CUOTAS';
COMMENT ON COLUMN  STG.T_DESEMBOLSO.FE_DESEMBOLSO IS 'FECHA DE DESEMBOLSO';
COMMENT ON COLUMN  STG.T_DESEMBOLSO.CO_REFINANCIACION IS 'REFINANCIACION';
COMMENT ON COLUMN  STG.T_DESEMBOLSO.CO_USUA_TOPA_DESE IS 'CODIGO USUARIO TOPAZ QUE REALIZO EL DESEMBOLSO';


-- =========================
-- ODS.HD_DESEMBOLSO
-- =========================

ALTER TABLE ODS.HD_DESEMBOLSO RENAME COLUMN FE_VALOR TO FE_APER_CUEN;

COMMENT ON COLUMN  ODS.HD_DESEMBOLSO.FE_APER_CUEN IS 'FECHA APERTURA DE LA CUENTA';

ALTER TABLE ODS.HD_DESEMBOLSO
ADD (
	NU_LINE_CRED      NUMBER(15),
	MO_CUOTA          NUMBER(15,2),
	NU_CUOTAS         NUMBER(15),
	FE_DESEMBOLSO     DATE,
	CO_REFINANCIACION VARCHAR2(1),
	CO_GRUP_EXCE      NUMBER(15),
	CO_USUA_TOPA_DESE VARCHAR2(10) 
  );
  
COMMENT ON COLUMN  ODS.HD_DESEMBOLSO.NU_LINE_CRED IS 'NUMERO DE LINEA DE CREDITO';
COMMENT ON COLUMN  ODS.HD_DESEMBOLSO.MO_CUOTA IS 'MONTO CUOTA';
COMMENT ON COLUMN  ODS.HD_DESEMBOLSO.NU_CUOTAS IS 'NUMERO DE CUOTAS';
COMMENT ON COLUMN  ODS.HD_DESEMBOLSO.FE_DESEMBOLSO IS 'FECHA DE DESEMBOLSO';
COMMENT ON COLUMN  ODS.HD_DESEMBOLSO.CO_REFINANCIACION IS 'REFINANCIACION';
COMMENT ON COLUMN  ODS.HD_DESEMBOLSO.CO_GRUP_EXCE IS 'CODIGO DE GRUPO DE EXCEPCIONES';
COMMENT ON COLUMN  ODS.HD_DESEMBOLSO.CO_USUA_TOPA_DESE IS 'CODIGO USUARIO TOPAZ QUE REALIZO EL DESEMBOLSO';


-- =========================
-- ODS.MD_SOLICITUDES
-- =========================
ALTER TABLE ODS.MD_SOLICITUDES
  ADD (CO_MONEDA     	    	NUMBER(4),
		FE_EVAL_SOLI 	   		DATE,
		CO_TIPO_GRAC 			VARCHAR2(1),
		CO_FORM_DESE 			VARCHAR2(2),
		NU_PLAZ_APROB			NUMBER(5),
		FE_APRO_SOLI			DATE ,
		CO_TIPO_CRED		    varchar2(2),
		MO_DEUD_SOLI  		 	number(15,2),
		IN_EVALUACION           NUMBER(1),
		IN_APROBACION           NUMBER(1),
		IN_DESEMBOLSO           NUMBER(1),
		CO_USUA_TOPA_REGI       VARCHAR2(8),
		CO_USUA_TOPA_EVAL       VARCHAR2(8),
		CO_USUA_TOPA_APRO       VARCHAR2(8),
		MO_PRESTAMO             NUMBER(15,2),
		MO_CUOTA                NUMBER(15,2),
		NU_PLAZOS               NUMBER(6),
		NU_CUOTAS               NUMBER(8)
      );

COMMENT ON COLUMN  ODS.MD_SOLICITUDES.CO_MONEDA IS 'CODIGO DE MONEDA';
COMMENT ON COLUMN  ODS.MD_SOLICITUDES.FE_EVAL_SOLI IS 'FECHA DE EVALUACION DE SOLICITUD';
COMMENT ON COLUMN  ODS.MD_SOLICITUDES.CO_TIPO_GRAC IS 'CODIGO DEL TIPO DE GRACIA';
COMMENT ON COLUMN  ODS.MD_SOLICITUDES.CO_FORM_DESE IS 'CODIGO DE LA FORMA DE DESEMBOLSO';
COMMENT ON COLUMN  ODS.MD_SOLICITUDES.NU_PLAZ_APROB IS 'NUMERO DE PLAZO APROBADO';
COMMENT ON COLUMN  ODS.MD_SOLICITUDES.FE_APRO_SOLI IS 'FECHA DE APROBACION DE LA SOLICITUD';
COMMENT ON COLUMN  ODS.MD_SOLICITUDES.CO_TIPO_CRED IS 'CODIGO DEL TIPO DE CREDITO';
COMMENT ON COLUMN  ODS.MD_SOLICITUDES.MO_DEUD_SOLI IS 'MONTO DEUDA DE LA SOLICITUD';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.IN_EVALUACION IS 'INDICADOR DE SOLICITUD EVALUADA -> 1 = EVALUADA.';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.IN_APROBACION IS 'INDICADOR DE SOLICITUD APRODADA -> 1 = APROBADA.';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.IN_DESEMBOLSO IS 'INDICADOR DE SOLICITUD DESEMBOLSADA -> 1 = DESEMBOLSADA.';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.CO_USUA_TOPA_REGI IS 'CODIGO DEL USUARIO QUE REGISTRA LA SOLICITUD.';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.CO_USUA_TOPA_EVAL IS 'CODIGO DEL USUARIO QUE EVALUA LA SOLICITUD.';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.CO_USUA_TOPA_APRO IS 'CODIGO DEL USUARIO QUE APRUEBA LA SOLICITUD.';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.MO_PRESTAMO IS 'MONTO DEL PRESTAMO.';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.MO_CUOTA IS 'MONTO DE LA CUOTA.';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.NU_PLAZOS IS 'NUMERO DE PLAZO SOLICITADO.';
COMMENT ON COLUMN ODS.MD_SOLICITUDES.NU_CUOTAS IS 'NUMERO DE CUOTAS DE LA SOLICITUD.';


-- =========================
-- STG.T_SL_PERDIDASYGANANCIAS
-- =========================
ALTER TABLE STG.T_SL_PERDIDASYGANANCIAS   
  ADD (
SALARIO                    NUMBER(15,2),
MONEDA	                   NUMBER(3),
CUOTAOBLIGACIONFINANCIERA  NUMBER(15,2),
MARGENUTILIDADBRUTA        NUMBER(15,2),
GASTOSNEGOCIO              NUMBER(15,2),
DEPRECIACION               NUMBER(15,2),
GASTOSGENERALES            NUMBER(15,2),
MARGENUTILIDADOPERATIVA    NUMBER(15,2),
INGRESOSFINANCIEROS        NUMBER(15,2),
OTROSINGRESOS              NUMBER(15,2),
INGRESOSEXTRAORDINARIOS    NUMBER(15,2),
OTROSEGRESOS               NUMBER(15,2),
EGRESOSEXTRAORDINARIOS     NUMBER(15,2),
IMPUESTORENTA              NUMBER(15,2),
DISTRIBUCIONLEGALRENTA     NUMBER(15,2),
APORTECONYUGE              NUMBER(15,2),
ALQUILERCASA               NUMBER(15,2),
ALIMENTACION               NUMBER(15,2),
EDUCACION                  NUMBER(15,2),
TRANSPORTE                 NUMBER(15,2),
SERVICIOSPUBLICOS          NUMBER(15,2),
TELEFONO                   NUMBER(15,2),
SALUD                      NUMBER(15,2),
CUOTATARJETACREDITO        NUMBER(15,2),
FECHA                      DATE,
MIGRADO                    VARCHAR2(1)
  );

COMMENT ON COLUMN  STG.T_SL_PERDIDASYGANANCIAS.SALARIO                   IS 'SALARIO DEL CLIENTE';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.MONEDA                     IS 'MONEDA DE INFORMACION DEDUCIBLE';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.CUOTAOBLIGACIONFINANCIERA  IS 'CUOTA DE UNA OBLIGACION FINANCIERA';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.MARGENUTILIDADBRUTA        IS 'MARGEN DE UTILIDAD BRUTA';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.GASTOSNEGOCIO              IS 'GASTOS DE NEGOCIO';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.DEPRECIACION               IS 'DEPRECIACION';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.GASTOSGENERALES            IS 'GASTOS GENERALES';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.MARGENUTILIDADOPERATIVA    IS 'MARGEN DE UTILIDAD OPERATIVA';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.INGRESOSFINANCIEROS        IS 'INGRESOS FINANCIEROS';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.OTROSINGRESOS              IS 'OTROS INGRESOS';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.INGRESOSEXTRAORDINARIOS    IS 'INGRESOS EXTRAORIDNARIOS';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.OTROSEGRESOS               IS 'OTROS EGRESOS';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.EGRESOSEXTRAORDINARIOS     IS 'EGRESOS EXTRAORDINARIOS';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.IMPUESTORENTA              IS 'IMPUESTO DE RENTA';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.DISTRIBUCIONLEGALRENTA     IS 'DISTRIBUCION LEGAL DE RENTA';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.APORTECONYUGE              IS 'INGRESO DE APORTE DE CONYUGE';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.ALQUILERCASA               IS 'GASTOS POR ALQUILER DE CASA';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.ALIMENTACION               IS 'GASTOS POR ALIMENTACION';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.EDUCACION                  IS 'GASTOS POR EDUCACION';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.TRANSPORTE                 IS 'GASTOS POR TRANSPORTE';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.SERVICIOSPUBLICOS          IS 'GASTOS POR SERVICIOS PUBLICOS';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.TELEFONO                   IS 'GASTOS POR TELEFONO';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.SALUD                      IS 'GASTOS POR SALUD';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.CUOTATARJETACREDITO        IS 'GASTOS POR TARJETA DE CREDITO';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.FECHA                      IS 'FECHA DE REGISTRO';
COMMENT ON COLUMN STG.T_SL_PERDIDASYGANANCIAS.MIGRADO                    IS 'FLAG DE MIGRADO';

-- =========================
-- ODS.MD_PERDIDAS_GANANCIAS
-- =========================
ALTER TABLE ODS.MD_PERDIDAS_GANANCIAS 
  ADD (
  MO_SALARIO      NUMBER(15,2),
  TI_DOCUMENTO    VARCHAR2(2),
  NU_DOCUMENTO    VARCHAR2(20)
  );

COMMENT ON COLUMN  ODS.MD_PERDIDAS_GANANCIAS.MO_SALARIO   IS 'SALARIO DEL CLIENTE';
COMMENT ON COLUMN  ODS.MD_PERDIDAS_GANANCIAS.TI_DOCUMENTO IS 'TIPO DE DOCUMENTO DEL CLIENTE';
COMMENT ON COLUMN  ODS.MD_PERDIDAS_GANANCIAS.NU_DOCUMENTO IS 'NUMERO DE DOCUMENTO DEL CLIENTE';


