CREATE INDEX BDS.F_RIE_COBRANZA_N1 ON BDS.F_RIE_COBRANZA (NU_PERI_MES, NU_PRESTAMO) TABLESPACE BDS_IDX_01;
CREATE UNIQUE INDEX BDS.UK_D_GEN_CRITERIO_N1 ON BDS.D_GEN_CRITERIO (CO_CRITERIO) TABLESPACE BDS_IDX_01;
CREATE UNIQUE INDEX BDS.UK_D_GEN_CLIENTE_N1 ON BDS.D_GEN_CLIENTE (NU_PERI_MES, CO_CLIENTE) TABLESPACE BDS_IDX_01;
CREATE UNIQUE INDEX BDS.UK_D_RIE_TRAMO_DETERIORO_N1 ON BDS.D_RIE_TRAMO_DETERIORO (CO_TRAMO) TABLESPACE BDS_IDX_01;
