-- Create table
create table STG.T_AU_ESTADOSAUTONOMIAS
(
	CODESTADO  NUMBER(3)    NOT NULL, 
	DESCESTADO VARCHAR2(30),
	TIPOESTADO NUMBER(2)    
)
tablespace STG_DATA_01;


-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE STG.T_AU_ESTADOSAUTONOMIAS IS 'TABLA STAGING QUE CONTIENE ESTADOS DE LAS SOLICITUDES DE PRESTAMOS';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN STG.T_AU_ESTADOSAUTONOMIAS.CODESTADO IS 'CODIGO DE ESTADO';
COMMENT ON COLUMN STG.T_AU_ESTADOSAUTONOMIAS.DESCESTADO IS 'DESCRIPCION DEL ESTADO';
COMMENT ON COLUMN STG.T_AU_ESTADOSAUTONOMIAS.TIPOESTADO IS 'TIPO DE ESTADO';



-- Create table
create table ODS.MD_ESTADO_SOLICITUD
(
	CO_ESTADO  NUMBER(3)    NOT NULL,
	DE_ESTADO VARCHAR2(30) ,
	TI_ESTADO NUMBER(2)  ,
	FE_ACTU_DIA DATE  
)
tablespace ODS_DATA_01;


-- Add comments to the table 
comment on table ODS.MD_ESTADO_SOLICITUD is 'TABLA MAESTRA DIARIA QUE CONTIENE ESTADOS DE LAS SOLICITUDES DE PRESTAMOS';
-- Add comments to the columns 
comment on column ODS.MD_ESTADO_SOLICITUD.CO_ESTADO is 'CODIGO DE ESTADO';
comment on column ODS.MD_ESTADO_SOLICITUD.DE_ESTADO is 'DESCRIPCION DEL ESTADO';
comment on column ODS.MD_ESTADO_SOLICITUD.TI_ESTADO is 'TIPO DE ESTADO';
comment on column ODS.MD_ESTADO_SOLICITUD.FE_ACTU_DIA is 'FECHA DE CARGA';


-- Create table
create table ODS.MD_TIPO_PERSONA
(
	CO_PERSONA  VARCHAR2(20) NOT NULL,
	TI_PERSONA VARCHAR2(30),
	FE_ACTU_DIA DATE  
)
tablespace ODS_DATA_01;


-- Add comments to the table 
comment on table ODS.MD_TIPO_PERSONA is 'TABLA MAESTRA DIARIA QUE CONTIENE EL TIPO DE PERSONA';
-- Add comments to the columns 
comment on column ODS.MD_TIPO_PERSONA.CO_PERSONA is 'CODIGO DE TIPO DE PERSONA';
comment on column ODS.MD_TIPO_PERSONA.TI_PERSONA is 'TIPO DE PERSONA';
comment on column ODS.MD_TIPO_PERSONA.FE_ACTU_DIA is 'FECHA DE CARGA';



-- Create table
create table ODS.HD_SOLICITUDES
(
  FE_PROCESO             DATE,
  NU_PERI_MES            NUMBER(6) default (0),
  NU_SOLICITUD           NUMBER(15) default (0),
  CO_CLIENTE             NUMBER(15) default (0),
  CO_ESTA_SOLI           NUMBER(3) default (0),
  CO_TIPO_PRES           VARCHAR2(20) default ('.'),
  NU_METODOLOGIA         NUMBER(12) default (0),
  CO_ANALISTA            VARCHAR2(8) default ('.'),
  CO_TIPO_SOLI           VARCHAR2(5) default ('.'),
  NU_CUOT_GRAC           NUMBER(4) default (0),
  NU_DIA_PAGO            NUMBER(15) default (0),
  NU_DEPENDIENTES        NUMBER(2) default (0),
  IN_CAMPANAS            NUMBER(1) default (0),
  NU_PUNT_CUAL           NUMBER(4) default (0),
  FE_REGI_SOLI           DATE,
  MO_SALARIO             NUMBER(15,2) default (0),
  MO_SOLICITADO          NUMBER(15,2) default (0),
  NU_PLAZ_SOLI           NUMBER(15) default (0),
  VL_ENDEUDAMIENTO       NUMBER(15,4) default (0),
  VL_TIPO_CAMB_OFI       NUMBER(15,9) default (0),
  FE_REGI_PRES           DATE,
  VL_TASA_OPTI           NUMBER(11,7) default (0),
  FE_VENC_LINE           DATE,
  MO_TOTA_GAST           NUMBER(15,2) default (0),
  CO_MOTI_RECH           NUMBER(6) default (0),
  DE_COME_RECH           VARCHAR2(4000) default ('.'),
  CO_PRODUCTO            NUMBER(5) default (0),
  CO_COND_CLIE           VARCHAR2(5) default ('.'),
  VL_TASA_MINI           NUMBER(15,7) default (0),
  VL_TASA_MAXI           NUMBER(15,7) default (0),
  MO_APROBADO            NUMBER(15,2) default (0),
  CO_SUCURSAL            NUMBER(5) default (0),
  VL_TASA                NUMBER(11,7) default (0),
  IN_CONGLOMERADO        VARCHAR2(1) default ('.'),
  DE_PROP_DEST           VARCHAR2(4000) default ('.'),
  FE_ACTU_DIA            DATE default SYSDATE,
  CO_MONEDA              NUMBER(4),
  FE_EVAL_SOLI           DATE,
  CO_TIPO_GRAC           VARCHAR2(1),
  CO_FORM_DESE           VARCHAR2(2),
  NU_PLAZ_APROB          NUMBER(5),
  FE_APRO_SOLI           DATE,
  CO_TIPO_CRED           VARCHAR2(2),
  MO_DEUD_SOLI           NUMBER(15,2),
  IN_EVALUACION          NUMBER(1),
  IN_APROBACION          NUMBER(1),
  IN_DESEMBOLSO          NUMBER(1),
  CO_USUA_TOPA_REGI     VARCHAR2(8),
  CO_USUA_TOPA_EVAL     VARCHAR2(8),
  CO_USUA_TOPA_APRO     VARCHAR2(8),
  MO_PRESTAMO             NUMBER(15,2),
  MO_CUOTA                NUMBER(15,2),
  NU_PLAZOS               NUMBER(6),
  NU_CUOTAS               NUMBER(8)
)
PARTITION BY RANGE (FE_PROCESO)
(
  PARTITION P_SOLICITUDES_20200301 VALUES LESS THAN (TO_DATE(' 2020-03-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    TABLESPACE ODS_DATA_01,
  PARTITION P_SOLICITUDES_MAX VALUES LESS THAN (MAXVALUE)
    TABLESPACE ODS_DATA_01
);


-- Add comments to the table 
comment on table ODS.HD_SOLICITUDES  is 'HISTORICO DIARIO DE SOLICITUDES.';
-- Add comments to the columns 
COMMENT ON COLUMN ODS.HD_SOLICITUDES.FE_PROCESO IS 'FECHA DE PROCESO';
comment on column ODS.HD_SOLICITUDES.NU_PERI_MES  is 'NUMERO DE PERIODO. SE GENERA A PARTIR DEL ANIO Y MES DE LA FECHA EXTRACCION EN FORMATO YYYYMM.';
comment on column ODS.HD_SOLICITUDES.NU_SOLICITUD  is 'NUMERO DE SOLICITUD.';
comment on column ODS.HD_SOLICITUDES.CO_CLIENTE  is 'CODIGO DEL CLIENTE.';
comment on column ODS.HD_SOLICITUDES.CO_ESTA_SOLI  is 'CODIGO DE ESTADO DE LA SOLICITUD.';
comment on column ODS.HD_SOLICITUDES.CO_TIPO_PRES  is 'CODIGO DE TIPO DE PRESTAMO';
comment on column ODS.HD_SOLICITUDES.NU_METODOLOGIA  is 'CODIGO DE METODOLOGIA DE EVALUACION.';
comment on column ODS.HD_SOLICITUDES.CO_ANALISTA  is 'CODIGO DEL ANALISTA.';
comment on column ODS.HD_SOLICITUDES.CO_TIPO_SOLI  is 'CODIGO DE TIPO DE SOLICITUD.';
comment on column ODS.HD_SOLICITUDES.NU_CUOT_GRAC  is 'CANTIDAD DE CUOTAS DE GRACIA.';
comment on column ODS.HD_SOLICITUDES.NU_DIA_PAGO  is 'DIA DE PAGO DE LAS CUOTAS.';
comment on column ODS.HD_SOLICITUDES.NU_DEPENDIENTES  is 'CANTIDAD DE DEPENDIENTES.';
comment on column ODS.HD_SOLICITUDES.IN_CAMPANAS  is 'FLAG QUE INDICA QUE EL CLIENTE ESTA EN CAMPANA. 1=CLIENTE ESTA EN CAMPANA, 0=CLIENTE NO ESTA EN CAMPANA';
comment on column ODS.HD_SOLICITUDES.NU_PUNT_CUAL  is 'PUNTAJE DEL ANALISIS CUALITATIVO.';
comment on column ODS.HD_SOLICITUDES.FE_REGI_SOLI  is 'FECHA DE RECEPCION DE LA SOLICITUD.';
comment on column ODS.HD_SOLICITUDES.MO_SALARIO  is 'MONTO DEL SALARIO DEL CLIENTE.';
comment on column ODS.HD_SOLICITUDES.MO_SOLICITADO  is 'MONTO SOLICITADO.';
comment on column ODS.HD_SOLICITUDES.NU_PLAZ_SOLI  is 'PLAZO SOLICITADO POR EL CLIENTE.';
comment on column ODS.HD_SOLICITUDES.VL_ENDEUDAMIENTO  is 'CAPACIDAD DE ENDEUDAMIENTO (CUOTA DISPONIBLE / CUOTA CREDITO).';
comment on column ODS.HD_SOLICITUDES.VL_TIPO_CAMB_OFI  is 'TIPO DE CAMBIO EN LA SOLICITUD ASOCIADA AL PRESTAMO.';
comment on column ODS.HD_SOLICITUDES.FE_REGI_PRES  is 'FECHA REGISTRADA EN EL SISTEMA TOPAZ, REGISTRO EN LA PRE SOLICITUD.';
comment on column ODS.HD_SOLICITUDES.VL_TASA_OPTI  is 'TASA OPTIMA.';
comment on column ODS.HD_SOLICITUDES.FE_VENC_LINE  is 'FECHA DE VENCIMIENTO DE LA LINEA DE CREDITO ASOCIADA AL PRESTAMO.';
comment on column ODS.HD_SOLICITUDES.MO_TOTA_GAST  is 'MONTO TOTAL DE GASTOS.';
comment on column ODS.HD_SOLICITUDES.CO_MOTI_RECH  is 'MOTIVO DE RECHAZO.';
comment on column ODS.HD_SOLICITUDES.DE_COME_RECH  is 'COMENTARIO POR RECHAZO DE SOLICITUDES.';
comment on column ODS.HD_SOLICITUDES.CO_PRODUCTO  is 'CODIGO DEL PRODUCTO.';
comment on column ODS.HD_SOLICITUDES.CO_COND_CLIE  is 'CODIGO DE CONDICION CLIENTE.';
comment on column ODS.HD_SOLICITUDES.VL_TASA_MINI  is 'TASA MINIMA. CONTIENE EL RANGO DE TASAS INFERIOR MOSTRADO AL MOMENTO DE LA EVALUACION DE LA SOLICITUD.';
comment on column ODS.HD_SOLICITUDES.VL_TASA_MAXI  is 'TASA MAXIMA. CONTIENE EL RANGO DE TASAS SUPERIOR MOSTRADO AL MOMENTO DE LA EVALUACION DE LA SOLICITUD.';
comment on column ODS.HD_SOLICITUDES.MO_APROBADO  is 'MONTO APROBADO DEL PRESTAMO.';
comment on column ODS.HD_SOLICITUDES.CO_SUCURSAL  is 'CODIGO DE SUCURSAL.';
comment on column ODS.HD_SOLICITUDES.VL_TASA  is 'TASA DE INTERES (TNA).';
comment on column ODS.HD_SOLICITUDES.IN_CONGLOMERADO  is 'INDICADOR DE NEGOCIO CONGLOMERADO. 1=PRESENTA NEGOCIO CONGLOMERADO, 0=NO PRESENTA NEGOCIO CONGLOMERADO';
comment on column ODS.HD_SOLICITUDES.DE_PROP_DEST  is 'FUNDAMENTO DEL DESTINO DE CREDITO EN LA PROPUESTA DE CREDITO.';
comment on column ODS.HD_SOLICITUDES.FE_ACTU_DIA  is 'FECHA DE ACTUALIZACION DEL REGISTRO.';
comment on column ODS.HD_SOLICITUDES.CO_MONEDA  is 'CODIGO DE MONEDA';
comment on column ODS.HD_SOLICITUDES.FE_EVAL_SOLI  is 'FECHA DE EVALUACION DE SOLICITUD';
comment on column ODS.HD_SOLICITUDES.CO_TIPO_GRAC  is 'CODIGO DEL TIPO DE GRACIA';
comment on column ODS.HD_SOLICITUDES.CO_FORM_DESE  is 'CODIGO DE LA FORMA DE DESEMBOLSO';
comment on column ODS.HD_SOLICITUDES.NU_PLAZ_APROB  is 'NUMERO DE PLAZO APROBADO';
comment on column ODS.HD_SOLICITUDES.FE_APRO_SOLI  is 'FECHA DE APROBACION DE LA SOLICITUD';
comment on column ODS.HD_SOLICITUDES.CO_TIPO_CRED  is 'CODIGO DEL TIPO DE CREDITO';
comment on column ODS.HD_SOLICITUDES.MO_DEUD_SOLI  is 'MONTO DEUDA DE LA SOLICITUD';
comment on column ODS.HD_SOLICITUDES.IN_EVALUACION  is 'INDICADOR DE SOLICITUD EVALUADA -> 1 = EVALUADA.';
comment on column ODS.HD_SOLICITUDES.IN_APROBACION  is 'INDICADOR DE SOLICITUD APRODADA -> 1 = APROBADA.';
comment on column ODS.HD_SOLICITUDES.IN_DESEMBOLSO  is 'INDICADOR DE SOLICITUD DESEMBOLSADA -> 1 = DESEMBOLSADA.';
comment on column ODS.HD_SOLICITUDES.CO_USUA_TOPA_REGI  is 'CODIGO DEL USUARIO QUE REGISTRA LA SOLICITUD.';
comment on column ODS.HD_SOLICITUDES.CO_USUA_TOPA_EVAL  is 'CODIGO DEL USUARIO QUE EVALUA LA SOLICITUD.';
comment on column ODS.HD_SOLICITUDES.CO_USUA_TOPA_APRO  is 'CODIGO DEL USUARIO QUE APRUEBA LA SOLICITUD.';
COMMENT ON COLUMN ODS.HD_SOLICITUDES.MO_PRESTAMO IS 'MONTO DEL PRESTAMO.';
COMMENT ON COLUMN ODS.HD_SOLICITUDES.MO_CUOTA IS 'MONTO DE LA CUOTA.';
COMMENT ON COLUMN ODS.HD_SOLICITUDES.NU_PLAZOS IS 'NUMERO DE PLAZO SOLICITADO.';
COMMENT ON COLUMN ODS.HD_SOLICITUDES.NU_CUOTAS IS 'NUMERO DE CUOTAS DE LA SOLICITUD.';





--CREAR TABLA HD_PRESTAMOS_REFINANCIADOS
CREATE TABLE ODS.HD_PRESTAMOS_REFINANCIADOS(
	FE_PROCESO DATE,
	NU_SOLICITUD   NUMBER(15),
	NU_PRESTAMO  NUMBER(15),
	CO_CLIENTE   NUMBER(15),
	FE_DESEMBOLSO DATE,
	CO_TIPO_REFI  VARCHAR2(1),
	NU_PRES_CANC  NUMBER(15),
	NU_SOLI_CANC NUMBER(15),
	CO_MONE_CANC  NUMBER(5),
	CO_PROD_CANC  NUMBER(10),  
	CO_CLIE_CANC NUMBER(15),
	MO_CRED_CANC  NUMBER(15,2),
	MO_CRED_IND_CANC  NUMBER(15,2),  
	CO_MOTI_CANC VARCHAR2(1),
	DE_MOTI_CANC VARCHAR2(150), 
	NU_ORDE_PRES_CANC NUMBER(15),
	VL_PORC_PRES_CANC NUMBER(15),
	FE_ACTU_DIA DATE
) TABLESPACE ODS_DATA_01;

--Comentarios
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.FE_PROCESO  IS 'FECHA DE PROCESO DEL REGISTRO.';
COMMENT ON TABLE ODS.HD_PRESTAMOS_REFINANCIADOS IS 'TABLA CREDITOS REFINANCIADOS.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.NU_SOLICITUD IS        'NUMERO DE SOLICITUD.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.NU_PRESTAMO  IS        'NUMERO DE PRESTAMO.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.CO_CLIENTE IS          'CODIGO DE CLIENTE.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.FE_DESEMBOLSO  IS      'FECHA DE DESEMBOLSO.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.CO_TIPO_REFI IS        'CODIGO DEL TIPO DE REFINANCIADO.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.NU_PRES_CANC IS        'NUMERO DE PRESTAMO CANCELADO.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.NU_SOLI_CANC IS        'NUMERO DE SOLICITUD CANCELADO.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.CO_MONE_CANC IS        'CODIGO DE MONEDA.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.CO_PROD_CANC  IS       'CODIGO DE PRODUCTO CANCELADO.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.CO_CLIE_CANC IS        'CODIGO DE CLIENTE CANCELADO.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.MO_CRED_CANC IS        'MONTO CREDITO CANCELA.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.MO_CRED_IND_CANC IS    'MONTO CREDITO INDIVIDUAL CANCELA.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.CO_MOTI_CANC IS        'CODIGO MOTIVO CANCELA.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.DE_MOTI_CANC IS        'DESCRIPCIÓN DE MOTIVO CANCELA.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.NU_ORDE_PRES_CANC IS   'NUMERO DE ORDEN PRESTAMO CANCELA.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.VL_PORC_PRES_CANC IS   'VALOR PORCENTUAL DEL PRESTAMO CANCELA.';
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.FE_ACTU_DIA  IS        'FECHA DE ACTUALIZACIÓN DEL REGISTRO.';
 
-- CREATE TABLE HD_CLIENTES
CREATE  TABLE ODS.HD_CLIENTES
(
  FE_PROCESO        DATE,
  CO_CLIENTE        NUMBER(15) DEFAULT (0) NOT NULL,
  DE_CLIENTE        VARCHAR2(150) DEFAULT ('.'),
  TI_DOCUMENTO      VARCHAR2(1) DEFAULT ('.'),
  DE_TIPO_DOCU      VARCHAR2(150) DEFAULT ('.'),
  NU_DOCUMENTO      VARCHAR2(20) DEFAULT ('.'),
  CO_PAIS_DOCU      VARCHAR2(2) DEFAULT ('.'),
  TI_PERSONA        VARCHAR2(1) DEFAULT ('.'),
  TI_SEXO           VARCHAR2(1) DEFAULT ('.'),
  FE_NACIMIENTO     DATE,
  CO_BLOQUEO        VARCHAR2(1) DEFAULT ('.'),
  DE_BLOQUEO        VARCHAR2(30) DEFAULT ('.'),
  FE_APERTURA       DATE,
  FE_CIERRE         DATE,
  FE_BLOQUEO        DATE,
  CO_ESTADO         VARCHAR2(1) DEFAULT ('.'),
  DE_ESTADO         VARCHAR2(30) DEFAULT ('.'),
  CO_TIPO_CLIE      VARCHAR2(1) DEFAULT ('.'),
  DE_TIPO_CLIE      VARCHAR2(30) DEFAULT ('.'),
  CO_TIPO_CLIE_PASI VARCHAR2(1) DEFAULT ('.'),
  DE_TIPO_CLIE_PASI VARCHAR2(150) DEFAULT ('.'),
  CO_ACTI_ECON_INTE VARCHAR2(8) DEFAULT ('.'),
  CO_SECT_ECON_ALTE NUMBER(3) DEFAULT (0),
  CO_ACTIVIDAD      NUMBER(5) DEFAULT (0),
  CO_ACTI_CIIU      VARCHAR2(8) DEFAULT ('.'),
  NU_CANT_PRES      NUMBER(15) DEFAULT (0),
  CO_SUCURSAL       NUMBER(5) DEFAULT (0),
  NU_MEDI_RECI_LUZ  VARCHAR2(50) DEFAULT ('.'),
  CO_SECT_ECON_INTE NUMBER(2) DEFAULT (0),
  IN_EMPLEADO       NUMBER(1) DEFAULT (0),
  CO_TIPO_RESI      NUMBER(1) DEFAULT (0),
  DE_TIPO_RESI      VARCHAR2(150) DEFAULT ('.'),
  CO_SBS_CLIE       NUMBER(15) DEFAULT (0),
  CO_CATE_PERS      VARCHAR2(2) DEFAULT ('.'),
  DE_CATE_PERS      VARCHAR2(150) DEFAULT ('.'),
  CO_MAGN_EMPR      NUMBER(2) DEFAULT (0),
  DE_MAGN_EMPR      VARCHAR2(150) DEFAULT ('.'),
  CO_CLAS_INDE      VARCHAR2(2) DEFAULT ('.'),
  DE_CLAS_INDE      VARCHAR2(150) DEFAULT ('.'),
  CO_PROFESION      NUMBER(5) DEFAULT (0),
  DE_PROFESION      VARCHAR2(150) DEFAULT ('.'),
  CO_NIVE_EDUC      VARCHAR2(2) DEFAULT ('.'),
  DE_NIVE_EDUC      VARCHAR2(150) DEFAULT ('.'),
  CO_ESTA_CIVI      VARCHAR2(5) DEFAULT ('.'),
  CO_BASE_NEGA      NUMBER(2) DEFAULT (0),
  CO_CLAS_DEPE      VARCHAR2(5) DEFAULT ('.'),
  FE_INGRESO        DATE,
  IN_MIGRADO        VARCHAR2(1) DEFAULT ('.'),
  CO_NATU_JURI      VARCHAR2(4) DEFAULT ('.'),
  FE_APER_PRIM_CRED DATE,
  TI_DOCU_CONY      VARCHAR2(1) DEFAULT ('.'),
  NU_DOCU_CONY      VARCHAR2(20) DEFAULT ('.'),
  CO_PAIS_CONY      VARCHAR2(2) DEFAULT ('.'),
  DE_CONYUGE        VARCHAR2(150) DEFAULT ('.'),
  IN_SEPA_BIEN      VARCHAR2(1) DEFAULT ('.'),
  FE_ACTU_DIA       DATE
)
  partition by range (FE_PROCESO)
(
  partition P_HD_CLIENTES_20150101 values less than (TO_DATE(' 2015-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
    tablespace ODS_DATA_01,
  partition P_HD_CLIENTES_MAX values less than (MAXVALUE)
    tablespace ODS_DATA_01
    );
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE ODS.HD_CLIENTES  IS 'HISTORICO DIARIO DE CLIENTES. CONTIENE LA INFORMACION RELACIONADA A LOS CLIENTES DE LA INSTITUCION';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN ODS.HD_CLIENTES.FE_PROCESO  IS 'FECHA DE PROCESO DE LA INFORMACION.';  
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_CLIENTE  IS 'CODIGO DEL CLIENTE';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_CLIENTE  IS 'DESCRIPCION DEL CLIENTE';
COMMENT ON COLUMN ODS.HD_CLIENTES.TI_DOCUMENTO  IS 'TIPO DE DOCUMENTO. TIPO DE DOCUMENTO DE LA PERSONA TITULAR DEL CLIENTE';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_TIPO_DOCU  IS 'DESCRIPCION DEL TIPO DOCUMENTO';
COMMENT ON COLUMN ODS.HD_CLIENTES.NU_DOCUMENTO  IS 'NUMERO DE DOCUMENTO DE LA PERSONA TITULAR DEL CLIENTE';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_PAIS_DOCU  IS 'CODIGO DEL PAIS DEL DOCUMENTO.';
COMMENT ON COLUMN ODS.HD_CLIENTES.TI_PERSONA  IS 'TIPO DE PERSONA.(N=PERSONA NATURAL / J=PERSONA JURIDICA).';
COMMENT ON COLUMN ODS.HD_CLIENTES.TI_SEXO  IS 'TIPO DE SEXO.(PARA PERSONAS NATURALES M=MASCULINO / F=FEMENINO) PARA LOS DEMAS CASOS MOSTRARA UN PUNTO.';
COMMENT ON COLUMN ODS.HD_CLIENTES.FE_NACIMIENTO  IS 'FECHA NACIMIENTO. SOLO SE CARGA PARA PERSONAS NATURALES.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_BLOQUEO  IS 'CODIGO DE BLOQUEO.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_BLOQUEO  IS 'DESCRIPCION DEL BLOQUEO.';
COMMENT ON COLUMN ODS.HD_CLIENTES.FE_APERTURA  IS 'FECHA DE APERTURA. FECHA EN QUE SE APERTURO EL CLIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.FE_CIERRE  IS 'FECHA DE CIERRE. SE CARGA CUANDO EL PRESTAMO SE ENCUENTRA EN ESTADO CASTIGADO';
COMMENT ON COLUMN ODS.HD_CLIENTES.FE_BLOQUEO  IS 'FECHA DE BLOQUEO. FECHA EN QUE SE BLOQUEO EL CLIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_ESTADO  IS 'CODIGO DE ESTADO DEL CLIENTE. (B = BAJA, K=BLOQUEADO ,O=PREVIO BAJA ,V=VIGENTE).';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_ESTADO  IS 'DESCRIPCION DEL ESTADO DEL CLIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_TIPO_CLIE  IS 'CODIGO DEL TIPO DE CLIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_TIPO_CLIE  IS 'DESCRIPCION DEL TIPO DE CLIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_TIPO_CLIE_PASI  IS 'CODIGO TIPO DE CLIENTE PASIVOS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_TIPO_CLIE_PASI  IS 'DESCRIPCION DEL TIPO DE CLIENTE PASIVOS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_ACTI_ECON_INTE  IS 'CODIGO DE ACTIVIDAD ECONOMICA INTERNA.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_SECT_ECON_ALTE  IS 'CODIGO SECTOR ECONOMICO ALTERNATIVO.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_ACTIVIDAD  IS 'CODIGO DE ACTIVIDAD.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_ACTI_CIIU  IS 'CODIGO DE ACTIVIDAD CIIU.';
COMMENT ON COLUMN ODS.HD_CLIENTES.NU_CANT_PRES  IS 'CANTIDAD DE PRESTAMOS DEL CLIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_SUCURSAL  IS 'CODIGO DE  SUCURSAL EN LA QUE SE APERTURO EL CLIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.NU_MEDI_RECI_LUZ  IS 'NUMERO DE MEDIDOR RECIBO DE LUZ.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_SECT_ECON_INTE  IS 'CODIGO DEL SECTOR ECONOMICO INTERNO.';
COMMENT ON COLUMN ODS.HD_CLIENTES.IN_EMPLEADO  IS 'INDICADOR DE EMPLEADO. (0: NO ES EMPLEADO / 1: EMPLEADO).';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_TIPO_RESI  IS 'CODIGO DE TIPO DE RESIDENCIA.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_TIPO_RESI  IS 'DESCRIPCION DE TIPO DE RESIDENCIA.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_SBS_CLIE  IS 'CODIGO SBS CLIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_CATE_PERS  IS 'CODIGO DE CATEGORIZACION DE LA PERSONA. SOLOS SE CARGA PARA LAS PERSONAS FISICAS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_CATE_PERS  IS 'DESCRIPCION DE CODIGO DE CATEGORIZACION DE LA PERSONA. SOLOS SE CARGA PARA LAS PERSONAS FISICAS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_MAGN_EMPR  IS 'CODIGO DE MAGNITUD DE EMPRESA. SOLO SE CARGA PARA PERSONAS FISICAS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_MAGN_EMPR  IS 'DESCRIPCION DE CODIGO DE MAGNITUD DE EMPRESA. SOLO SE CARGA PARA PERSONAS FISICAS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_CLAS_INDE  IS 'CODIGO DE CLASIFICACION INDEPENDIENTE. SOLO SE CARGA PARA PERSONAS FISICAS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_CLAS_INDE  IS 'DESCRIPCION DE CODIGO DE CLASIFICACION INDEPENDIENTE. SOLO SE CARGA PARA PERSONAS FISICAS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_PROFESION  IS 'CODIGO DE PROFESION. SOLO SE CARGA PARA PERSONAS FISICAS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_PROFESION  IS 'DESCRIPCION DE LA PROFESION.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_NIVE_EDUC  IS 'CODIGO DE NIVEL EDUCATIVO. SOLO SE CARGA PARA PERSONAS FISICAS.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_NIVE_EDUC  IS 'DESCRIPCION DEL NIVEL EDUCATIVO.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_ESTA_CIVI  IS 'ESTADO CIVIL DEL CLIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_BASE_NEGA  IS 'ESTADO EN BASE NEGATIVA.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_CLAS_DEPE  IS 'CLASIFICACION DEL CLIENTE DEPENDIENTE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.FE_INGRESO  IS 'FECHA DE INGRESO DEL CLIENTE, INCLUYE BT.';
COMMENT ON COLUMN ODS.HD_CLIENTES.IN_MIGRADO  IS 'INDICADOR DE CLIENTE MIGRADO.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_NATU_JURI  IS 'CODIGO DE NATURALEZA JURIDICA.';
COMMENT ON COLUMN ODS.HD_CLIENTES.FE_APER_PRIM_CRED  IS 'FECHA DE DESEMBOLSO DEL PRIMER CREDITO.';
COMMENT ON COLUMN ODS.HD_CLIENTES.TI_DOCU_CONY  IS 'TIPO DE DOCUMENTO DEL CONYUGE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.NU_DOCU_CONY  IS 'NUMERO DE DOCUMENTO DEL CONYUGE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.CO_PAIS_CONY  IS 'PAIS DE DOCUMENTO DEL CONYUGE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.DE_CONYUGE  IS 'NOMBRE DEL CONYUGE.';
COMMENT ON COLUMN ODS.HD_CLIENTES.IN_SEPA_BIEN  IS 'INDICADOR DE SEPARACION DE BIENES.';
COMMENT ON COLUMN ODS.HD_CLIENTES.FE_ACTU_DIA  IS 'FECHA DE INGRESO DEL REGISTRO.'; 


------------------------------------------
CREATE TABLE ODS.TP_BITACORA_PRE_PRESTAMO
( 
	NU_SOLICITUD        NUMBER(15), 
	FE_PROCESO          DATE,
	TX_HORA_PROC        VARCHAR2(12),
	CO_USUA_TOPA        VARCHAR2(8),
	FE_ACTU_DIA         DATE
) 
TABLESPACE ODS_DATA_01;
COMMENT ON TABLE ODS.TP_BITACORA_PRE_PRESTAMO IS 'TABLA DE BITACORA DE PRE-PRESTAMO PARA IDENTIFICAR LAS SOLICITUDES APROBADAS.';
COMMENT ON COLUMN ODS.TP_BITACORA_PRE_PRESTAMO.NU_SOLICITUD IS 'NUMERO DE SOLICITUD.';
COMMENT ON COLUMN ODS.TP_BITACORA_PRE_PRESTAMO.FE_PROCESO IS 'FECHA DE PROCESO DEL PRE-PRESTAMO.';
COMMENT ON COLUMN ODS.TP_BITACORA_PRE_PRESTAMO.TX_HORA_PROC IS 'HORA DE PROCESO DE PRE-PRESTAMO.';
COMMENT ON COLUMN ODS.TP_BITACORA_PRE_PRESTAMO.CO_USUA_TOPA IS 'CODIGO DEL USUARIO DE TOPAZ QUE REALIZO EL PRE-PRESTAMO.';
COMMENT ON COLUMN ODS.TP_BITACORA_PRE_PRESTAMO.FE_ACTU_DIA IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
