-- Crear tabla BDS.F_RIE_COBRANZA
CREATE TABLE BDS.F_RIE_COBRANZA ( 
NU_PERI_MES               NUMBER(6)     DEFAULT 0,
NU_PERI_CART              NUMBER(6)     DEFAULT 0,
NU_PRESTAMO               NUMBER(15)    DEFAULT 0,
CO_CLIENTE                NUMBER(15)    DEFAULT 0, 
CO_ESTA_PRES              VARCHAR2(1)   DEFAULT '.',
CO_PRODUCTO               NUMBER(5)     DEFAULT 0, 
CO_REFINANCIACION         VARCHAR2(5)   DEFAULT '.',
CO_MONEDA                 NUMBER(5)     DEFAULT 0, 
CO_AGENCIA                NUMBER(5)     DEFAULT 0,
CO_TIPO_PRES              VARCHAR2(3)   DEFAULT '.',
CO_CRITERIO               NUMBER(4)     DEFAULT 0,
CO_FUNC_RESP              NUMBER(8)     DEFAULT 0,
CO_TRAMO                  NUMBER(3)     DEFAULT 0,
NU_COSECHA                NUMBER(6)     DEFAULT 0,
NU_CUOT_TOTA              NUMBER(15,2)  DEFAULT 0,
NU_CUOT_PAGA              NUMBER(15,2)  DEFAULT 0,
NU_LINE_CRED              NUMBER(15)    DEFAULT 0,
NU_EDAD                   NUMBER(3)     DEFAULT 0,
MO_DESEMBOLSO             NUMBER(15,2)  DEFAULT 0,
MO_SALD_ACTU              NUMBER(15,2)  DEFAULT 0,
MO_TOTA_DEUD              NUMBER(15,2)  DEFAULT 0,
MO_SALD_DISP_LINE         NUMBER(15,2)  DEFAULT 0,
MO_SALD_CAST_MES          NUMBER(15,2)  DEFAULT 0,
MO_SALD_PASE              NUMBER(15,2)  DEFAULT 0,
MO_INTE_DEVE_VIGE         NUMBER(15,2)  DEFAULT 0,
MO_INTE_DEVE_SUST         NUMBER(15,2)  DEFAULT 0,
IN_CASTIGO                NUMBER(1)     DEFAULT 0,
IN_ACTIVO                 NUMBER(1)     DEFAULT 1,
NU_TRAM_PASE              NUMBER(6)     DEFAULT 0,
FE_DESEMBOLSO             DATE,
FE_VENCIMIENTO            DATE,
FE_ULTI_PAGO              DATE,
FE_CASTIGO                DATE,
FE_VENC_LINE              DATE,
VL_TNA                    NUMBER(11,7)  DEFAULT 0,
MO_INTE_COMP_ATRA         NUMBER(15,2)  DEFAULT 0,
MO_INTE_MORA_PEND         NUMBER(15,2)  DEFAULT 0,
FE_ACTU_MES               DATE          DEFAULT SYSDATE,
CO_ACTU_USER              VARCHAR2(50)  DEFAULT USER,
NU_CARGA                  INTEGER,
IN_ESTA_REGI              INTEGER       DEFAULT 0 
) 
PARTITION BY RANGE (NU_PERI_MES)
(
 PARTITION P_RIE_COBRANZA_201601 VALUES LESS THAN (201602)   TABLESPACE BDS_DATA_01,
 PARTITION P_RIE_COBRANZA_MAX    VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);

COMMENT ON TABLE BDS.F_RIE_COBRANZA IS 'TABLA DE HECHOS DE COBRANZAS.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_PERI_MES        IS 'PERIODO DE COBRANZA EN FORMATO YYYYMM.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_PERI_CART       IS 'PERIODO DE CARTERA EN FORMATO YYYYMM. HACE REFERENCIA AL PERIODO DE CARTERA PROCESADO';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_PRESTAMO        IS 'NUMERO DE PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_CLIENTE         IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_ESTA_PRES       IS 'CODIGO DE ESTADO DEL PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_PRODUCTO        IS 'CODIGO DE PRODUCTO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_REFINANCIACION  IS 'CODIGO DE REFINANCIACION.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_MONEDA          IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_AGENCIA         IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_TIPO_PRES       IS 'CODIGO DE TIPO DE PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_CRITERIO        IS 'CODIGO DE TIPO DE CRITERIO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_FUNC_RESP       IS 'CODIGO DE FUNCIONARIO RESPONSABLE.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_TRAMO           IS 'CODIGO DE TRAMO DE DETERIORO DE UN PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_COSECHA         IS 'NUMERO DE COSECHA.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_CUOT_TOTA       IS 'NUMERO DE CUOTAS DEL PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_CUOT_PAGA       IS 'NUMERO DE CUOTAS PAGADAS.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_LINE_CRED       IS 'NUMERO DE LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_EDAD            IS 'EDAD DEL CLIENTE.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_DESEMBOLSO      IS 'MONTO DE DESEMBOLSO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_SALD_ACTU       IS 'SALDO DE CAPITAL.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_TOTA_DEUD       IS 'DEUDA TOTAL.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_SALD_DISP_LINE  IS 'SALDO DISPONIBLE DE LA LINEA.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_SALD_CAST_MES   IS 'MONTO DE CASTIGO DEL MES.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_SALD_PASE       IS 'MONTO DE SALDO PASE.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_INTE_DEVE_VIGE  IS 'MONTO DE INTERESES DEVENGADOS VIGENTES.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_INTE_DEVE_SUST  IS 'MONTO DE INTERESES DEVENGADOS SUSTITUTORIOS.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.IN_CASTIGO         IS 'INDICADOR DE CASTIGO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.IN_ACTIVO          IS 'INDICADOR DE ACTIVO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_TRAM_PASE       IS 'NUMERO DE TRAMOS DE PASE.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.FE_DESEMBOLSO      IS 'FECHA DE DESEMBOLSO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.FE_VENCIMIENTO     IS 'FECHA DE VENCIMIENTO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.FE_ULTI_PAGO       IS 'FECHA DE ULTIMO PAGO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.FE_CASTIGO         IS 'FECHA DE CASTIGO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.FE_VENC_LINE       IS 'FECHA DE VENCIMIENTO DE LA LINEA.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.VL_TNA             IS 'TASA DE INTERES NOMINAL ANUAL.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_INTE_COMP_ATRA  IS 'MONTO DE INTERES COMPENSATORIO EN ATRASO.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.MO_INTE_MORA_PEND  IS 'MONTO DE INTERES DE MORA PENDIENTE.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.FE_ACTU_MES        IS 'FECHA DE ACTUALIZACION MENSUAL DE LA TABLA.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.CO_ACTU_USER       IS 'USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.NU_CARGA           IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN BDS.F_RIE_COBRANZA.IN_ESTA_REGI       IS 'ESTADO DEL REGISTRO.';

--Crear Tabla D_GEN_CLIENTE
CREATE  TABLE BDS.D_GEN_CLIENTE
(
NU_PERI_MES       NUMBER(6)     DEFAULT 0,
CO_CLIENTE        NUMBER(15)    DEFAULT 0,
NO_CLIENTE        VARCHAR(250)  DEFAULT '.',
TI_DOCUMENTO      VARCHAR2(1)   DEFAULT '.',
NU_DOCUMENTO      VARCHAR2(20)  DEFAULT '.',
TI_SEXO           VARCHAR2(1)   DEFAULT '.',
FE_NACIMIENTO     DATE,
CO_SBS            NUMBER(10)    DEFAULT 0,
CO_PAIS_DOCU      VARCHAR2(2)   DEFAULT '.',
CO_CATE_PERS      VARCHAR2(1)   DEFAULT '.',
DE_CATE_PERS      VARCHAR2(150) DEFAULT '.',
CO_CLAS_DEPE      VARCHAR2(1)   DEFAULT '.',
DE_CLAS_DEPE      VARCHAR2(150) DEFAULT '.',
CO_ESTA_CIVI      VARCHAR2(1)   DEFAULT '.',
DE_ESTA_CIVI      VARCHAR2(150) DEFAULT '.',
CO_SEGM_COBR      VARCHAR2(4)   DEFAULT '.',
DE_SEGM_COBR      VARCHAR2(150) DEFAULT '.', 
CO_SEGM_MORA      VARCHAR2(4)   DEFAULT '.',
DE_SEGM_MORA      VARCHAR2(150) DEFAULT '.',
CO_CALI_INTE_FINA VARCHAR2(3)   DEFAULT '.',
DE_CALI_INTE_FINA VARCHAR2(150) DEFAULT '.',
CO_CALI_SIST_FINA VARCHAR2(3)   DEFAULT '.',
DE_CALI_SIST_FINA VARCHAR2(150) DEFAULT '.',
CO_CALI_ALIN      VARCHAR2(3)   DEFAULT '.',
DE_CALI_ALIN      VARCHAR2(150) DEFAULT '.',
NU_CANT_PRES      NUMBER(5)     DEFAULT 0,
CO_SEGM_NEGO      VARCHAR2(4)   DEFAULT '.',
DE_SEGM_NEGO      VARCHAR2(150) DEFAULT '.',
CO_SEGMENTACION   VARCHAR2(4)   DEFAULT '.',
DE_SEGMENTACION   VARCHAR2(150) DEFAULT '.',
TI_PERSONA        VARCHAR2(3)   DEFAULT '.',
FE_ACTU_MES       DATE          DEFAULT SYSDATE
)
PARTITION BY RANGE (NU_PERI_MES)
(
 PARTITION P_D_GEN_CLIENTE_201503 VALUES LESS THAN (201504)   TABLESPACE BDS_DATA_01,
 PARTITION P_D_GEN_CLIENTE_MAX    VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
)
;
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE BDS.D_GEN_CLIENTE IS 'TABLA DIMENSION GENERICA DE CLIENTES QUE CONTIENE INFORMACION PARA COBRANZAS.';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.NU_PERI_MES       IS 'PERIODO DEL MES DE PROCESAMIENTO.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_CLIENTE        IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.NO_CLIENTE        IS 'NOMBRE DE CLIENTE.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.TI_DOCUMENTO      IS 'TIPO DE DOCUMENTO.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.NU_DOCUMENTO      IS 'NUMERO DE DOCUMENTO DE IDENTIDAD DEL CLIENTE.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.TI_SEXO           IS 'TIPO DE SEXO.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.FE_NACIMIENTO     IS 'FECHA DE NACIMIENTO.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_SBS            IS 'CODIGO SBS DEL CLIENTE.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_PAIS_DOCU      IS 'CODIGO DE PAIS DEL DOCUMENTO.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_CATE_PERS      IS 'CODIGO DE CATEGORIZACIÓN PERSONA, SOLO SE CARGA PARA PERSONAS FISICAS.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_CATE_PERS      IS 'DESCRIPCION DE CODIGO DE CATEGORIZACION PERSONA. SOLO SE CARGA PARA LAS PERSONAS FISICAS.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_CLAS_DEPE      IS 'CODIGO DE CLASIFICACION DEL CLIENE DEPENDIENTE.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_CLAS_DEPE      IS 'DESCRIPCION DE CLASIFICACION DEL CLIENTE DEPENDIENTE.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_ESTA_CIVI      IS 'CODIGO DE ESTADO CIVIL.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_ESTA_CIVI      IS 'DESCRIPCION DE ESTADO CIVIL DEL CLIENTE.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_SEGM_COBR      IS 'CODIGO DE SEGMENTO DE COBRANZA.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_SEGM_COBR      IS 'DESCRIPCION DE SEGMENTACION COBRANZA.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_SEGM_MORA      IS 'CODIGO DE SEGMENTO DE MORA.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_SEGM_MORA      IS 'DESCRIPCION DE SEGMENTACION MORA.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_CALI_INTE_FINA IS 'CODIGO DE CALIFICACIÓN INTERNA FINAL.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_CALI_INTE_FINA IS 'DESCRIPCION DE CALIFICACION INTERNA FINAL.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_CALI_SIST_FINA IS 'CODIGO DE CALIFICACIÓN EN SISTEMA FINANCIERO.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_CALI_SIST_FINA IS 'DESCRIPCION DE CALIFICACION SISTEMA FINANCIERO.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_CALI_ALIN      IS 'CODIGO DE CALIFICACIÓN ALINEADA.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_CALI_ALIN      IS 'DESCRIPCION DE LA CALIFICACION ALINEADA.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.NU_CANT_PRES      IS 'NUMERO DE PRESTAMOS EN GENERAL.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_SEGM_NEGO      IS 'CODIGO DE SEGMENTO DE COMERCIAL.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_SEGM_NEGO      IS 'DESCRIPCION DE SEGMENTACION COMERCIAL.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.CO_SEGMENTACION   IS 'CODIGO DE SEGMENTO DE INTERNA.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.DE_SEGMENTACION   IS 'DESCRIPCION DE SEGMENTACION DE RIESGOS.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.TI_PERSONA        IS 'TIPO DE PERSONA.';
COMMENT ON COLUMN BDS.D_GEN_CLIENTE.FE_ACTU_MES       IS 'FECHA DE ACTUALIZACION MENSUAL DE LA TABLA.';


--Crear Tabla D_RIE_TRAMO_DETERIORO
CREATE TABLE BDS.D_RIE_TRAMO_DETERIORO
(
CO_TRAMO          NUMBER(2)    DEFAULT 0,
DE_TRAMO          VARCHAR2(35) DEFAULT '.',
FE_ACTU_DIA       DATE         DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;

COMMENT ON TABLE  BDS.D_RIE_TRAMO_DETERIORO IS 'TABLA DIMENSION DE RIESGOS DE LOS TRAMOS DE DETERIORO'; 
COMMENT ON COLUMN BDS.D_RIE_TRAMO_DETERIORO.CO_TRAMO     IS 'CODIGO DE TRAMO.';
COMMENT ON COLUMN BDS.D_RIE_TRAMO_DETERIORO.DE_TRAMO     IS 'DESCRIPCION DEL TRAMO CALCULADO.' ;
COMMENT ON COLUMN BDS.D_RIE_TRAMO_DETERIORO.FE_ACTU_DIA  IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';


-- Create table BDS.D_GEN_CRITERIO
CREATE TABLE BDS.D_GEN_CRITERIO
(
CO_CRITERIO            NUMBER(4)     DEFAULT 0,   
DE_CRITERIO            VARCHAR2(150) DEFAULT '.',
FE_ACTU_DIA            DATE          DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;
COMMENT ON TABLE BDS.D_GEN_CRITERIO IS 'TABLA DIMENSION GENERICA DE CRITERIOS.';
COMMENT ON COLUMN BDS.D_GEN_CRITERIO.CO_CRITERIO  IS 'CODIGO DE CRITERIO.';
COMMENT ON COLUMN BDS.D_GEN_CRITERIO.DE_CRITERIO  IS 'DESCRIPCION DE CRITERIO.';
COMMENT ON COLUMN BDS.D_GEN_CRITERIO.FE_ACTU_DIA  IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';
