-- TABLAS EXTERNAS DE
CREATE TABLE STG.DE_CAMPANA_VIGENCIA
(IDCAMPANA VARCHAR2 (250),
PERIODO VARCHAR2 (250),
CODCAMPANA VARCHAR2 (250),
FECINIVIGENCIA VARCHAR2 (250),
FECFINVIGENCIA VARCHAR2 (250))
ORGANIZATION EXTERNAL
( TYPE ORACLE_LOADER
DEFAULT DIRECTORY DIR_IN_DE_CRM
ACCESS PARAMETERS
( RECORDS DELIMITED BY NEWLINE
SKIP 1
BADFILE '%a_%p.bad'
LOGFILE '%a_%p.log'
NOLOGFILE
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LRTRIM
MISSING FIELD VALUES ARE NULL
REJECT ROWS WITH ALL NULL FIELDS
)
LOCATION
(DIR_IN_DE_CRM:'DE_CAMPANA_VIGENCIA.csv'
)
)
REJECT LIMIT UNLIMITED;

CREATE TABLE STG.DE_CAMPANA
(CODCAMPANA VARCHAR2 (250),
CAMPANA_ABR VARCHAR2 (250),
CAMPANA VARCHAR2 (250),
TIPOCAMPANA VARCHAR2 (250),
TIPOFERTA VARCHAR2 (250),
CATEGORIA VARCHAR2 (250),
FLG_ACTIVO VARCHAR2 (250),
FECREGISTRO VARCHAR2 (250),
CODUSUARIOACT VARCHAR2 (250))
ORGANIZATION EXTERNAL
( TYPE ORACLE_LOADER
DEFAULT DIRECTORY DIR_IN_DE_CRM
ACCESS PARAMETERS
( RECORDS DELIMITED BY NEWLINE
SKIP 1
BADFILE '%a_%p.bad'
LOGFILE '%a_%p.log'
NOLOGFILE
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LRTRIM
MISSING FIELD VALUES ARE NULL
REJECT ROWS WITH ALL NULL FIELDS
)
LOCATION
(DIR_IN_DE_CRM:'DE_CAMPANA.csv'
)
)
REJECT LIMIT UNLIMITED;

CREATE TABLE STG.DE_CANAL
(CODCANAL VARCHAR2 (250),
DESCANAL_ABR VARCHAR2 (250),
DESCANAL VARCHAR2 (250),
DESCANALVENTA VARCHAR2 (250),
GRUPOCANAL VARCHAR2 (250),
DESGRUPOCANAL VARCHAR2 (250),
TIPOCANAL VARCHAR2 (250),
FLG_ACTIVO VARCHAR2 (250))
ORGANIZATION EXTERNAL
( TYPE ORACLE_LOADER
DEFAULT DIRECTORY DIR_IN_DE_CRM
ACCESS PARAMETERS
( RECORDS DELIMITED BY NEWLINE
SKIP 1
BADFILE '%a_%p.bad'
LOGFILE '%a_%p.log'
NOLOGFILE
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LRTRIM
MISSING FIELD VALUES ARE NULL
REJECT ROWS WITH ALL NULL FIELDS
)
LOCATION
(DIR_IN_DE_CRM:'DE_CANAL.csv'
)
)
REJECT LIMIT UNLIMITED;

CREATE TABLE STG.DE_RESULTADO_CONTACTO
(IDCANAL VARCHAR2 (250),
IDRESPUESTACANAL VARCHAR2 (250),
DESRESPUESTACANAL VARCHAR2 (250),
CODRESPUESTA VARCHAR2 (250),
DESRESPUESTA VARCHAR2 (250),
CODRESULTADO VARCHAR2 (250),
DESRESULTADO VARCHAR2 (250))
ORGANIZATION EXTERNAL
( TYPE ORACLE_LOADER
DEFAULT DIRECTORY DIR_IN_DE_CRM
ACCESS PARAMETERS
( RECORDS DELIMITED BY NEWLINE
SKIP 1
BADFILE '%a_%p.bad'
LOGFILE '%a_%p.log'
NOLOGFILE
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LRTRIM
MISSING FIELD VALUES ARE NULL
REJECT ROWS WITH ALL NULL FIELDS
)
LOCATION
(DIR_IN_DE_CRM:'DE_RESULTADOCONTACTO.csv'
)
)
REJECT LIMIT UNLIMITED;

CREATE TABLE STG.DE_MKT_PRODUCTOS
(COD_PRODUCTO VARCHAR2 (250),
FAMILIA_IC VARCHAR2 (250),
SUBFAMILIA_IC VARCHAR2 (250),
GRUPO_0 VARCHAR2 (250),
GRUPO_1 VARCHAR2 (250),
GRUPO_2 VARCHAR2 (250),
GRUPO_3 VARCHAR2 (250))
ORGANIZATION EXTERNAL
( TYPE ORACLE_LOADER
DEFAULT DIRECTORY DIR_IN_DE_CRM
ACCESS PARAMETERS
( RECORDS DELIMITED BY NEWLINE
SKIP 1
BADFILE '%a_%p.bad'
LOGFILE '%a_%p.log'
NOLOGFILE
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LRTRIM
MISSING FIELD VALUES ARE NULL
REJECT ROWS WITH ALL NULL FIELDS
)
LOCATION
(DIR_IN_DE_CRM:'DIM_PRODUCTOS.csv'
)
)
REJECT LIMIT UNLIMITED;

CREATE TABLE STG.DE_REL_PROD_CAMPANA
(ID_REL_PC VARCHAR2 (250),
CODCAMPANA VARCHAR2 (250),
CODPRODUCTO VARCHAR2 (250),
FLGMARCA VARCHAR2 (250),
FLGACTIVO VARCHAR2 (250),
PERIODOINICIO VARCHAR2 (250))
ORGANIZATION EXTERNAL
( TYPE ORACLE_LOADER
DEFAULT DIRECTORY DIR_IN_DE_CRM
ACCESS PARAMETERS
( RECORDS DELIMITED BY NEWLINE
SKIP 1
BADFILE '%a_%p.bad'
LOGFILE '%a_%p.log'
NOLOGFILE
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' LRTRIM
MISSING FIELD VALUES ARE NULL
REJECT ROWS WITH ALL NULL FIELDS
)
LOCATION
(DIR_IN_DE_CRM:'DE_REL_PROD_CAMPANA.csv'
)
)
REJECT LIMIT UNLIMITED;


-- TABLAS STG
CREATE TABLE STG.T_CAMPANA_VIGENCIA(
	IDCAMPANA      VARCHAR2 (13),
	PERIODO        INTEGER,
	CODCAMPANA     INTEGER,
	FECINIVIGENCIA DATE,
	FECFINVIGENCIA DATE,
	FE_ACTU_DIA    DATE DEFAULT SYSDATE
) TABLESPACE STG_DATA_01;
COMMENT ON TABLE  STG.T_CAMPANA_VIGENCIA                IS 'TABLA QUE ALMACENA LA VIGENCIA DE LAS CAMPANAS EN DETERMINADO PERIODO';
COMMENT ON COLUMN STG.T_CAMPANA_VIGENCIA.IDCAMPANA      IS 'ID DE LA CAMPANA DEFINIDA POR EL PERIODO O MES DE GENERACION + CODIGO DE LA CAMPANA + CORRELATIVO';
COMMENT ON COLUMN STG.T_CAMPANA_VIGENCIA.PERIODO        IS 'MES DE VIGENCIA DE LA CAMPANA';
COMMENT ON COLUMN STG.T_CAMPANA_VIGENCIA.CODCAMPANA     IS 'CODIGO DE LA CAMPANA';
COMMENT ON COLUMN STG.T_CAMPANA_VIGENCIA.FECINIVIGENCIA IS 'FECHA INICIO DE VIGENCIA';
COMMENT ON COLUMN STG.T_CAMPANA_VIGENCIA.FECFINVIGENCIA IS 'FECHA FIN DE VIGENCIA';
COMMENT ON COLUMN STG.T_CAMPANA_VIGENCIA.FE_ACTU_DIA    IS 'FECHA ACTUALIZACION DIA';

CREATE TABLE STG.T_CAMPANA(
	CODCAMPANA    INTEGER,
	CAMPANA_ABR   VARCHAR2(50),
	CAMPANA       VARCHAR2(50),
	TIPOCAMPANA   VARCHAR2(50),
	TIPOFERTA     VARCHAR2(50),
	CATEGORIA     VARCHAR2(50),
	FLG_ACTIVO    INTEGER,
	CODUSUARIOACT VARCHAR2(250),
	FECREGISTRO   DATE,
	FE_ACTU_DIA   DATE DEFAULT SYSDATE
) TABLESPACE STG_DATA_01;
COMMENT ON TABLE  STG.T_CAMPANA               IS 'TABLA MAESTRA DE CAMPANAS';
COMMENT ON COLUMN STG.T_CAMPANA.CODCAMPANA    IS 'CODIGO DE LA CAMPANA';
COMMENT ON COLUMN STG.T_CAMPANA.CAMPANA_ABR   IS 'NOMBRE DE LA CAMPANA ABREVIADA';
COMMENT ON COLUMN STG.T_CAMPANA.CAMPANA       IS 'NOMBRE DE LA CAMPANA';
COMMENT ON COLUMN STG.T_CAMPANA.TIPOCAMPANA   IS 'TIPO DE CAMPANA: TIPO DE EVALUACION PARA EL GRUPO COMERCIAL U OBJETIVO ESPECIFICO PARA EL RESTO';
COMMENT ON COLUMN STG.T_CAMPANA.TIPOFERTA     IS 'TIPO DE PRODUCTO DE LA OFERTA: ACTIVO, PASIVO, SEGURO, TIPO DE CAMBIO';
COMMENT ON COLUMN STG.T_CAMPANA.CATEGORIA     IS 'CATEGORIZACION DE LA CAMPANA POR EL OBJETIVO DE LA MISMA: COMERCIAL O VENTA, TRANSACCIONAL O USO, RELACIONAL';
COMMENT ON COLUMN STG.T_CAMPANA.FLG_ACTIVO    IS 'INDICADOR QUE INDICA SI LA CAMPANA SIGUE ACTIVA O NO. 1:SI, 2:NO';
COMMENT ON COLUMN STG.T_CAMPANA.CODUSUARIOACT IS 'ID USUARIO ACTUALIZADOR';
COMMENT ON COLUMN STG.T_CAMPANA.FECREGISTRO   IS 'FECHA DE ACTUALIZACION DEL REGISTRO';
COMMENT ON COLUMN STG.T_CAMPANA.FE_ACTU_DIA   IS 'FECHA ACTUALIZACION DIA';

CREATE TABLE STG.T_CANAL(
	CODCANAL      INTEGER,
	DESCANAL_ABR  VARCHAR2(20),
	DESCANAL      VARCHAR2(50),
	DESCANALVENTA VARCHAR2(50),
	GRUPOCANAL    VARCHAR2(20),
	DESGRUPOCANAL VARCHAR2(50),
	TIPOCANAL     VARCHAR2(20),
	FLG_ACTIVO    INTEGER,
	FE_ACTU_DIA   DATE DEFAULT SYSDATE
) TABLESPACE STG_DATA_01;
COMMENT ON TABLE  STG.T_CANAL               IS 'TABLA MAESTRA DE CANALES';
COMMENT ON COLUMN STG.T_CANAL.CODCANAL      IS 'CODIGO DE CANAL DEFINIDO POR CRM';
COMMENT ON COLUMN STG.T_CANAL.DESCANAL_ABR  IS 'DESCRIPCION ABREVIADA DEL CANAL';
COMMENT ON COLUMN STG.T_CANAL.DESCANAL      IS 'DESCRIPCION DEL CANAL';
COMMENT ON COLUMN STG.T_CANAL.DESCANALVENTA IS 'DESCRIPCION DEL CANAL DE VENTA CONSOLIDADA POR NEGOCIOS';
COMMENT ON COLUMN STG.T_CANAL.GRUPOCANAL    IS 'AGRUPACION DE CANAL CLASIFICADA POR CRM';
COMMENT ON COLUMN STG.T_CANAL.DESGRUPOCANAL IS 'DESCRIPCION DEL GRUPO CANAL';
COMMENT ON COLUMN STG.T_CANAL.TIPOCANAL     IS 'TIPO DE CANAL CLASIFICA SI ES FACTIBLE TENER LA INICIATIVA DE CONTACTAR AL CLIENTE A TRAVES DEL CANAL: PROACTIVO, REACTIVO, MIXTO';
COMMENT ON COLUMN STG.T_CANAL.FLG_ACTIVO    IS 'INDICADOR QUE INDICA SI EL CANAL SE ENCUENTRA EN USO';
COMMENT ON COLUMN STG.T_CANAL.FE_ACTU_DIA   IS 'FECHA ACTUALIZACION DIA';



CREATE TABLE STG.T_RESULTADO_CONTACTO(
    IDCANAL           INTEGER,
    IDRESPUESTACANAL  INTEGER,
    DESRESPUESTACANAL VARCHAR2(250),
    CODRESPUESTA      INTEGER,
    DESRESPUESTA      VARCHAR2(50),
    CODRESULTADO      INTEGER,
    DESRESULTADO      VARCHAR2(50),
    FE_ACTU_DIA       DATE DEFAULT SYSDATE
) TABLESPACE STG_DATA_01;
COMMENT ON TABLE  STG.T_RESULTADO_CONTACTO                   IS 'TABLA CRM PARA INSCRIBIR POSIBLES RESPUESTAS DE LA RETROALIMENTACION POR CANAL TIPIFICADO CON UNA RESPUESTA Y RESULTADO DEL CONTACTO ESTANDARIZADOS';
COMMENT ON COLUMN STG.T_RESULTADO_CONTACTO.IDCANAL           IS 'CODIGO DE CANAL';
COMMENT ON COLUMN STG.T_RESULTADO_CONTACTO.IDRESPUESTACANAL  IS 'CODIGO DE RESPUESTA CANAL';
COMMENT ON COLUMN STG.T_RESULTADO_CONTACTO.DESRESPUESTACANAL IS 'RESPUESTA CANAL';
COMMENT ON COLUMN STG.T_RESULTADO_CONTACTO.CODRESPUESTA      IS 'CODIGO DE RESPUESTA';
COMMENT ON COLUMN STG.T_RESULTADO_CONTACTO.DESRESPUESTA      IS 'RESPUESTA HOMOLOGADA';
COMMENT ON COLUMN STG.T_RESULTADO_CONTACTO.CODRESULTADO      IS 'CODIGO DE RESULTADO';
COMMENT ON COLUMN STG.T_RESULTADO_CONTACTO.DESRESULTADO      IS 'RESULTADO HOMOLOGADO';
COMMENT ON COLUMN STG.T_RESULTADO_CONTACTO.FE_ACTU_DIA       IS 'FECHA ACTUALIZACION DIA';

CREATE TABLE STG.T_MKT_PRODUCTOS(
	COD_PRODUCTO  INTEGER,
	FAMILIA_IC    VARCHAR2(250),
	SUBFAMILIA_IC VARCHAR2(250),
	GRUPO_0       VARCHAR2(250),
	GRUPO_1       VARCHAR2(250),
	GRUPO_2       VARCHAR2(250),
	GRUPO_3       VARCHAR2(250),
	FE_ACTU_DIA   DATE DEFAULT SYSDATE
) TABLESPACE STG_DATA_01;
COMMENT ON TABLE STG.T_MKT_PRODUCTOS                IS 'TABLA DE CATALOGO DE PRODUCTOS POR CLASIFICACION DE GRUPOS';
COMMENT ON COLUMN STG.T_MKT_PRODUCTOS.COD_PRODUCTO  IS 'CODIGO DE PRODUCTO';
COMMENT ON COLUMN STG.T_MKT_PRODUCTOS.FAMILIA_IC    IS 'DESCRIPCION DE FAMILIA INTELIGENCIA COMERCIAL';
COMMENT ON COLUMN STG.T_MKT_PRODUCTOS.SUBFAMILIA_IC IS 'DESCRIPCION DE SUBFAMILIA INTELIGENCIA COMERCIAL';
COMMENT ON COLUMN STG.T_MKT_PRODUCTOS.GRUPO_0       IS 'CLASIFICACION DE AGRUPACION DE PRODUCTO RESUMEN';
COMMENT ON COLUMN STG.T_MKT_PRODUCTOS.GRUPO_1       IS 'CLASIFICACION DE AGRUPACION DE PRODUCTO INTERMEDIO 1';
COMMENT ON COLUMN STG.T_MKT_PRODUCTOS.GRUPO_2       IS 'CLASIFICACION DE AGRUPACION DE PRODUCTO INTERMEDIO 2';
COMMENT ON COLUMN STG.T_MKT_PRODUCTOS.GRUPO_3       IS 'CLASIFICACION DE AGRUPACION DE PRODUCTO DETALLE';
COMMENT ON COLUMN STG.T_MKT_PRODUCTOS.FE_ACTU_DIA   IS 'FECHA ACTUALIZACION DIA';

CREATE TABLE STG.T_REL_PROD_CAMPANA(
	ID_REL_PC     INTEGER,
	CODCAMPANA    INTEGER,
	CODPRODUCTO   INTEGER,
	FLGMARCA      INTEGER,
	FLGACTIVO     INTEGER,
	PERIODOINICIO INTEGER,
	FE_ACTU_DIA   DATE DEFAULT SYSDATE
) TABLESPACE STG_DATA_01;
COMMENT ON TABLE STG.T_REL_PROD_CAMPANA                IS 'TABLA QUE GUARDA LA RELACION DE PRODUCTO CON CAMPANA EN PERIODO DETERMINADO';
COMMENT ON COLUMN STG.T_REL_PROD_CAMPANA.ID_REL_PC     IS 'ID DEL REGISTRO QUE RELACIONA UN PRODUCTO DESEMBOLSADO CON UNA CAMPANA CORRESPONDIENTE';
COMMENT ON COLUMN STG.T_REL_PROD_CAMPANA.CODCAMPANA    IS 'CODIGO DE LA CAMPANA CRM';
COMMENT ON COLUMN STG.T_REL_PROD_CAMPANA.CODPRODUCTO   IS 'CODIGO DEL PRODUCTO SOLICITADO O DESEMBOLSADO';
COMMENT ON COLUMN STG.T_REL_PROD_CAMPANA.FLGMARCA      IS 'INDICADOR QUE INDICA SI EL PRODUCTO ES EL PRODUCTO MARCA O PRINCIPAL OFERTADO POR LA CAMPANA';
COMMENT ON COLUMN STG.T_REL_PROD_CAMPANA.FLGACTIVO     IS 'INDICADOR QUE INDICA SI LA RELACION PRODUCTO DESEMBOLSADO Y LA CAMPANA ESTA ACTIVA AUN.';
COMMENT ON COLUMN STG.T_REL_PROD_CAMPANA.PERIODOINICIO IS 'MES DE INICIO DE VIGENCIA DEL MATCH ENTRE EL PRODUCTO Y LA CAMPANA INDICADA';
COMMENT ON COLUMN STG.T_REL_PROD_CAMPANA.FE_ACTU_DIA   IS 'FECHA ACTUALIZACION DIA';

-- TABLAS ODS
CREATE TABLE ODS.MD_CAMPANA_VIGENCIA(
	CO_UNIC_CAMP VARCHAR2(20),
	NU_PERIODO   INTEGER,
	CO_CAMPANA   INTEGER,
	FE_INIC_VIGE DATE,
	FE_FIN_VIGE  DATE,
	FE_ACTU_DIA  DATE DEFAULT SYSDATE,
	CO_ACTU_USER VARCHAR2(25) DEFAULT USER,
	NU_CARGA     INTEGER DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHHMISS'),
	IN_ESTA_REG  INTEGER DEFAULT 1
) TABLESPACE ODS_DATA_01;
COMMENT ON TABLE  ODS.MD_CAMPANA_VIGENCIA              IS 'TABLA QUE ALMACENA LA VIGENCIA DE LAS CAMPANAS EN DETERMINADO PERIODO';
COMMENT ON COLUMN ODS.MD_CAMPANA_VIGENCIA.CO_UNIC_CAMP IS 'CODIGO UNICO DE LA CAMPANA';
COMMENT ON COLUMN ODS.MD_CAMPANA_VIGENCIA.NU_PERIODO   IS 'NUMERO DE PERIODO DEL MES DE VIGENCIA DE LA CAMAPANA';
COMMENT ON COLUMN ODS.MD_CAMPANA_VIGENCIA.CO_CAMPANA   IS 'CODIGO DE CAMPANA';
COMMENT ON COLUMN ODS.MD_CAMPANA_VIGENCIA.FE_INIC_VIGE IS 'FECHA INICIO DE VIGENCIA DE LA CAMPANA';
COMMENT ON COLUMN ODS.MD_CAMPANA_VIGENCIA.FE_FIN_VIGE  IS 'FECHA FIN DE VIGENCIA DE LA CAMPANA';
COMMENT ON COLUMN ODS.MD_CAMPANA_VIGENCIA.FE_ACTU_DIA  IS 'FECHA ACTUALIZACION DIA';
COMMENT ON COLUMN ODS.MD_CAMPANA_VIGENCIA.CO_ACTU_USER IS 'CODIGO DE USUARIO ACTUALIZACION';
COMMENT ON COLUMN ODS.MD_CAMPANA_VIGENCIA.NU_CARGA     IS 'NUMERO DE CARGA';
COMMENT ON COLUMN ODS.MD_CAMPANA_VIGENCIA.IN_ESTA_REG  IS 'ESTADO DE CARGA';


CREATE TABLE ODS.MD_CRM_CAMPANA(
	CO_CAMPANA   INTEGER,
	DE_ABRE_CAMP VARCHAR2(50),
	DE_CAMPANA   VARCHAR2(50),
	TI_CAMPANA   VARCHAR2(50),
	TI_OFERTA    VARCHAR2(50),
	DE_CATEGORIA VARCHAR2(50),
	IN_ACTIVO    INTEGER,
	FE_ACTU_DIA  DATE DEFAULT SYSDATE,
	CO_ACTU_USER VARCHAR2(25) DEFAULT USER,
	NU_CARGA     INTEGER DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHHMISS'),
	IN_ESTA_REG  INTEGER DEFAULT 1
) TABLESPACE ODS_DATA_01;
COMMENT ON TABLE ODS.MD_CRM_CAMPANA               IS 'TABLA MAESTRA DE CAMPANAS';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.CO_CAMPANA   IS 'CODIGO DE LA CAMPANA';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.DE_ABRE_CAMP IS 'DESCRIPCION ABREVIADA DE LA CAMPANA';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.DE_CAMPANA   IS 'DESCRIPCION DE LA CAMPANA';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.TI_CAMPANA   IS 'TIPO DE CAMPANA: TIPO DE EVALUACION PARA EL GRUPO COMERCIAL U OBJETIVO ESPECIFICO PARA EL RESTO';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.TI_OFERTA    IS 'TIPO DE PRODUCTO DE LA OFERTA: ACTIVO, PASIVO, SEGURO, TIPO DE CAMBIO';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.DE_CATEGORIA IS 'CATEGORIZACION DE LA CAMPANA POR EL OBEJTIVO DE LA MISMA: COMERCIAL O VENTA, TRANSACCIONAL O USO, RELACIONAL';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.IN_ACTIVO    IS 'INDICADOR QUE INDICA SI LA CAMPANA SIGUE ACTIVA O NO. 1:SI, 2:NO';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.FE_ACTU_DIA  IS 'FECHA ACTUALIZACION DIA';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.CO_ACTU_USER IS 'CODIGO DE USUARIO ACTUALIZACION';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.NU_CARGA     IS 'NUMERO DE CARGA';
COMMENT ON COLUMN ODS.MD_CRM_CAMPANA.IN_ESTA_REG  IS 'ESTADO DE CARGA';


CREATE TABLE ODS.MD_CANAL(
	CO_CANAL     INTEGER,
	DE_ABRE_CANA VARCHAR2(20),
	DE_CANAL     VARCHAR2(50),
	DE_CANA_VENT VARCHAR2(50),
	TI_GRUP_CANA VARCHAR2(20),
	DE_GRUP_CANA VARCHAR2(50),
	TI_CANAL     VARCHAR2(50),
	IN_ACTIVO    INTEGER,
	FE_ACTU_DIA  DATE DEFAULT SYSDATE,
	CO_ACTU_USER VARCHAR2(25) DEFAULT USER,
	NU_CARGA     INTEGER DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHHMISS'),
	IN_ESTA_REG  INTEGER DEFAULT 1
) TABLESPACE ODS_DATA_01;
COMMENT ON TABLE ODS.MD_CANAL IS 'TABLA MAESTRA DE CANALES';
COMMENT ON COLUMN ODS.MD_CANAL.CO_CANAL IS 'CODIGO DE CANAL DEFINIDO POR CRM';
COMMENT ON COLUMN ODS.MD_CANAL.DE_ABRE_CANA IS 'DESCRIPCION ABREVIADA DEL CANAL';
COMMENT ON COLUMN ODS.MD_CANAL.DE_CANAL  IS 'DESCRIPCION DEL CANAL';
COMMENT ON COLUMN ODS.MD_CANAL.DE_CANA_VENT  IS 'DESCRIPCION DEL CANAL DE VENTA CONSOLIDADA POR NEGOCIOS';
COMMENT ON COLUMN ODS.MD_CANAL.TI_GRUP_CANA  IS 'AGRUPACION DE CANAL CLASIFICADA POR CRM';
COMMENT ON COLUMN ODS.MD_CANAL.DE_GRUP_CANA  IS 'DESCRIPCION DEL GRUPO CANAL';
COMMENT ON COLUMN ODS.MD_CANAL.TI_CANAL  IS 'TIPO DE CANAL CLASIFICA SI ES FACTIBLE TENER LA INICIATIVA DE CONTACTAR AL CLIENTE A TRAVÉS DEL CANAL: PROACTIVO, REACTIVO, MIXTO';
COMMENT ON COLUMN ODS.MD_CANAL.IN_ACTIVO  IS 'INDICADOR QUE INDICA SI EL CANAL SE ENCUENTRA EN USO';
COMMENT ON COLUMN ODS.MD_CANAL.FE_ACTU_DIA  IS 'FECHA ACTUALIZACION DIA';
COMMENT ON COLUMN ODS.MD_CANAL.CO_ACTU_USER  IS 'CODIGO DE USUARIO ACTUALIZACION';
COMMENT ON COLUMN ODS.MD_CANAL.NU_CARGA  IS 'NUMERO DE CARGA';
COMMENT ON COLUMN ODS.MD_CANAL.IN_ESTA_REG  IS 'ESTADO DE CARGA';


CREATE TABLE ODS.MD_RESULTADO_CONTACTO(
	CO_CANAL     INTEGER,
	CO_RESP_CANA INTEGER,
	DE_RESP_CANA VARCHAR2(250),
	CO_RESPUESTA INTEGER,
	DE_RESPUESTA VARCHAR2(50),
	CO_RESULTADO INTEGER,
	DE_RESULTADO VARCHAR2(50),
	FE_ACTU_DIA  DATE DEFAULT SYSDATE,
	CO_ACTU_USER VARCHAR2(25) DEFAULT USER,
	NU_CARGA     INTEGER DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHHMISS'),
	IN_ESTA_REG  INTEGER DEFAULT 1
) TABLESPACE ODS_DATA_01;
COMMENT ON TABLE  ODS.MD_RESULTADO_CONTACTO               IS 'TABLA CRM PARA INSCRIBIR POSIBLES RESPUESTAS DE LA RETROALIMENTACION POR CANAL TIPIFICADO CON UNA RESPUESTA Y RESULTADO DEL CONTACTO ESTANDARIZADOS';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.CO_CANAL      IS 'CODIGO DEL CANAL DE CONTACTO, DEFINIDO POR CRM. TIENE UNA MAESTRA DESCRIPTIVA';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.CO_RESP_CANA  IS 'IDENTIFICADOR DE LA RESPUESTA DE CONTACTO PROPIA DEL CANAL ';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.DE_RESP_CANA  IS 'DESCRIPCION DE LA RESPUESTA DE CONTACTO PROPIA DEL CANAL ';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.CO_RESPUESTA  IS 'CODIGO DE LA RESPUESTA DE CONTACTO, ESTANDARIZADA POR CRM';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.DE_RESPUESTA  IS 'DESCRIPCION DE LA RESPUESTA DE CONTACTO, ESTANDARIZADA POR CRM';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.CO_RESULTADO  IS 'CODIGO DEL RESULTADO DEL CONTACTO, ESTANDARIZADA POR CRM';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.DE_RESULTADO  IS 'DESCRIPCION DEL RESULTADO DEL CONTACTO, ESTANDARIZADA POR CRM';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.FE_ACTU_DIA   IS 'FECHA ACTUALIZACION DIA';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.CO_ACTU_USER  IS 'CODIGO DE USUARIO ACTUALIZACION';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.NU_CARGA      IS 'NUMERO DE CARGA';
COMMENT ON COLUMN ODS.MD_RESULTADO_CONTACTO.IN_ESTA_REG   IS 'ESTADO DE CARGA';


CREATE TABLE ODS.MD_GRUPO_PRODUCTO(
	CO_PRODUCTO  INTEGER,
	DE_FAMI_IC   VARCHAR2(250),
	DE_SUBF_IC   VARCHAR2(250),
	TI_GRUP_0    VARCHAR2(250),
	TI_GRUP_1    VARCHAR2(250),
	TI_GRUP_2    VARCHAR2(250),
	TI_GRUP_3    VARCHAR2(250),
	FE_ACTU_DIA  DATE DEFAULT SYSDATE,
	CO_ACTU_USER VARCHAR2(25) DEFAULT USER,
	NU_CARGA     INTEGER DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHHMISS'),
	IN_ESTA_REG  INTEGER DEFAULT 1
) TABLESPACE ODS_DATA_01;
COMMENT ON TABLE  ODS.MD_GRUPO_PRODUCTO              IS 'TABLA DE CATALOGO DE PRODUCTOS POR CLASIFICACION DE GRUPOS';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.CO_PRODUCTO  IS 'CODIGO DE PRODUCTO';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.DE_FAMI_IC   IS 'DESCRIPCION DE FAMILIA INTELIGENCIA COMERCIAL';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.DE_SUBF_IC   IS 'DESCRIPCION DE SUBFAMILIA INTELIGENCIA COMERCIAL';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.TI_GRUP_0    IS 'CLASIFICACION DE AGRUPACION DE PRODUCTO RESUMEN';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.TI_GRUP_1    IS 'CLASIFICACION DE AGRUPACION DE PRODUCTO INTERMEDIO 1';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.TI_GRUP_2    IS 'CLASIFICACION DE AGRUPACION DE PRODUCTO INTERMEDIO 2';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.TI_GRUP_3    IS 'CLASIFICACION DE AGRUPACION DE PRODUCTO DETALLE';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.FE_ACTU_DIA  IS 'FECHA ACTUALIZACION DIA';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.CO_ACTU_USER IS 'CODIGO DE USUARIO ACTUALIZACION';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.NU_CARGA     IS 'NUMERO DE CARGA';
COMMENT ON COLUMN ODS.MD_GRUPO_PRODUCTO.IN_ESTA_REG  IS 'ESTADO DE CARGA';


CREATE TABLE ODS.MD_PRODUCTO_CAMPANA(
	CO_PROD_CAMP INTEGER,
	CO_CAMPANA   INTEGER,
	CO_PRODUCTO  INTEGER,
	IN_MARCA     INTEGER,
	IN_ACTIVO    INTEGER,
	NU_PERI_INIC INTEGER,
	FE_ACTU_DIA  DATE DEFAULT SYSDATE,
	CO_ACTU_USER VARCHAR2(25) DEFAULT USER,
	NU_CARGA     INTEGER DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHHMISS'),
	IN_ESTA_REG  INTEGER DEFAULT 1
) TABLESPACE ODS_DATA_01;
COMMENT ON TABLE ODS.MD_PRODUCTO_CAMPANA                    IS 'TABLA MAESTRA DE LA RELACION DE PRODUCTO CON CAMPANA EN PERIODO DETERMINADO';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.CO_PROD_CAMP      IS 'CODIGO QUE RELACIONA UN PRODUCTO DESEMBOLSADO CON UNA CAMPANA';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.CO_CAMPANA        IS 'CODIGO DE CAMPANA';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.CO_PRODUCTO       IS 'CODIGO DEL PRODUCTO SOLICITADO O DESEMBOLSADO';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.IN_MARCA          IS 'INDICADOR QUE INDICA SI EL PRODUCTO ES EL PRODUCTO MARCA O PRINCIPAL OFERTADO POR LA CAMPANA';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.IN_ACTIVO         IS 'INDICADOR QUE INDICA SI LA RELACIÓN PRODUCTO DESEMBOLSADO Y LA CAMPANA ESTÁ ACTIVA AUN.';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.NU_PERI_INIC      IS 'NUMERO DE PERIODO DE INICIO DE VIGENCIA DE LA RELACIÓN ENTRE PRODUCTO Y CAMPANA';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.FE_ACTU_DIA       IS 'FECHA ACTUALIZACION DIA';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.CO_ACTU_USER      IS 'CODIGO DE USUARIO ACTUALIZACION';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.NU_CARGA          IS 'NUMERO DE CARGA';
COMMENT ON COLUMN ODS.MD_PRODUCTO_CAMPANA.IN_ESTA_REG       IS 'ESTADO DE CARGA';

