-- Crear tabla BDS.F_RIE_ADMISION_CREDITOS
CREATE TABLE BDS.F_RIE_ADMISION_CREDITOS ( 
NU_SOLICITUD                       NUMBER(22)   DEFAULT (0), 
NU_PRESTAMO                        NUMBER(22)   DEFAULT (0), 
NU_PERI_MES                        NUMBER(6)    DEFAULT (0),
FE_INGR_SOLI                       DATE, 
FE_EVAL_SOLI                       DATE, 
FE_APRO_SOLI                       DATE, 
FE_DESEMBOLSO                      DATE, 
FE_APER_CUEN                       DATE, 
IN_EVALUACION                      NUMBER(1)    DEFAULT (0), 
IN_APROBACION                      NUMBER(1)    DEFAULT (0), 
IN_DESEMBOLSO                      NUMBER(1)    DEFAULT (0), 
IN_REFINANCIADO                    NUMBER(1)    DEFAULT (0), 
IN_GARANTIA                        NUMBER(1)    DEFAULT (0), 
IN_PRES_PREP                       NUMBER(1)    DEFAULT (0), 
IN_CODEUDORES                      NUMBER(1)    DEFAULT (0), 
CO_CLIENTE                         NUMBER(15)   DEFAULT (0), 
CO_ESTA_SOLI                       NUMBER(3)    DEFAULT (0), 
CO_MONEDA                          NUMBER(4)    DEFAULT (0), 
CO_TIPO_SOLI                       VARCHAR2(5)  DEFAULT ('.'), 
CO_TIPO_PRES                       VARCHAR2(20) DEFAULT ('.'),
CO_TIPO_GRAC                       VARCHAR2(1)  DEFAULT ('.'), 
CO_TIPO_CRED                       VARCHAR2(5)  DEFAULT ('.'), 
CO_PRODUCTO                        NUMBER(5)    DEFAULT (0), 
IN_PRES_MIGR                       NUMBER(1)    DEFAULT 0, 
NU_LINE_CRED                       NUMBER(15)   DEFAULT (0), 
NU_SOLI_LINE_CRED                  NUMBER(15)   DEFAULT (0), 
CO_FORM_DESE                       VARCHAR2(2)  DEFAULT ('.'), 
CO_AGENCIA                         NUMBER(5)    DEFAULT (0), 
CO_ACTI_INTE                       NUMBER(5)    DEFAULT (0), 
CO_GRUP_EXCE                       NUMBER(5)    DEFAULT (0), 
NU_PERI_GRAC                       NUMBER(4)    DEFAULT (0), 
VL_TASA_DESE                       NUMBER(11,7) DEFAULT (0), 
MO_SOLICITADO                      NUMBER(15,2) DEFAULT (0), 
MO_APROBADO                        NUMBER(15,2) DEFAULT (0), 
MO_DESEMBOLSADO                    NUMBER(15,2) DEFAULT (0), 
MO_DEUD_SOLI                       NUMBER(15,2) DEFAULT (0), 
MO_CUOTA                           NUMBER(15,2) DEFAULT (0), 
MO_SALD_CRED_CANC                  NUMBER(15,2) DEFAULT (0),
NU_PLAZ_SOLI                       NUMBER(5)    DEFAULT (0), 
NU_PLAZ_APRO                       NUMBER(5)    DEFAULT (0), 
NU_CUOTAS                          NUMBER(5)    DEFAULT (0), 
NU_DISP_LINE_CRED                  NUMBER(5)    DEFAULT (0), 
NU_CANT_GARA                       NUMBER(5)    DEFAULT (0), 
NU_CANT_CODE                       NUMBER(5)    DEFAULT (0), 
NU_CANT_ENTI_ACRE                  NUMBER(5)    DEFAULT (0), 
NU_DIAS_MORA_RCC                   NUMBER(5)    DEFAULT (0), 
MO_DEUD_SIST_FINA                  NUMBER(15,2) DEFAULT (0), 
NU_DIAS_PROC_EVAL                  NUMBER(5)    DEFAULT (0), 
NU_DIAS_PROC_APRO                  NUMBER(5)    DEFAULT (0), 
NU_DIAS_PROC_DESE                  NUMBER(5)    DEFAULT (0), 
CO_CONV_SOLI                       NUMBER(4)    DEFAULT (0),
FE_ACTU_DIA                        DATE         DEFAULT SYSDATE
) 
PARTITION BY RANGE (NU_PERI_MES)
(
 PARTITION P_RIE_ADMISION_CREDITOS_201501 VALUES LESS THAN (201502)   TABLESPACE BDS_DATA_01,
 PARTITION P_RIE_ADMISION_CREDITOS_MAX    VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);

COMMENT ON TABLE BDS.F_RIE_ADMISION_CREDITOS IS 'TABLA DE HECHOS DE ADMISION DE CREDITOS.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_SOLICITUD      IS 'NUMERO DE SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_PRESTAMO       IS 'NUMERO DE PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_PERI_MES       IS 'NUMERO DE MES (FORMATO YYYYMM) EN EL QUE SE REGISTRO LA SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.FE_INGR_SOLI      IS 'FECHA DE INGRESO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.FE_EVAL_SOLI      IS 'FECHA FIN DE EVALUACION DE LA SOLICITUD - PARA LOS CASOS DE SOLICITUDES DE DISPOSICION DE DINERO DE UNA LINEA DE CREDITO APROBADA, SE PONE LA FECHA DE EVALUACION DE LA SOLICITUD DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.FE_APRO_SOLI      IS 'FECHA FIN DE APROBACION DE LA SOLICITUD - PARA LOS CASOS DE SOLICITUDES DE DISPOSICION DE DINERO DE UNA LINEA DE CREDITO APROBADA, SE PONE LA FECHA DE APROBACION DE LA SOLICITUD DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.FE_DESEMBOLSO     IS 'FECHA DE DESEMBOLSO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.FE_APER_CUEN      IS 'FECHA DE APERTURA DE CUENTA.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.IN_EVALUACION     IS 'FLAG DE EVALUADO --> 1=EVALUADO, 0=SIN EVALUAR.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.IN_APROBACION     IS 'FLAG DE APROBADO --> 1=APROBADO, 0=SIN APROBAR.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.IN_DESEMBOLSO     IS 'FLAG DE DESEMBOLSO --> 1=CON DESEMBOLSO, 0=SIN DESEMBOLSO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.IN_REFINANCIADO   IS 'FLAG DE REFINANCIADO --> 1=REFINANCIADO, 0=SIN REFINANCIAR.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.IN_GARANTIA       IS 'FLAG DE GARANTIA --> 1=CON GARANTIA, 0=SIN GARANTIA.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.IN_PRES_PREP      IS 'FLAG DE PRESTAMO PRE-PAGADO --> 1=CON PRE-PAGO, 0=SIN PRE-PAGO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.IN_CODEUDORES     IS 'FLAG DE CO-DEUDORES --> 1=CON CO-DEUDORES, 0=SIN CO-DEUDORES.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_CLIENTE        IS 'CODIGO DEL CLIENTE.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_ESTA_SOLI      IS 'CODIGO DEL ESTADO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_MONEDA         IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_TIPO_SOLI      IS 'CODIGO DEL TIPO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_TIPO_PRES      IS 'CODIGO DEL TIPO DE PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_TIPO_GRAC      IS 'CODIGO DEL TIPO DE GRACIA.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_TIPO_CRED      IS 'CODIGO DEL TIPO DE CREDITO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_PRODUCTO       IS 'CODIGO DEL PRODUCTO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.IN_PRES_MIGR      IS 'FLAG PRESTAMO MIGRADO --> 1=MIGRADO, 0=NO MIGRADO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_LINE_CRED      IS 'NUMERO DE LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_SOLI_LINE_CRED IS 'NUMERO DE SOLICITUD DE LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_FORM_DESE      IS 'CODIGO FORMA DE DESEMBOLSO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_AGENCIA        IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_ACTI_INTE      IS 'CODIGO DE ACTIVIDAD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_ESTA_SOLI      IS 'CODIGO DEL ESTADO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_GRUP_EXCE      IS 'TIPO DE EXCEPCION.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_PERI_GRAC      IS 'PERIODO DE GRACIA.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.VL_TASA_DESE      IS 'TASA AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.MO_SOLICITADO     IS 'MONTO SOLICITADO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.MO_APROBADO       IS 'MONTO APROBADO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.MO_DESEMBOLSADO   IS 'MONTO DESEMBOLSADO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.MO_DEUD_SOLI      IS 'MONTO DE DEUDA DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.MO_CUOTA          IS 'MONTO DE LA CUOTA.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.MO_SALD_CRED_CANC IS 'MONTO DEL SALDO DEL CREDITO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_PLAZ_SOLI      IS 'NUMERO DE PLAZO SOLICITADO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_PLAZ_APRO      IS 'NUMERO DE PLAZO APROBADO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_CUOTAS         IS 'NUMERO DE CUOTAS.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_DISP_LINE_CRED IS 'NUMERO DE LA DISPOSICON DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_CANT_GARA      IS 'CANTIDAD DE GARANTIAS.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_CANT_CODE      IS 'CANTIDAD DE CODEUDORES DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_CANT_ENTI_ACRE IS 'ENTIDADES ACREEDORAS SIN MBCO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_DIAS_MORA_RCC  IS 'DIAS DE MORA.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.MO_DEUD_SIST_FINA IS 'MONTO DE SALDO EN EL SISTEMA FINANCIERO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_DIAS_PROC_EVAL IS 'NUMERO DE DIAS DEL PROCESO DE EVALUACION.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_DIAS_PROC_APRO IS 'NUMERO DE DIAS DEL PROCESO DE APROBACION.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.NU_DIAS_PROC_DESE IS 'NUMERO DE DIAS DEL PROCESO DE DESEMBOLSO.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.CO_CONV_SOLI      IS 'CODIGO DEL CONVENIO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_ADMISION_CREDITOS.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';


-- Crear tabla BDS.F_RIE_COSECHA_M
CREATE TABLE BDS.F_RIE_COSECHA_M
(  
  NU_PERI_MES                  NUMBER(6)    DEFAULT (0),
  NU_PERI_DESE                 NUMBER(6)    DEFAULT (0),
  NU_PRESTAMO                  NUMBER(15)   DEFAULT (0),
  NU_COSECHA                   NUMBER(3)    DEFAULT (0),
  NU_PRES_FINA                 NUMBER(15)   DEFAULT (0),
  CO_ESTA_PRES                 VARCHAR2(1)  DEFAULT ('.'),
  CO_REFINANCIACION            VARCHAR2(5)  DEFAULT ('.'),
  MO_DESEMBOLSADO              NUMBER(15,2) DEFAULT (0),
  MO_DETERIORADO               NUMBER(15,2) DEFAULT (0),
  MO_DETE_FENO_NINO            NUMBER(15,2) DEFAULT (0),
  MO_DETE_15                   NUMBER(15,2) DEFAULT (0),
  MO_DETE_30                   NUMBER(15,2) DEFAULT (0),
  NU_DIAS_MORA                 NUMBER(7)    DEFAULT (0),
  FE_ACTU_MES                  DATE         DEFAULT SYSDATE
)
PARTITION BY RANGE (NU_PERI_MES)
(
 PARTITION P_RIE_COSECHA_M_201401 VALUES LESS THAN (201402)   TABLESPACE BDS_DATA_01,
 PARTITION P_RIE_COSECHA_M_MAX    VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);

COMMENT ON TABLE BDS.F_RIE_COSECHA_M IS 'TABLA DE HECHOS DE COSECHA MENSUAL.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.NU_PERI_MES       IS 'PERIODO DE PROCESO EN FORMATO YYYYMM.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.NU_PERI_DESE      IS 'PERIODO DE DESEMBOLSO EN FORMATO YYYYMM.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.NU_PRESTAMO       IS 'NUMERO DE PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.NU_COSECHA        IS 'NUMERO DE COSECHA.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.NU_PRES_FINA      IS 'NUMERO DE PRESTAMO FINAL.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.CO_ESTA_PRES      IS 'CODIGO DEL ESTADO DEL PRESTAMO .';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.CO_REFINANCIACION IS 'CODIGO DE REFINANCIADO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.MO_DESEMBOLSADO   IS 'MONTO DESEMBOLSADO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.MO_DETERIORADO    IS 'MONTO DETERIORADO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.MO_DETE_FENO_NINO IS 'MONTO DETERIORADO POR FENOMENO DEL NIÑO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.MO_DETE_15        IS 'MONTO DETERIORADO 15.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.MO_DETE_30        IS 'MONTO DETERIORADO 30.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.NU_DIAS_MORA      IS 'NUMERO DE DIAS DE MORA.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_M.FE_ACTU_MES       IS 'FECHA DE ACTUALIZACION MENSUAL DE LA TABLA.';

-- Crear tabla BDS.F_RIE_COSECHA_D
CREATE TABLE BDS.F_RIE_COSECHA_D
(  
  FE_PROCESO                   DATE,
  NU_PERI_DESE                 NUMBER(6)    DEFAULT (0),
  NU_PRESTAMO                  NUMBER(15)   DEFAULT (0),
  NU_COSECHA                   NUMBER(3)    DEFAULT (0),
  NU_PRES_FINA                 NUMBER(15)   DEFAULT (0),
  CO_ESTA_PRES                 VARCHAR2(1)  DEFAULT ('.'),
  CO_REFINANCIACION            VARCHAR2(5)  DEFAULT ('.'),
  MO_DESEMBOLSADO              NUMBER(15,2) DEFAULT (0),
  MO_DETERIORADO               NUMBER(15,2) DEFAULT (0),
  MO_DETE_FENO_NINO            NUMBER(15,2) DEFAULT (0),
  MO_DETE_15                   NUMBER(15,2) DEFAULT (0),
  MO_DETE_30                   NUMBER(15,2) DEFAULT (0),
  NU_DIAS_MORA                 NUMBER(7)    DEFAULT (0),
  FE_ACTU_DIA                  DATE         DEFAULT SYSDATE
)
PARTITION BY RANGE (FE_PROCESO)
(
 PARTITION P_RIE_COSECHA_D_20140101 VALUES LESS THAN (TO_DATE(' 2014-01-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) TABLESPACE BDS_DATA_01,
 PARTITION P_RIE_COSECHA_D_MAX      VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);

COMMENT ON TABLE BDS.F_RIE_COSECHA_D IS 'TABLA DE HECHOS DE COSECHA DIARIO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.FE_PROCESO        IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.NU_PERI_DESE      IS 'PERIODO DE DESEMBOLSO EN FORMATO YYYYMM.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.NU_PRESTAMO       IS 'NUMERO DE PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.NU_COSECHA        IS 'NUMERO DE COSECHA.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.NU_PRES_FINA      IS 'NUMERO DE PRESTAMO FINAL.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.CO_ESTA_PRES      IS 'CODIGO DEL ESTADO DEL PRESTAMO .';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.CO_REFINANCIACION IS 'CODIGO DE REFINANCIACION.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.MO_DESEMBOLSADO   IS 'MONTO DESEMBOLSADO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.MO_DETERIORADO    IS 'MONTO DETERIORADO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.MO_DETE_FENO_NINO IS 'MONTO DETERIORADO POR FENOMENO DEL NIÑO.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.MO_DETE_15        IS 'MONTO DETERIORADO 15.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.MO_DETE_30        IS 'MONTO DETERIORADO 30.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.NU_DIAS_MORA      IS 'NUMERO DE DIAS DE MORA.';
COMMENT ON COLUMN BDS.F_RIE_COSECHA_D.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';


-- Crear tabla BDS.F_RIE_REF_EXTREMO
CREATE TABLE BDS.F_RIE_REF_EXTREMO
(  
  NU_PRES_ORIG                 NUMBER(15) DEFAULT (0),
  NU_PERI_MES_ORIG             NUMBER(6)  DEFAULT (0),  
  CO_PROD_ORIG                 NUMBER(22) DEFAULT (0),
  NU_PRES_FINA                 NUMBER(15) DEFAULT (0),
  NU_PERI_MES_FINA             NUMBER(6)  DEFAULT (0),
  VL_PORC_PART                 NUMBER     DEFAULT (0),
  FE_ACTU_DIA                  DATE       DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;

COMMENT ON TABLE BDS.F_RIE_REF_EXTREMO IS 'TABLA DE HECHOS QUE RELACIONA UN PRESTAMO REFINANCIADO CON EL ULTIMO PRESTAMO DE REFINANCIACION.';
COMMENT ON COLUMN BDS.F_RIE_REF_EXTREMO.NU_PRES_ORIG     IS 'NUMERO DEL PRESTAMO ORIGEN.';
COMMENT ON COLUMN BDS.F_RIE_REF_EXTREMO.NU_PERI_MES_ORIG IS 'MES EN FORMATO YYYYMM EN EL QUE SE OTORGO EL PRESTAMO ORIGEN.';
COMMENT ON COLUMN BDS.F_RIE_REF_EXTREMO.CO_PROD_ORIG     IS 'CODIGO DEL PRODUCTO DEL PRESTAMO ORIGEN.';
COMMENT ON COLUMN BDS.F_RIE_REF_EXTREMO.NU_PRES_FINA     IS 'NUMERO DEL PRESTAMO DE REFINANCIACION FINAL.';
COMMENT ON COLUMN BDS.F_RIE_REF_EXTREMO.NU_PERI_MES_FINA IS 'MES EN FORMATO YYYYMM EN EL QUE SE OTORGO EL PRESTAMO DE REFINANCIACION FINAL.';
COMMENT ON COLUMN BDS.F_RIE_REF_EXTREMO.VL_PORC_PART     IS 'PORCENTAJE DE PARTICIPACION.';
COMMENT ON COLUMN BDS.F_RIE_REF_EXTREMO.FE_ACTU_DIA      IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';


-- Crear tabla BDS.T_TABLAS_TRUNCO_RETOMA
CREATE TABLE BDS.T_TABLAS_TRUNCO_RETOMA
(
  ID_ETAPA               NUMBER(5)    DEFAULT (0),
  ID_FASE                NUMBER(5)    DEFAULT (0),
  ID_SUBFASE             NUMBER(5)    DEFAULT (0),
  DE_NOMBREFISICO        VARCHAR2(30) DEFAULT ('.'),
  ESQUEMA_TABLA          VARCHAR2(3)  DEFAULT ('.')
) TABLESPACE BDS_DATA_01 ;

COMMENT ON TABLE  BDS.T_TABLAS_TRUNCO_RETOMA IS 'MAESTRO DE TABLAS A TRUNCAR EN BDS.';
COMMENT ON COLUMN BDS.T_TABLAS_TRUNCO_RETOMA.ID_ETAPA IS 'CODIGO DE ETAPA ETL.';
COMMENT ON COLUMN BDS.T_TABLAS_TRUNCO_RETOMA.ID_FASE  IS 'CODIGO DE SUBFASE ETL POR FASE,ETAPA Y FECHA PROCESO.';
COMMENT ON COLUMN BDS.T_TABLAS_TRUNCO_RETOMA.ID_SUBFASE IS 'CODIGO DE SUBFASE ETL POR ETAPA, FASE Y FECHA PROCESO.';
COMMENT ON COLUMN BDS.T_TABLAS_TRUNCO_RETOMA.DE_NOMBREFISICO IS 'NOMBRE FISICO DE LA TABLA.';
COMMENT ON COLUMN BDS.T_TABLAS_TRUNCO_RETOMA.ESQUEMA_TABLA IS 'ESQUEMA DONDE SE UBICA LA TABLA.';


-- Crear tabla BDS.T_RIE_ADMISION_CREDITOS
CREATE TABLE BDS.T_RIE_ADMISION_CREDITOS ( 
NU_SOLICITUD                       NUMBER(22)   DEFAULT 0, 
NU_PRESTAMO                        NUMBER(22)   DEFAULT 0, 
NU_PERI_MES                        NUMBER(6)    DEFAULT 0,
FE_INGR_SOLI                       DATE, 
FE_EVAL_SOLI                       DATE, 
FE_APRO_SOLI                       DATE, 
FE_DESEMBOLSO                      DATE, 
FE_APER_CUEN                       DATE, 
IN_EVALUACION                      NUMBER(1)    DEFAULT 0, 
IN_APROBACION                      NUMBER(1)    DEFAULT 0, 
IN_DESEMBOLSO                      NUMBER(1)    DEFAULT 0, 
IN_REFINANCIADO                    NUMBER(1)    DEFAULT 0, 
IN_GARANTIA                        NUMBER(1)    DEFAULT 0, 
IN_PRES_PREP                       NUMBER(1)    DEFAULT 0, 
IN_CODEUDORES                      NUMBER(1)    DEFAULT 0, 
CO_CLIENTE                         NUMBER(15)   DEFAULT 0, 
CO_ESTA_SOLI                       NUMBER(3)    DEFAULT 0, 
CO_MONEDA                          NUMBER(4)    DEFAULT 0, 
CO_TIPO_SOLI                       VARCHAR2(5)  DEFAULT '.', 
CO_TIPO_PRES                       VARCHAR2(20) DEFAULT '.',
CO_TIPO_GRAC                       VARCHAR2(1)  DEFAULT '.', 
CO_TIPO_CRED                       VARCHAR2(5)  DEFAULT '.', 
CO_PRODUCTO                        NUMBER(5)    DEFAULT 0, 
IN_PRES_MIGR                       NUMBER(1)    DEFAULT 0, 
NU_LINE_CRED                       NUMBER(15)   DEFAULT 0, 
NU_SOLI_LINE_CRED                  NUMBER(15)   DEFAULT 0, 
CO_FORM_DESE                       VARCHAR2(2)  DEFAULT '.', 
CO_AGENCIA                         NUMBER(5)    DEFAULT 0, 
CO_ACTI_INTE                       NUMBER(5)    DEFAULT 0, 
CO_GRUP_EXCE                       NUMBER(5)    DEFAULT 0, 
NU_PERI_GRAC                       NUMBER(4)    DEFAULT 0, 
VL_TASA_DESE                       NUMBER(11,7) DEFAULT 0, 
MO_SOLICITADO                      NUMBER(15,2) DEFAULT 0, 
MO_APROBADO                        NUMBER(15,2) DEFAULT 0, 
MO_DESEMBOLSADO                    NUMBER(15,2) DEFAULT 0, 
MO_DEUD_SOLI                       NUMBER(15,2) DEFAULT 0, 
MO_CUOTA                           NUMBER(15,2) DEFAULT 0, 
MO_SALD_CRED_CANC                  NUMBER(15,2) DEFAULT 0,
NU_PLAZ_SOLI                       NUMBER(5)    DEFAULT 0, 
NU_PLAZ_APRO                       NUMBER(5)    DEFAULT 0, 
NU_CUOTAS                          NUMBER(5)    DEFAULT 0, 
NU_DISP_LINE_CRED                  NUMBER(5)    DEFAULT 0, 
NU_CANT_GARA                       NUMBER(5)    DEFAULT 0, 
NU_CANT_CODE                       NUMBER(5)    DEFAULT 0, 
NU_CANT_ENTI_ACRE                  NUMBER(5)    DEFAULT 0, 
NU_DIAS_MORA_RCC                   NUMBER(5)    DEFAULT 0, 
MO_DEUD_SIST_FINA                  NUMBER(15,2) DEFAULT 0, 
NU_DIAS_PROC_EVAL                  NUMBER(5)    DEFAULT 0, 
NU_DIAS_PROC_APRO                  NUMBER(5)    DEFAULT 0, 
NU_DIAS_PROC_DESE                  NUMBER(5)    DEFAULT 0, 
CO_CONV_SOLI                       NUMBER(4)    DEFAULT 0,
FE_ACTU_DIA                        DATE         DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;

COMMENT ON TABLE BDS.T_RIE_ADMISION_CREDITOS IS 'TABLA TEMPORAL PARA CARGAR LA TABLA DE HECHOS DE ADMISION DE CREDITOS.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_SOLICITUD      IS 'NUMERO DE SOLICITUD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_PRESTAMO       IS 'NUMERO DE PRESTAMO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_PERI_MES       IS 'NUMERO DE MES (FORMATO YYYYMM) EN EL QUE SE REGISTRO LA SOLICITUD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.FE_INGR_SOLI      IS 'FECHA DE INGRESO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.FE_EVAL_SOLI      IS 'FECHA FIN DE EVALUACION DE LA SOLICITUD - PARA LOS CASOS DE SOLICITUDES DE DISPOSICION DE DINERO DE UNA LINEA DE CREDITO APROBADA, SE PONE LA FECHA DE EVALUACION DE LA SOLICITUD DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.FE_APRO_SOLI      IS 'FECHA FIN DE APROBACION DE LA SOLICITUD - PARA LOS CASOS DE SOLICITUDES DE DISPOSICION DE DINERO DE UNA LINEA DE CREDITO APROBADA, SE PONE LA FECHA DE APROBACION DE LA SOLICITUD DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.FE_DESEMBOLSO     IS 'FECHA DE DESEMBOLSO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.FE_APER_CUEN      IS 'FECHA DE APERTURA DE CUENTA.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.IN_EVALUACION     IS 'FLAG DE EVALUADO --> 1=EVALUADO, 0=SIN EVALUAR.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.IN_APROBACION     IS 'FLAG DE APROBADO --> 1=APROBADO, 0=SIN APROBAR.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.IN_DESEMBOLSO     IS 'FLAG DE DESEMBOLSO --> 1=CON DESEMBOLSO, 0=SIN DESEMBOLSO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.IN_REFINANCIADO   IS 'FLAG DE REFINANCIADO --> 1=REFINANCIADO, 0=SIN REFINANCIAR.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.IN_GARANTIA       IS 'FLAG DE GARANTIA --> 1=CON GARANTIA, 0=SIN GARANTIA.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.IN_PRES_PREP      IS 'FLAG DE PRESTAMO PRE-PAGADO --> 1=CON PRE-PAGO, 0=SIN PRE-PAGO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.IN_CODEUDORES     IS 'FLAG DE CO-DEUDORES --> 1=CON CO-DEUDORES, 0=SIN CO-DEUDORES.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_CLIENTE        IS 'CODIGO DEL CLIENTE.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_ESTA_SOLI      IS 'CODIGO DEL ESTADO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_MONEDA         IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_TIPO_SOLI      IS 'CODIGO DEL TIPO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_TIPO_PRES      IS 'CODIGO DEL TIPO DE PRESTAMO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_TIPO_GRAC      IS 'CODIGO DEL TIPO DE GRACIA.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_TIPO_CRED      IS 'CODIGO DEL TIPO DE CREDITO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_PRODUCTO       IS 'CODIGO DEL PRODUCTO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.IN_PRES_MIGR      IS 'FLAG PRESTAMO MIGRADO --> 1=MIGRADO, 0=NO MIGRADO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_LINE_CRED      IS 'NUMERO DE LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_SOLI_LINE_CRED IS 'NUMERO DE SOLICITUD DE LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_FORM_DESE      IS 'CODIGO FORMA DE DESEMBOLSO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_AGENCIA        IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_ACTI_INTE      IS 'CODIGO DE ACTIVIDAD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_ESTA_SOLI      IS 'CODIGO DEL ESTADO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_GRUP_EXCE      IS 'TIPO DE EXCEPCION.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_PERI_GRAC      IS 'PERIODO DE GRACIA.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.VL_TASA_DESE      IS 'TASA AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.MO_SOLICITADO     IS 'MONTO SOLICITADO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.MO_APROBADO       IS 'MONTO APROBADO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.MO_DESEMBOLSADO   IS 'MONTO DESEMBOLSADO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.MO_DEUD_SOLI      IS 'MONTO DE DEUDA DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.MO_CUOTA          IS 'MONTO DE LA CUOTA.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.MO_SALD_CRED_CANC IS 'MONTO DEL SALDO DEL CREDITO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_PLAZ_SOLI      IS 'NUMERO DE PLAZO SOLICITADO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_PLAZ_APRO      IS 'NUMERO DE PLAZO APROBADO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_CUOTAS         IS 'NUMERO DE CUOTAS.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_DISP_LINE_CRED IS 'NUMERO DE LA DISPOSICON DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_CANT_GARA      IS 'CANTIDAD DE GARANTIAS.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_CANT_CODE      IS 'CANTIDAD DE CODEUDORES DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_CANT_ENTI_ACRE IS 'ENTIDADES ACREEDORAS SIN MBCO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_DIAS_MORA_RCC  IS 'DIAS DE MORA.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.MO_DEUD_SIST_FINA IS 'MONTO DE SALDO EN EL SISTEMA FINANCIERO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_DIAS_PROC_EVAL IS 'NUMERO DE DIAS DEL PROCESO DE EVALUACION.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_DIAS_PROC_APRO IS 'NUMERO DE DIAS DEL PROCESO DE APROBACION.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.NU_DIAS_PROC_DESE IS 'NUMERO DE DIAS DEL PROCESO DE DESEMBOLSO.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.CO_CONV_SOLI      IS 'CODIGO DEL CONVENIO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.T_RIE_ADMISION_CREDITOS.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';


-- Crear tabla BDS.C_RIE_DESEMBOLSO
CREATE TABLE BDS.C_RIE_DESEMBOLSO
(
  FE_PROCESO             DATE,
  NU_PRESTAMO            NUMBER(22)    DEFAULT (0),
  NU_SOLICITUD           NUMBER(22)    DEFAULT (0),
  NU_PERI_MES            NUMBER(6)     DEFAULT (0),
  CO_CLIENTE             NUMBER(15)    DEFAULT (0),
  CO_SEGM_RIES           VARCHAR2(3)   DEFAULT ('.'),
  CO_SEGM_NEGO           NUMBER(22)    DEFAULT (0),
  DE_SALARIO             VARCHAR2(40)  DEFAULT ('.'),
  DE_VENT_NETA           VARCHAR2(40)  DEFAULT ('.'),
  DE_UTIL_DISP           VARCHAR2(40)  DEFAULT ('.'),
  NU_EDAD                NUMBER(3)     DEFAULT (0),
  DE_RANG_EDAD           VARCHAR2(25)  DEFAULT ('.'),
  TI_VIVI_DOMI           VARCHAR2(50)  DEFAULT ('.'),
  TI_VIVI_CORR           VARCHAR2(100) DEFAULT ('.'),
  TI_VIVI_NEGO           VARCHAR2(50)  DEFAULT ('.'),
  TI_VIVI_GARA           VARCHAR2(50)  DEFAULT ('.'),
  CO_TIPO_PERS           VARCHAR2(1)   DEFAULT ('.'),
  CO_CLAS_DEPE           VARCHAR2(5)   DEFAULT ('.'),
  CO_ESTA_CIVI           VARCHAR2(5)   DEFAULT ('.'),
  CO_FUNC_DESE           NUMBER(15)    DEFAULT (0),
  NO_FUNC_DESE           VARCHAR2(150) DEFAULT ('.'),
  CO_PUES_DESE           VARCHAR2(10)  DEFAULT ('.'),
  CO_CARG_DESE           NUMBER(5)     DEFAULT (0),
  CO_AGENCIA             NUMBER(5)     DEFAULT (0),
  DE_AGENCIA             VARCHAR2(150) DEFAULT ('.'),
  CO_TERRITORIO          NUMBER(5)     DEFAULT (0),
  DE_TERRITORIO          VARCHAR2(150) DEFAULT ('.'),
  CO_REGION              NUMBER(5)     DEFAULT (0),
  DE_REGION              VARCHAR2(150) DEFAULT ('.'),
  CO_ZONA                NUMBER(5)     DEFAULT (0),
  DE_ZONA                VARCHAR2(150) DEFAULT ('.'),
  DE_RANG_RIES_TOT       VARCHAR2(20)  DEFAULT ('.'),
  DE_RANG_PLAZ_APRO      VARCHAR2(20)  DEFAULT ('.'),
  DE_RANG_ENTI_ACRE      VARCHAR2(2)   DEFAULT ('.'),
  CO_CALI_RCC_MAXI       VARCHAR2(1)   DEFAULT ('.'),
  CO_CATE_PERS           VARCHAR2(2)   DEFAULT ('.'),
  CO_USUA_TOPA_DESE      VARCHAR2(10)  DEFAULT ('.'),
  DE_ANTI_LABO_EVAL      VARCHAR2(10)  DEFAULT ('.'),
  DE_ANTI_LABO_APRO      VARCHAR2(10)  DEFAULT ('.'),
  FE_ACTU_DIA            DATE          DEFAULT SYSDATE
)
PARTITION BY RANGE (FE_PROCESO)
(
  PARTITION P_RIE_DESEMBOLSO_20140101 VALUES LESS THAN (TO_DATE(' 2014-01-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) TABLESPACE BDS_DATA_01,
  PARTITION P_RIE_DESEMBOLSO_MAX      VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);

COMMENT ON TABLE BDS.C_RIE_DESEMBOLSO IS 'TABLA DE CREDITOS DESEMBOLSADOS.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.FE_PROCESO        IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.NU_PRESTAMO       IS 'NUMERO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.NU_SOLICITUD      IS 'NUMERO DE LA SOLICITUD ASOCIADA AL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.NU_PERI_MES       IS 'NUMERO DE MES (FORMATO YYYYMM) EN EL QUE SE REGISTRO EL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_CLIENTE        IS 'CODIGO DEL CLIENTE.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_SEGM_RIES      IS 'CODIGO DEL SEGMENTO DE RIESGO DEL CLIENTE AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_SEGM_NEGO      IS 'CODIGO DEL SEGMENTO DE NEGOCIO AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_SALARIO        IS 'DESCRIPCION DEL MONTO SALARIO DEL CLIENTE AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_VENT_NETA      IS 'DESCRIPCION DEL MONTO VENTA NETA DEL CLIENTE AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_UTIL_DISP      IS 'DESCRIPCION DEL MONTO DE UTILIDAD DISPONIBLE AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.NU_EDAD           IS 'EDAD DEL CLIENTE AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_RANG_EDAD      IS 'RANGO DE EDAD DEL CLIENTE AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.TI_VIVI_DOMI      IS 'TIPO DE VIVIENDA DEL DOMICILIO DEL CLIENTE AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.TI_VIVI_CORR      IS 'TIPO DE VIVIENDA DE CORRESPONDENCIA AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.TI_VIVI_NEGO      IS 'TIPO DE VIVIENDA DEL NEGOCIO AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.TI_VIVI_GARA      IS 'TIPO DE VIVIENDA DE GARANTIA AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_TIPO_PERS      IS 'CODIGO TIPO PERSONA AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_CLAS_DEPE      IS 'CODIGO CLASE DEPENDENCIA AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_ESTA_CIVI      IS 'CODIGO ESTADO CIVIL AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_FUNC_DESE      IS 'CODIGO FUNCIONARIO AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.NO_FUNC_DESE      IS 'NOMBRE FUNCIONARIO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_PUES_DESE      IS 'CODIGO PUESTO FUNCIONARIO AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_CARG_DESE      IS 'CODIGO CARGO DE FUNCIONARIO AL MOMENTO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_AGENCIA        IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_AGENCIA        IS 'DESCIPCION DE AGENCIA.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_TERRITORIO     IS 'CODIGO TERRTITORIO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_TERRITORIO     IS 'DESCRIPCION DE TERRITORIO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_ZONA           IS 'CODIGO DE ZONA.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_ZONA           IS 'DESCRIPCION DE ZONA.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_REGION         IS 'CODIGO DE REGION.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_REGION         IS 'DESCRIPCION DE REGION.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_RANG_RIES_TOT  IS 'DESCRIPCION DE MONTO DESEMBOLSADO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_RANG_PLAZ_APRO IS 'RANGO NUMERO CUOTAS DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_RANG_ENTI_ACRE IS 'RANGO NUMERO ENTIDADES ACREEDORAS DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_CALI_RCC_MAXI  IS 'CODIGO CALCULO RCC MAXIMO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_CATE_PERS      IS 'CODIGO DE CATEGORIA PERSONA.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.CO_USUA_TOPA_DESE IS 'CODIGO DE USUARIO TOPAZ DE DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_ANTI_LABO_EVAL IS 'RANGO DE ANTIGUEDAD LABORAL DEL FUNCIONARIO DE EVALUACION.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.DE_ANTI_LABO_APRO IS 'RANGO DE ANTIGUEDAD LABORAL DEL FUNCIONARIO QUE APRUEBA.';
COMMENT ON COLUMN BDS.C_RIE_DESEMBOLSO.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';


-- Create table BDS.C_RIE_SOLICITUDES_DIA
CREATE TABLE BDS.C_RIE_SOLICITUDES_DIA
(
  FE_PROCESO        DATE,
  NU_SOLICITUD      NUMBER(22)    DEFAULT (0),
  FE_INGR_SOLI      DATE,
  CO_CLIENTE        NUMBER(15)    DEFAULT (0),
  CO_TIPO_PERS      VARCHAR2(1)   DEFAULT ('.'),
  CO_CATE_PERS      VARCHAR2(1)   DEFAULT ('.'),
  CO_CLAS_DEPE      VARCHAR2(1)   DEFAULT ('.'),
  CO_ESTA_CIVI      VARCHAR2(1)   DEFAULT ('.'),
  NU_EDAD           NUMBER(3)     DEFAULT (0),
  DE_RANG_EDAD      VARCHAR2(25)  DEFAULT ('.'),
  MO_SALARIO        NUMBER(22)    DEFAULT (0),
  MO_VENT_NETA      NUMBER(22)    DEFAULT (0),
  MO_UTIL_DISP      NUMBER(22)    DEFAULT (0),
  CO_SEGM_RIES      VARCHAR2(2)   DEFAULT ('.'),
  CO_SEGM_NEGO      NUMBER(22)    DEFAULT (0),
  CO_ACTI_INTE      NUMBER(5)     DEFAULT (0),
  CO_MONEDA         NUMBER(4)     DEFAULT (0),
  CO_ESTA_SOLI      NUMBER(3)     DEFAULT (0),
  IN_EVALUACION     NUMBER(1)     DEFAULT (0),
  IN_APROBACION     NUMBER(1)     DEFAULT (0),
  IN_DESEMBOLSO     NUMBER(1)     DEFAULT (0),
  TI_VIVI_DOMI      VARCHAR2(50)  DEFAULT ('.'),
  TI_VIVI_CORR      VARCHAR2(100) DEFAULT ('.'),
  TI_VIVI_NEGO      VARCHAR2(50)  DEFAULT ('.'),
  TI_VIVI_GARA      VARCHAR2(50)  DEFAULT ('.'),
  CO_FUNC_REGI_SOLI NUMBER(6)     DEFAULT (0),
  CO_USUA_TOPA_REGI VARCHAR2(8)   DEFAULT ('.'),
  NO_FUNC_REGI_SOLI VARCHAR2(150) DEFAULT ('.'),
  CO_PUES_REGI_SOLI VARCHAR2(10)  DEFAULT ('.'),
  CO_CARG_REGI_SOLI NUMBER(5)     DEFAULT (0),
  CO_FUNC_EVAL      NUMBER(6)     DEFAULT (0),
  CO_USUA_TOPA_EVAL VARCHAR2(8)   DEFAULT ('.'),
  NO_FUNC_EVAL      VARCHAR2(150) DEFAULT ('.'),
  CO_PUES_EVAL      VARCHAR2(10)  DEFAULT ('.'),
  CO_CARG_EVAL      NUMBER(5)     DEFAULT (0),
  CO_FUNC_APRO      NUMBER(6)     DEFAULT (0),
  CO_USUA_TOPA_APRO VARCHAR2(8)   DEFAULT ('.'),
  NO_FUNC_APRO      VARCHAR2(150) DEFAULT ('.'),
  CO_PUES_APRO      VARCHAR2(10)  DEFAULT ('.'),
  CO_CARG_APRO      NUMBER(5)     DEFAULT (0),
  CO_AGENCIA        NUMBER(5)     DEFAULT (0),
  DE_AGENCIA        VARCHAR2(150) DEFAULT ('.'),
  CO_TERRITORIO     NUMBER(5)     DEFAULT (0),
  CO_REGION         NUMBER(5)     DEFAULT (0),
  CO_ZONA           NUMBER(5)     DEFAULT (0),
  CO_CALI_RCC_MAXI  VARCHAR2(1)   DEFAULT ('.'),
  MO_PRESTAMO       NUMBER(15,2)  DEFAULT (0),
  MO_CUOTA          NUMBER(15,2)  DEFAULT (0),
  NU_PLAZOS         NUMBER(6)     DEFAULT (0),
  NU_CUOTAS         NUMBER(8)     DEFAULT (0),
  VL_TASA           NUMBER(11,7)  DEFAULT (0),
  FE_ACTU_DIA       DATE          DEFAULT SYSDATE
)
PARTITION BY RANGE (FE_PROCESO)
(
  PARTITION P_C_RIE_SOLICITUD_DIA_20200301 VALUES LESS THAN (TO_DATE(' 2020-03-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) TABLESPACE BDS_DATA_01,
  PARTITION P_C_RIE_SOLICITUD_DIA_MAX      VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);
-- Add comments to the table 
COMMENT ON TABLE BDS.C_RIE_SOLICITUDES_DIA IS 'TABLA DE SOLICITUDES DIARIAS.';
-- Add comments to the columns 
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.FE_PROCESO        IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.NU_SOLICITUD      IS 'NUMERO DE SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.FE_INGR_SOLI      IS 'FECHA DE INGRESO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_CLIENTE        IS 'CODIGO DEL CLIENTE.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_TIPO_PERS      IS 'CODIGO DEL TIPO DE PERSONA.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_CATE_PERS      IS 'CODIGO DE LA CATEGORIA DE PERSONA.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_CLAS_DEPE      IS 'CODIGO DE LA CLASE DEPENDIENTE.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_ESTA_CIVI      IS 'CODIGO DEL ESTADO CIVIL.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.NU_EDAD           IS 'EDAD DEL CLIENTE AL MOMENTO DE LA FECHA DE PROCESO, APLICA PARA PERSONAS NATURALES.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.DE_RANG_EDAD      IS 'RANGO DE EDAD DEL CLIENTE AL MOMENTO DE LA FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.MO_SALARIO        IS 'MONTO DEL SALARIO DEL CLIENTE. APLICA PARA PERSONAS NATURALES Y DEPENDIENTES';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.MO_VENT_NETA      IS 'MONTO DE LAS VENTAS NETAS DEL CLIENTE AL MOMENTO DE LA FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.MO_UTIL_DISP      IS 'MONTO DE LA UTILIDAD DISPONIBLE DEL CLIENTE AL MOMENTO DE LA FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_SEGM_RIES      IS 'CODIGO DEL SEGMENTO DE RIESGO DEL CLIENTE AL MOMENTO DE LA FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_SEGM_NEGO      IS 'CODIGO DEL SEGMENTO DE NEGOCIO AL MOMENTO DE LA FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_ACTI_INTE      IS 'CODIGO DE ACTIVIDAD INTERNA.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_MONEDA         IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_ESTA_SOLI      IS 'CODIGO DEL ESTADO DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.IN_EVALUACION     IS 'FLAG DE EVALUADO --> 1=EVALUADO, 0=SIN EVALUAR.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.IN_APROBACION     IS 'FLAG DE APROBACION --> 1=APROBADO, 0=SIN APROBADO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.IN_DESEMBOLSO     IS 'FLAG DE DESEMBOLSO --> 1=DESEMBOLSADO, 0=SIN DESEMBOLSO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.TI_VIVI_DOMI      IS 'TIPO DE VIVIENDA DEL DOMICILIO DEL CLIENTE AL MOMENTO DE LA FECHA DE PROCESO..';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.TI_VIVI_CORR      IS 'TIPO DE VIVIENDA DE CORRESPONDENCIA AL MOMENTO DE LA FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.TI_VIVI_NEGO      IS 'TIPO DE VIVIENDA DEL NEGOCIO AL MOMENTO DE LA FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.TI_VIVI_GARA      IS 'TIPO DE VIVIENDA DE GARANTIA AL MOMENTO DE LA FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_FUNC_REGI_SOLI IS 'CODIGO DEL FUNCIONARIO QUE REGISTRO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_USUA_TOPA_REGI IS 'CODIGO DEL USUARIO DE TOPAZ QUE REGISTRO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.NO_FUNC_REGI_SOLI IS 'NOMBRE DEL FUNCIONARIO QUE REGISTRO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_PUES_REGI_SOLI IS 'CODIGO DE PUESTO DEL FUNCIONARIO QUE REGISTRO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_CARG_REGI_SOLI IS 'CODIGO DEL CARGO DEL FUNCIONARIO QUE REGISTRO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_FUNC_EVAL      IS 'CODIGO DEL FUNCIONARIO QUE EVALUO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_USUA_TOPA_EVAL IS 'CODIGO DEL USUARIO DE TOPAZ QUE EVALUO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.NO_FUNC_EVAL      IS 'NOMBRE DEL FUNCIONARIO QUE EVALUO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_PUES_EVAL      IS 'CODIGO DE PUESTO DEL FUNCIONARIO QUE EVALUO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_CARG_EVAL      IS 'CODIGO DEL CARGO DEL FUNCIONARIO QUE EVALUO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_FUNC_APRO      IS 'CODIGO DEL FUNCIONARIO QUE APROBO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_USUA_TOPA_APRO IS 'CODIGO DEL USUARIO DE TOPAZ QUE APROBO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.NO_FUNC_APRO      IS 'NOMBRE DEL FUNCIONARIO QUE APROBO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_PUES_APRO      IS 'CODIGO DE PUESTO DEL FUNCIONARIO QUE APROBO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_CARG_APRO      IS 'CODIGO DEL CARGO DEL FUNCIONARIO QUE APROBO LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_AGENCIA        IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.DE_AGENCIA        IS 'DESCRIPCION DE LA AGENCIA.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_TERRITORIO     IS 'CODIGO DE TERRITORIO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_REGION         IS 'CODIGO DE REGION.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_ZONA           IS 'CODIGO DE ZONA.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.CO_CALI_RCC_MAXI  IS 'MAXIMA CALIFICACION EN RCC.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.MO_PRESTAMO       IS 'MONTO DEL PRESTAMO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.MO_CUOTA          IS 'MONTO DE LA CUOTA.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.NU_PLAZOS         IS 'NUMERO DE PLAZO SOLICITADO.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.NU_CUOTAS         IS 'NUMERO DE CUOTAS DE LA SOLICITUD.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.VL_TASA           IS 'VALOR DE LA TASA DE INTERES.';
COMMENT ON COLUMN BDS.C_RIE_SOLICITUDES_DIA.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

-- Create table BDS.L_RIE_PRESTAMOS_EXTORNADOS
CREATE TABLE BDS.L_RIE_PRESTAMOS_EXTORNADOS(
 FE_PROCESO  DATE not null,
 FE_EXTORNO  DATE not null,
 NU_PRESTAMO NUMBER(15) default (0) not null,
 FE_ACTU_DIA DATE default SYSDATE
)
PARTITION BY RANGE (FE_PROCESO)
(
 PARTITION P_RIE_PREST_EXTOR_20160101 VALUES LESS THAN (TO_DATE(' 2016-01-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) TABLESPACE BDS_DATA_01,
 PARTITION P_RIE_PREST_EXTOR_MAX      VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);
-- Add comments to the table 
COMMENT ON TABLE BDS.L_RIE_PRESTAMOS_EXTORNADOS IS 'TABLA DE HECHOS DE PRESTAMOS EXTORNADOS.';
-- Add comments to the columns 
COMMENT ON COLUMN BDS.L_RIE_PRESTAMOS_EXTORNADOS.FE_PROCESO  IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.L_RIE_PRESTAMOS_EXTORNADOS.FE_EXTORNO  IS 'FECHA DE EXTORNO DEL CREDITO.';
COMMENT ON COLUMN BDS.L_RIE_PRESTAMOS_EXTORNADOS.NU_PRESTAMO IS 'NUMERO DEL PRESTAMO.';
COMMENT ON COLUMN BDS.L_RIE_PRESTAMOS_EXTORNADOS.FE_ACTU_DIA IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';


-- Create table BDS.L_RIE_AUSENTE_HM_EGP
CREATE TABLE BDS.L_RIE_AUSENTE_HM_EGP(
 FE_PROCESO  DATE not null,
 NU_PERI_MES NUMBER(6),
 NU_PRESTAMO NUMBER(15) default (0) not null,
 FE_ACTU_MES DATE default SYSDATE
)
PARTITION BY RANGE (NU_PERI_MES)
(
 PARTITION P_RIE_AUSENTE_HM_EGP_201601 VALUES LESS THAN (201602)   TABLESPACE BDS_DATA_01,
 PARTITION P_RIE_AUSENTE_HM_EGP_MAX    VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);
-- Add comments to the table 
COMMENT ON TABLE BDS.L_RIE_AUSENTE_HM_EGP IS 'TABLA DE HECHOS DE PRESTAMOS AUSENTES EN HM EGP.';
-- Add comments to the columns 
COMMENT ON COLUMN BDS.L_RIE_AUSENTE_HM_EGP.FE_PROCESO  IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN BDS.L_RIE_AUSENTE_HM_EGP.NU_PERI_MES IS 'NUMERO DE MES (FORMATO YYYYMM) EN EL QUE SE REGISTRO EL HECHO.';
COMMENT ON COLUMN BDS.L_RIE_AUSENTE_HM_EGP.NU_PRESTAMO IS 'NUMERO DEL DESEMBOLSO.';
COMMENT ON COLUMN BDS.L_RIE_AUSENTE_HM_EGP.FE_ACTU_MES IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';



-- Create table BDS.F_RIE_PRESTAMOS_REFINANCIADOS
CREATE TABLE BDS.F_RIE_PRESTAMOS_REFINANCIADOS
(
FE_PROCESO            DATE,
NU_SOLICITUD          NUMBER(15)    DEFAULT 0,
NU_PRESTAMO           NUMBER(15)    DEFAULT 0,
CO_CLIENTE            NUMBER(15)    DEFAULT 0,
FE_DESEMBOLSO         DATE,
CO_REFINANCIADO       VARCHAR2(1)   DEFAULT '.',
NU_PRES_CANC          NUMBER(15)    DEFAULT 0,
NU_SOLI_CANC          NUMBER(15)    DEFAULT 0,
CO_MONE_CANC          NUMBER(5)     DEFAULT 0,
CO_PROD_CANC          NUMBER(10)    DEFAULT 0,
CO_CLIE_CANC          NUMBER(15)    DEFAULT 0,
MO_CRED_CANC          NUMBER(15,2)  DEFAULT 0,
MO_CRED_INDI_CANC     NUMBER(15,2)  DEFAULT 0,
CO_MOTI_CANC          VARCHAR2(1)   DEFAULT '.',
NU_ORDE_PRES_CANC     NUMBER(15)    DEFAULT 0,
VL_PORC_PRES_CANC     NUMBER        DEFAULT 0 ,
FE_ACTU_DIA           DATE          DEFAULT SYSDATE
)
PARTITION BY RANGE (FE_PROCESO)
(
  PARTITION P_F_RIE_PRESTAMOS_REF_20200301 VALUES LESS THAN (TO_DATE(' 2020-03-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) TABLESPACE BDS_DATA_01,
  PARTITION P_F_RIE_PRESTAMOS_REF_MAX      VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);
COMMENT ON TABLE BDS.F_RIE_PRESTAMOS_REFINANCIADOS IS 'TABLA DE HECHOS DE PRESTAMOS REFINANCIADOS.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.FE_PROCESO        IS 'FECHA DE PROCESO DEL REGISTRO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.NU_SOLICITUD      IS 'NUMERO DE SOLICITUD.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.NU_PRESTAMO       IS 'NUMERO DE PRESTAMO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.CO_CLIENTE        IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.FE_DESEMBOLSO     IS 'FECHA DE DESEMBOLSO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.CO_REFINANCIADO   IS 'CODIGO DE REFINANCIADO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.NU_PRES_CANC      IS 'NUMERO DE PRESTAMO CANCELADO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.NU_SOLI_CANC      IS 'NUMERO DE SOLICITUD CANCELADO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.CO_MONE_CANC      IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.CO_PROD_CANC      IS 'CODIGO DE PRODUCTO CANCELADO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.CO_CLIE_CANC      IS 'CODIGO DE CLIENTE CANCELADO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.MO_CRED_CANC      IS 'MONTO CREDITO CANCELADO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.MO_CRED_INDI_CANC IS 'MONTO CREDITO INDIVIDUAL CANCELADO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.CO_MOTI_CANC      IS 'CODIGO MOTIVO CANCELACION.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.NU_ORDE_PRES_CANC IS 'NUMERO DE ORDEN PRESTAMO CANCELADO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.VL_PORC_PRES_CANC IS 'VALOR PORCENTUAL DEL PRESTAMO CANCELADO.';
COMMENT ON COLUMN BDS.F_RIE_PRESTAMOS_REFINANCIADOS.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';


-- Create table ODS.MD_MOTIVO_CANCELA_PRESTAMO
CREATE TABLE ODS.MD_MOTIVO_CANCELA_PRESTAMO
(
CO_MOTI_CANC_PRES      VARCHAR2(1)   DEFAULT '.',   
DE_MOTI_CANC_PRES      VARCHAR2(150) DEFAULT '.',
FE_ACTU_DIA            DATE          DEFAULT SYSDATE
) TABLESPACE ODS_DATA_01;
COMMENT ON TABLE ODS.MD_MOTIVO_CANCELA_PRESTAMO IS 'TABLA MAESTRA DE MOTIVOS DE CANCELACION DE PRESTAMOS.';
COMMENT ON COLUMN ODS.MD_MOTIVO_CANCELA_PRESTAMO.CO_MOTI_CANC_PRES IS 'CODIGO DE MOTIVO DE CANCELACION DE PRESTAMO.';
COMMENT ON COLUMN ODS.MD_MOTIVO_CANCELA_PRESTAMO.DE_MOTI_CANC_PRES IS 'DESCRIPCION DE MOTIVO DE CANCELACION DE PRESTAMO.';
COMMENT ON COLUMN ODS.MD_MOTIVO_CANCELA_PRESTAMO.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';




-- Create table ODS.MD_TIPO_VIVIENDA
CREATE TABLE ODS.MD_TIPO_VIVIENDA
(
TI_VIVIENDA          VARCHAR2(2)   DEFAULT '.',          
DE_TIPO_VIVI         VARCHAR2(150) DEFAULT '.',
FE_ACTU_DIA          DATE          DEFAULT SYSDATE
) TABLESPACE ODS_DATA_01;
COMMENT ON TABLE ODS.MD_TIPO_VIVIENDA IS 'TABLA MAESTRA DEL TIPO DE VIVIENDA.';
COMMENT ON COLUMN ODS.MD_TIPO_VIVIENDA.TI_VIVIENDA  IS 'TIPO DE VIVIENDA.';
COMMENT ON COLUMN ODS.MD_TIPO_VIVIENDA.DE_TIPO_VIVI IS 'DESCRIPCION DEL TIPO DE VIVIENDA.';
COMMENT ON COLUMN ODS.MD_TIPO_VIVIENDA.FE_ACTU_DIA  IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

-- Crear tabla BDS.D_GEN_LINEA_CREDITO
CREATE TABLE BDS.D_GEN_LINEA_CREDITO
(
  NU_LINE_CRED                 NUMBER(15)    DEFAULT (0),
  MO_LINE_CRED                 NUMBER(15,2)  DEFAULT (0),
  DE_ESTA_LINE                 VARCHAR2(150) DEFAULT ('.'),
  FE_APERTURA                  DATE,
  FE_CIERRE                    DATE,
  NU_DISPOSICIONES             NUMBER(5)     DEFAULT (0),
  DE_RANG_NUME_DISP            VARCHAR2(3)   DEFAULT ('.'),
  FE_ACTU_DIA                  DATE          DEFAULT SYSDATE 
) TABLESPACE BDS_DATA_01;
  
COMMENT ON TABLE BDS.D_GEN_LINEA_CREDITO IS 'TABLA DIMENSION GENERICA DE LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_LINEA_CREDITO.NU_LINE_CRED      IS 'NUMERO DE LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_LINEA_CREDITO.MO_LINE_CRED      IS 'MONTO OTORGADO A LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_LINEA_CREDITO.DE_ESTA_LINE      IS 'ESTADO DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_LINEA_CREDITO.FE_APERTURA       IS 'FECHA DE APERTURA DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_LINEA_CREDITO.FE_CIERRE         IS 'FECHA DE VENCIMIENTO ORIGINAL DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_LINEA_CREDITO.NU_DISPOSICIONES  IS 'NUMERO DE DISPOSICIONES DE LA LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_LINEA_CREDITO.DE_RANG_NUME_DISP IS 'RANGO POR NUMERO DE DISPOSICIONES DE LINEA DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_LINEA_CREDITO.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

ALTER TABLE BDS.D_GEN_LINEA_CREDITO
ADD CONSTRAINT PK_D_GEN_LINEA_CREDITO
PRIMARY KEY ( NU_LINE_CRED);

-- Create table BDS.D_GEN_CATEGORIA_PERSONA
CREATE TABLE BDS.D_GEN_CATEGORIA_PERSONA
(
CO_CATE_PERS        VARCHAR2(2)   DEFAULT '.',
DE_CATE_PERS        VARCHAR2(150) DEFAULT '.',
FE_ACTU_DIA         DATE          DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;
COMMENT ON TABLE BDS.D_GEN_CATEGORIA_PERSONA IS 'TABLA DIMENSION GENERICA DE CATEGORIA DE PERSONA.';
COMMENT ON COLUMN BDS.D_GEN_CATEGORIA_PERSONA.CO_CATE_PERS IS 'CODIGO DE CATEGORIZACION DE LA PERSONA.';
COMMENT ON COLUMN BDS.D_GEN_CATEGORIA_PERSONA.DE_CATE_PERS IS 'DESCRIPCION DE CATEGORIZACION DE LA PERSONA.';
COMMENT ON COLUMN BDS.D_GEN_CATEGORIA_PERSONA.FE_ACTU_DIA  IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

ALTER TABLE BDS.D_GEN_CATEGORIA_PERSONA
ADD CONSTRAINT PK_D_GEN_CATEGORIA_PERSONA
PRIMARY KEY (CO_CATE_PERS );



-- Create table BDS.D_GEN_SEGMENTO_NEGOCIO
CREATE TABLE BDS.D_GEN_SEGMENTO_NEGOCIO
(
CO_SEGM_NEGO        NUMBER(5)     DEFAULT 0,
DE_SEGM_NEGO        VARCHAR2(150) DEFAULT '.',
FE_ACTU_DIA         DATE          DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;
COMMENT ON TABLE BDS.D_GEN_SEGMENTO_NEGOCIO IS 'TABLA DIMENSION GENERICA DE SEGMENTO NEGOCIO.';
COMMENT ON COLUMN BDS.D_GEN_SEGMENTO_NEGOCIO.CO_SEGM_NEGO IS 'CODIGO DE SEGMENTACION DE NEGOCIO.';
COMMENT ON COLUMN BDS.D_GEN_SEGMENTO_NEGOCIO.DE_SEGM_NEGO IS 'DESCRIPCION DE SEGMENTACION DE NEGOCIO.';
COMMENT ON COLUMN BDS.D_GEN_SEGMENTO_NEGOCIO.FE_ACTU_DIA  IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

ALTER TABLE BDS.D_GEN_SEGMENTO_NEGOCIO
ADD CONSTRAINT PK_D_GEN_SEGMENTO_NEGOCIO
PRIMARY KEY (CO_SEGM_NEGO);

-- Create table BDS.D_GEN_TIPO_CAMBIO
CREATE TABLE BDS.D_GEN_TIPO_CAMBIO
(
FE_COTIZACION        DATE,
CO_TIPO_CAMB         NUMBER(5)    DEFAULT 0,
CO_MONEDA            NUMBER(5)    DEFAULT 0,
VL_TIPO_CAMB_COMP    NUMBER(15,9) DEFAULT 0,
VL_TIPO_CAMB_VENT    NUMBER(15,9) DEFAULT 0,
VL_TIPO_CAMB_OFIC    NUMBER(15,9) DEFAULT 0,
FE_ACTU_DIA          DATE         DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;
COMMENT ON TABLE BDS.D_GEN_TIPO_CAMBIO IS 'TABLA DIMENSION GENERICA DE TIPO DE CAMBIO.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CAMBIO.FE_COTIZACION     IS 'FECHA DE COTIZACION.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CAMBIO.CO_TIPO_CAMB      IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CAMBIO.CO_MONEDA         IS 'CODIGO DE TIPO DE CAMBIO.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CAMBIO.VL_TIPO_CAMB_COMP IS 'TIPO DE CAMBIO COMPRA.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CAMBIO.VL_TIPO_CAMB_VENT IS 'TIPO DE CAMBIO VENTA.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CAMBIO.VL_TIPO_CAMB_OFIC IS 'TIPO DE CAMBIO OFICIAL.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CAMBIO.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

ALTER TABLE BDS.D_GEN_TIPO_CAMBIO
ADD CONSTRAINT PK_D_GEN_TIPO_CAMBIO
PRIMARY KEY (FE_COTIZACION,CO_TIPO_CAMB,CO_MONEDA );

-- Create table BDS.D_GEN_TIPO_VIVIENDA
CREATE TABLE BDS.D_GEN_TIPO_VIVIENDA
(
TI_VIVIENDA          VARCHAR2(2)   DEFAULT '.',          
DE_TIPO_VIVI         VARCHAR2(150) DEFAULT '.',
FE_ACTU_DIA          DATE          DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;
COMMENT ON TABLE BDS.D_GEN_TIPO_VIVIENDA IS 'TABLA DIMENSION GENERICA DE TIPO DE VIVIENDA.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_VIVIENDA.TI_VIVIENDA  IS 'TIPO DE VIVIENDA.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_VIVIENDA.DE_TIPO_VIVI IS 'DESCRIPCION DEL TIPO DE VIVIENDA.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_VIVIENDA.FE_ACTU_DIA  IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

ALTER TABLE BDS.D_GEN_TIPO_VIVIENDA
ADD CONSTRAINT PK_D_GEN_TIPO_VIVIENDA
PRIMARY KEY (TI_VIVIENDA);


-- Create table BDS.D_GEN_TIPO_CREDITO
CREATE TABLE BDS.D_GEN_TIPO_CREDITO
(
CO_TIPO_CRED        VARCHAR2(3)   DEFAULT '.',
DE_TIPO_CRED        VARCHAR2(150) DEFAULT '.',
FE_ACTU_DIA         DATE          DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;
COMMENT ON TABLE BDS.D_GEN_TIPO_CREDITO IS 'TABLA DIMENSION GENERICA DE TIPO DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CREDITO.CO_TIPO_CRED IS 'CODIGO DEL TIPO DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CREDITO.DE_TIPO_CRED IS 'DESCRIPCION DEL TIPO DE CREDITO.';
COMMENT ON COLUMN BDS.D_GEN_TIPO_CREDITO.FE_ACTU_DIA  IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

ALTER TABLE BDS.D_GEN_TIPO_CREDITO
ADD CONSTRAINT PK_D_GEN_TIPO_CREDITO
PRIMARY KEY (CO_TIPO_CRED );
-- Create table BDS.D_GEN_MOTIVO_CANCELA_PRESTAMO
CREATE TABLE BDS.D_GEN_MOTIVO_CANCELA_PRESTAMO
(
CO_MOTI_CANC_PRES      VARCHAR2(1)   DEFAULT '.',   
DE_MOTI_CANC_PRES      VARCHAR2(150) DEFAULT '.',
FE_ACTU_DIA            DATE          DEFAULT SYSDATE
) TABLESPACE BDS_DATA_01;
COMMENT ON TABLE BDS.D_GEN_MOTIVO_CANCELA_PRESTAMO IS 'TABLA DIMENSION GENERICA DE MOTIVO DE CANCELACION DE PRESTAMOS.';
COMMENT ON COLUMN BDS.D_GEN_MOTIVO_CANCELA_PRESTAMO.CO_MOTI_CANC_PRES IS 'CODIGO DE MOTIVO DE CANCELACION DE PRESTAMO.';
COMMENT ON COLUMN BDS.D_GEN_MOTIVO_CANCELA_PRESTAMO.DE_MOTI_CANC_PRES IS 'DESCRIPCION DE MOTIVO DE CANCELACION DE PRESTAMO.';
COMMENT ON COLUMN BDS.D_GEN_MOTIVO_CANCELA_PRESTAMO.FE_ACTU_DIA       IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

ALTER TABLE BDS.D_GEN_MOTIVO_CANCELA_PRESTAMO
ADD CONSTRAINT PK_D_GEN_MOTIVO_CANCELA
PRIMARY KEY (CO_MOTI_CANC_PRES );


