-----------CREACION VISTA DE DIMENSION D_GEN_ACTIVIDAD_INTERNA--------------01
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_ACTIVIDAD_INTERNA_VW AS 
SELECT CO_ACTI_ECON_INTE,DE_ACTI_ECON_INTE FROM ODS.MD_ACTIVIDAD_ECONOMICA_INTERNA;

-----------CREACION VISTA DE DIMENSION D_GEN_CARGO--------------------------02
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_CARGO_VW AS 
SELECT CO_CARGO,DE_CARGO FROM ODS.MD_CARGO;

-----------CREACION VISTA DE DIMENSION D_GEN_CLASE_DEPEND-------------------03
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_CLASE_DEPEND_VW AS
SELECT CO_CLAS_DEPE, DE_CLAS_DEPE FROM ODS.MD_CLASIFICACION_DEPENDIENTE;

-----------CREACION VISTA DE DIMENSION D_GEN_ESTADO_CIVIL-------------------04
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_ESTADO_CIVIL_VW AS
SELECT CO_ESTA_CIVI,DE_ESTA_CIVI FROM ODS.MD_ESTADO_CIVIL;

-----------CREACION VISTA DE DIMENSION D_GEN_ESTADO_SOLICITUD---------------05
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_ESTADO_SOLICITUD_VW AS
SELECT CO_ESTADO AS CO_ESTA_SOLI,DE_ESTADO AS DE_ESTA_SOLI FROM ODS.MD_ESTADO_SOLICITUD;

-----------CREACION VISTA DE DIMENSION D_GEN_FORMA_DESEMBOLSO---------------06
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_FORMA_DESEMBOLSO_VW AS
SELECT CO_FORM_DESE,DE_FORM_DESE FROM ODS.MD_FORMA_DESEMBOLSO;

-----------CREACION VISTA DE DIMENSION D_GEN_PUESTO-------------------------07
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_PUESTO_VW AS
SELECT CO_PUESTO,DE_PUESTO FROM ODS.MD_PUESTO;

-----------CREACION VISTA DE DIMENSION D_GEN_D_SEGMENTO_RIESGO--------------08
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_SEGMENTO_RIESGO_VW AS
SELECT CO_SEGMENTACION,DE_SEGMENTACION FROM ODS.MD_SEGMENTACION;

-----------CREACION VISTA DE DIMENSION D_GEN_TIPO_DOCUMENTO-----------------09
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_TIPO_DOCUMENTO_VW AS
SELECT TI_DOCUMENTO,DE_DOCUMENTO FROM ODS.MD_TIPO_DOCUMENTO;

-----------CREACION VISTA DE DIMENSION D_GEN_TIPO_GRACIA--------------------10
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_TIPO_GRACIA_VW AS
SELECT CO_TIPO_GRAC,DE_TIPO_GRAC FROM ODS.MD_TIPO_GRACIA;

-----------CREACION VISTA DE DIMENSION D_GEN_TIPO_PERSONA-------------------11
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_TIPO_PERSONA_VW AS
SELECT TI_PERSONA,DE_PERSONA FROM ODS.MD_TIPO_PERSONA;

-----------CREACION VISTA DE DIMENSION D_GEN_TIPO_SOLICITUD-----------------12
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_TIPO_SOLICITUD_VW AS
SELECT CO_TIPO_SOLI,DE_TIPO_SOLI FROM ODS.MD_TIPO_SOLICITUD;

-----------CREACION VISTA DE DIMENSION D_GEN_TIPO_PRESTAMO------------------13
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_TIPO_PRESTAMO_VW AS
SELECT CO_TIPO_PRES,DE_TIPO_PRES FROM ODS.MD_TIPO_PRESTAMO;

-----------CREACION VISTA DE DIMENSION BDS.D_GEN_ESTADO_PRESTAMO------------14
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_ESTADO_PRESTAMO_VW AS
SELECT CO_ESTA_OPER AS CO_ESTA_PRES, DE_ESTA_OPER AS DE_ESTA_PRES FROM ODS.MD_ESTADO_OPERACION;

-----------CREACION VISTA DE DIMENSION BDS.D_GEN_REFINANCIACION-------------15
CREATE OR REPLACE VIEW BDS.BDS_D_GEN_REFINANCIACION_VW AS
SELECT CO_REFINANCIADO AS CO_REFINANCIACION, DE_REFINANCIADO AS DE_REFINANCIACION FROM ODS.MD_REFINANCIADOS;