
/* ** Campos Nuevos en la tabla HD_ASIENTOS** */
ALTER TABLE ODS.HD_ASIENTOS
  ADD ( NU_TRREAL NUMBER(5) DEFAULT 0,
        NU_ORDINAL NUMBER(10) DEFAULT 0,
        NU_TRTIPO NUMBER(5) DEFAULT 0,
        TI_MOVI_CONTA VARCHAR2(1) DEFAULT '.',
        NU_CUENTA NUMBER DEFAULT 0,
        IN_SIGNO VARCHAR2(50) DEFAULT '.',
        FE_VALOR DATE,
        MO_IMPORTE NUMBER(15,2) DEFAULT 0,
        MO_IMPO_MN NUMBER(15,2) DEFAULT 0,
        IN_AJUSTE VARCHAR2(1) DEFAULT '.' );
                
    
COMMENT ON COLUMN ODS.HD_ASIENTOS.NU_TRREAL 
IS 'NUMERO DE LA TRANSACCION REAL DEL MOVIMIENTO CONTABLE';

COMMENT ON COLUMN ODS.HD_ASIENTOS.NU_ORDINAL 
IS 'IDENTIFICADOR DE TRANSACCION';  

COMMENT ON COLUMN ODS.HD_ASIENTOS.NU_TRTIPO 
IS 'NUMERO DE TIPO DE TRANSACCION DEL MOVIMIENTO CONTABLE';

COMMENT ON COLUMN ODS.HD_ASIENTOS.TI_MOVI_CONTA 
IS 'TIPO DEL MOVIMIENTO CONTABLE';

COMMENT ON COLUMN ODS.HD_ASIENTOS.NU_CUENTA 
IS 'NUMERO DE CUENTA (PRESTAMO/CUENTA DE AHORROS)';  

COMMENT ON COLUMN ODS.HD_ASIENTOS.IN_SIGNO 
IS 'IDENTIFICADOR DE OPERACION SI ES DEBITO/CREDITO';

COMMENT ON COLUMN ODS.HD_ASIENTOS.FE_VALOR 
IS 'FECHA VALOR DEL MOVIMIENTO CONTABLE';

COMMENT ON COLUMN ODS.HD_ASIENTOS.MO_IMPORTE 
IS 'MONTO DE IMPORTE ORIGEN DE LA TRANSACCION';

COMMENT ON COLUMN ODS.HD_ASIENTOS.MO_IMPO_MN 
IS 'MONTO DE IMPORTE ORIGEN DE LA TRANSACCION EN MONEDA NACIONAL';    

COMMENT ON COLUMN ODS.HD_ASIENTOS.IN_AJUSTE 
IS 'INDICADOR DE AJUSTE';
	 
/* ** Campos Nuevos en la tabla TD_ASIENTOS** */
alter table ODS.TD_ASIENTOS
  ADD ( NU_TRREAL        NUMBER(5) DEFAULT 0,
        NU_ORDINAL       NUMBER(10) DEFAULT 0,
        NU_TRTIPO        NUMBER(5) DEFAULT 0,
        TI_MOVI_CONTA    VARCHAR2(1) DEFAULT '.',
        NU_CUENTA     NUMBER DEFAULT 0,
        IN_SIGNO         VARCHAR2(50)  DEFAULT '.',
        FE_VALOR         DATE,
        MO_IMPORTE        NUMBER(15,2) DEFAULT 0,  
        MO_IMPO_MN       NUMBER(15,2) DEFAULT 0,
        IN_AJUSTE        VARCHAR2(1)  DEFAULT '.');
                
   
  COMMENT ON COLUMN ODS.TD_ASIENTOS.NU_TRREAL 
     IS 'NUMERO DE LA TRANSACCION REAL DEL MOVIMIENTO CONTABLE';
     
   COMMENT ON COLUMN ODS.TD_ASIENTOS.NU_ORDINAL 
     IS 'IDENTIFICADOR DE TRANSACCION';  
   
   COMMENT ON COLUMN ODS.TD_ASIENTOS.NU_TRTIPO 
     IS 'NUMERO DE TIPO DE TRANSACCION DEL MOVIMIENTO CONTABLE';
     
   COMMENT ON COLUMN ODS.TD_ASIENTOS.TI_MOVI_CONTA 
     IS 'TIPO DEL MOVIMIENTO CONTABLE';
     
   COMMENT ON COLUMN ODS.TD_ASIENTOS.NU_CUENTA 
     IS 'NUMERO DE CUENTA (PRESTAMO/CUENTA DE AHORROS)';  
     
   COMMENT ON COLUMN ODS.TD_ASIENTOS.IN_SIGNO 
     IS 'IDENTIFICADOR DE OPERACION SI ES DEBITO/CREDITO';
     
   COMMENT ON COLUMN ODS.TD_ASIENTOS.FE_VALOR 
     IS 'FECHA VALOR DEL MOVIMIENTO CONTABLE';
     
   COMMENT ON COLUMN ODS.TD_ASIENTOS.MO_IMPORTE 
     IS 'MONTO DE IMPORTE ORIGEN DE LA TRANSACCION';
     
   COMMENT ON COLUMN ODS.TD_ASIENTOS.MO_IMPO_MN 
     IS 'MONTO DE IMPORTE ORIGEN DE LA TRANSACCION EN MONEDA NACIONAL';    
     
   COMMENT ON COLUMN ODS.TD_ASIENTOS.IN_AJUSTE 
     IS 'INDICADOR DE AJUSTE';
	 