-- =========================
-- ODS.HD_PRESTAMOS_REFINANCIADOS
-- =========================

--ADICIONAR CAMPO.
ALTER TABLE STG.T_TMP_MONTOS_SALDOS ADD C1704 NUMBER(15);
ALTER TABLE STG.T_TMP_MONTOS_SALDOS ADD C1803 NUMBER(15);
ALTER TABLE STG.T_TMP_MONTOS_SALDOS ADD CUENTA NUMBER(15);
ALTER TABLE STG.T_TMP_MONTOS_SALDOS_HIST ADD C1704_HIST NUMBER(15);
ALTER TABLE STG.T_TMP_MONTOS_SALDOS_HIST ADD C1803_HIST NUMBER(15);
ALTER TABLE STG.T_TMP_MONTOS_SALDOS_HIST ADD CUENTA_HIST NUMBER(15);

--ELIMINAR CAMPO.
ALTER TABLE ODS.HD_PRESTAMOS_REFINANCIADOS DROP COLUMN DE_MOTI_CANC;

--MODIFICAR TIPO DE VARIABLE.
ALTER TABLE ODS.HD_PRESTAMOS_REFINANCIADOS MODIFY VL_PORC_PRES_CANC NUMBER;

--CAMBIAR NOMBRE DE CAMPO SEGUN ESTANDAR.
ALTER TABLE ODS.HD_PRESTAMOS_REFINANCIADOS RENAME COLUMN CO_TIPO_REFI TO CO_REFINANCIADO;
ALTER TABLE ODS.HD_PRESTAMOS_REFINANCIADOS RENAME COLUMN MO_CRED_IND_CANC TO MO_CRED_INDI_CANC;

--ADICIONAR COMENTARIOS DE COLUMNAS NUEVAS 
COMMENT ON COLUMN ODS.HD_PRESTAMOS_REFINANCIADOS.CO_REFINANCIADO IS 'CODIGO DE REFINANCIADO.';
COMMENT ON COLUMN STG.T_TMP_MONTOS_SALDOS.C1704 IS 'NUMERO DE SOLICITUD.';
COMMENT ON COLUMN STG.T_TMP_MONTOS_SALDOS.C1803 IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN STG.T_TMP_MONTOS_SALDOS.CUENTA IS 'NUMERO DE PRESTAMO.';
COMMENT ON COLUMN STG.T_TMP_MONTOS_SALDOS_HIST.C1704_HIST IS 'NUMERO DE SOLICITUD.';
COMMENT ON COLUMN STG.T_TMP_MONTOS_SALDOS_HIST.C1803_HIST IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN STG.T_TMP_MONTOS_SALDOS_HIST.CUENTA_HIST IS 'NUMERO DE PRESTAMO.';

-- =========================
-- ODS.MD_TIPO_PERSONA
-- =========================
-- Modifica el nombre del campo
ALTER TABLE ODS.MD_TIPO_PERSONA RENAME COLUMN TI_PERSONA TO DE_PERSONA;
ALTER TABLE ODS.MD_TIPO_PERSONA RENAME COLUMN CO_PERSONA TO TI_PERSONA;

-- Add comments to the columns 
comment on column ODS.MD_TIPO_PERSONA.TI_PERSONA is 'TIPO DE PERSONA';
comment on column ODS.MD_TIPO_PERSONA.DE_PERSONA is 'DESCRIPCION TIPO DE PERSONA';
