-----------CREACION SINONIMO DE DIMENSION D_GEN_ACTIVIDAD_INTERNA--------------01
CREATE OR REPLACE SYNONYM BDS.D_GEN_ACTIVIDAD_INTERNA FOR BDS.BDS_D_GEN_ACTIVIDAD_INTERNA_VW; 

-----------CREACION SINONIMO DE DIMENSION D_GEN_CARGO--------------------------02
CREATE OR REPLACE SYNONYM BDS.D_GEN_CARGO FOR BDS.BDS_D_GEN_CARGO_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_CLASE_DEPEND-------------------03
CREATE OR REPLACE SYNONYM BDS.D_GEN_CLASE_DEPEN FOR BDS.BDS_D_GEN_CLASE_DEPEND_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_ESTADO_CIVIL-------------------04
CREATE OR REPLACE SYNONYM BDS.D_GEN_ESTADO_CIVIL FOR BDS.BDS_D_GEN_ESTADO_CIVIL_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_ESTADO_SOLICITUD---------------05
CREATE OR REPLACE SYNONYM BDS.D_GEN_ESTADO_SOLICITUD FOR BDS.BDS_D_GEN_ESTADO_SOLICITUD_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_FORMA_DESEMBOLSO---------------06
CREATE OR REPLACE SYNONYM BDS.D_GEN_FORMA_DESEMBOLSO FOR BDS.BDS_D_GEN_FORMA_DESEMBOLSO_VW; 

-----------CREACION SINONIMO DE DIMENSION D_GEN_PUESTO-------------------------07
CREATE OR REPLACE SYNONYM BDS.D_GEN_PUESTO FOR BDS.BDS_D_GEN_PUESTO_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_D_SEGMENTO_RIESGO--------------08
CREATE OR REPLACE SYNONYM BDS.D_GEN_SEGMENTO_RIESGO FOR BDS.BDS_D_GEN_SEGMENTO_RIESGO_VW;
 
-----------CREACION SINONIMO DE DIMENSION D_GEN_TIPO_DOCUMENTO-----------------09
CREATE OR REPLACE SYNONYM BDS.D_GEN_TIPO_DOCUMENTO FOR BDS.BDS_D_GEN_TIPO_DOCUMENTO_VW;
 
-----------CREACION SINONIMO DE DIMENSION D_GEN_TIPO_GRACIA--------------------10
CREATE OR REPLACE SYNONYM BDS.D_GEN_TIPO_GRACIA FOR BDS.BDS_D_TIPO_GRACIA_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_TIPO_PERSONA-------------------11
CREATE OR REPLACE SYNONYM BDS.D_GEN_TIPO_PERSONA FOR BDS.BDS_D_GEN_TIPO_PERSONA_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_TIPO_SOLICITUD-----------------12
CREATE OR REPLACE SYNONYM BDS.D_GEN_TIPO_SOLICITUD FOR BDS.BDS_D_TIPO_SOLICITUD_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_TIPO_PRESTAMO------------------13
CREATE OR REPLACE SYNONYM BDS.D_GEN_TIPO_PRESTAMO FOR BDS.BDS_D_GEN_TIPO_PRESTAMO_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_ESTADO_PRESTAMO----------------14
CREATE OR REPLACE SYNONYM BDS.D_GEN_ESTADO_PRESTAMO FOR BDS.BDS_D_GEN_ESTADO_PRESTAMO_VW;

-----------CREACION SINONIMO DE DIMENSION D_GEN_REFINANCIACION-----------------15
CREATE OR REPLACE SYNONYM BDS.D_GEN_REFINANCIACION FOR BDS.BDS_D_GEN_REFINANCIACION_VW;