-- =====================================================
-- Creacion de Tabla Externa de Distribución de Agencias
-- =====================================================
CREATE TABLE STG.DE_DISTRIBUCION_AGENCIAS
(
  CODIGOAGENCIA        VARCHAR2(15),
  AGENCIA              VARCHAR2(150),
  TERRITORIO           VARCHAR2(150),
  REGION               VARCHAR2(150),
  OLA                  VARCHAR2(150),
  TIPOAG               VARCHAR2(150),
  TIPODEMOVILIDAD      VARCHAR2(150),
  CODAGENCIAACARGO     VARCHAR2(15),
  PERIODO              VARCHAR2(6)
)
ORGANIZATION EXTERNAL
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY DIR_IN_DE_NEG
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    BADFILE '%a_%p.bad'
    LOGFILE '%a_%p.log'
    NOLOGFILE
    FIELDS TERMINATED BY '|' LRTRIM
    MISSING FIELD VALUES ARE NULL
    REJECT ROWS WITH ALL NULL FIELDS
  )
  location (DIR_IN_DE_NEG:'DE_DISTRIBUCION_AGENCIAS.csv')
)
reject limit UNLIMITED;


-- ========================================================
-- Creacion de Tabla Externa de Geolocalización de Agencias
-- ========================================================
CREATE TABLE STG.DE_GEO_AGENCIAS
(
  COD_AGEN             VARCHAR2(15),
  X                    VARCHAR2(50),
  Y                    VARCHAR2(50)
)
ORGANIZATION EXTERNAL
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY DIR_IN_DE_MKT
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    BADFILE '%a_%p.bad'
    LOGFILE '%a_%p.log'
    NOLOGFILE
    FIELDS TERMINATED BY '|' LRTRIM
    MISSING FIELD VALUES ARE NULL
    REJECT ROWS WITH ALL NULL FIELDS
  )
  location (DIR_IN_DE_MKT:'DE_GEO_AGENCIAS.csv')
)
reject limit UNLIMITED;


-- =====================================================
-- Creacion de Tabla Staging de Distribución de Agencias
-- =====================================================
CREATE TABLE STG.T_DISTRIBUCION_AGENCIAS
(
  CODIGOAGENCIA        NUMBER(15),
  AGENCIA              VARCHAR2(150),
  TERRITORIO           VARCHAR2(150),
  REGION               VARCHAR2(150),
  OLA                  VARCHAR2(150),
  TIPOAG               VARCHAR2(150),
  TIPODEMOVILIDAD      VARCHAR2(150),
  CODAGENCIAACARGO     NUMBER(15),
  PERIODO              NUMBER(6),
  FE_ACTU_DIA          DATE
) TABLESPACE STG_DATA_01;

COMMENT ON TABLE STG.T_DISTRIBUCION_AGENCIAS IS 'TABLA DE DISTRIBUCION DE AGENCIAS.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.CODIGOAGENCIA    IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.AGENCIA          IS 'DESCRIPCION DE LA AGENCIA.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.TERRITORIO       IS 'DESCRIPCION DEL TERRITORIO.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.REGION           IS 'DESCRIPCION DE LA REGION.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.OLA              IS 'DESCRIPCION OLA DEL PROYECTO CLIENTE SOY.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.TIPOAG           IS 'DESCRIPCION DEL TIPO DE AGENCIA.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.TIPODEMOVILIDAD  IS 'DESCRIPCION DEL TIPO DE MOVILIDAD DE LOS CLIENTES ALREDEDOR DE AGENCIA Y QUE UTILIZAN PARA LLEGAR AL BANCO.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.CODAGENCIAACARGO IS 'CODIGO DE AGENCIA A LA QUE REPORTA.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.PERIODO          IS 'PERIODO DE PROCESO EN FORMATO YYYYMM.';
COMMENT ON COLUMN STG.T_DISTRIBUCION_AGENCIAS.FE_ACTU_DIA      IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';

-- ========================================================
-- Creacion de Tabla Staging de Geolocalización de Agencias
-- ========================================================
CREATE TABLE STG.T_GEO_AGENCIAS
(
  COD_AGEN             NUMBER(15),
  X                    VARCHAR2(50),
  Y                    VARCHAR2(50),
  FE_ACTU_DIA          DATE
) TABLESPACE STG_DATA_01;

COMMENT ON TABLE STG.T_GEO_AGENCIAS IS 'TABLA DE GEOLOCALIZACION DE AGENCIAS.';
COMMENT ON COLUMN STG.T_GEO_AGENCIAS.COD_AGEN    IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN STG.T_GEO_AGENCIAS.X           IS 'COORDENADA QUE REPRESENTA LA POSICION HORIZONTAL DE LA AGENCIA.';
COMMENT ON COLUMN STG.T_GEO_AGENCIAS.Y           IS 'COORDENADA QUE REPRESENTA LA POSICIÓN VERTICAL DE LA AGENCIA.';
COMMENT ON COLUMN STG.T_GEO_AGENCIAS.FE_ACTU_DIA IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';


-- =========================================
-- Creacion de Tabla ODS.HM_AGENCIA_NEGOCIOS
-- =========================================
CREATE TABLE ODS.HM_AGENCIA_NEGOCIOS
(
  NU_PERI_MES      NUMBER(6)     DEFAULT 0,
  CO_AGENCIA       NUMBER(15)    DEFAULT 0,
  DE_AGENCIA       VARCHAR2(150) DEFAULT '.',
  DE_TERRITORIO    VARCHAR2(150) DEFAULT '.',
  DE_REGION        VARCHAR2(150) DEFAULT '.',
  DE_OLA           VARCHAR2(150) DEFAULT '.',
  DE_TIPO_AGEN     VARCHAR2(150) DEFAULT '.',
  DE_TIPO_MOVI     VARCHAR2(150) DEFAULT '.',
  CO_AGEN_CARG     NUMBER(15)    DEFAULT 0,
  DE_ZONA          VARCHAR2(150) DEFAULT '.',
  FE_ACTU_MES      DATE          DEFAULT SYSDATE,
  CO_ACTU_USER     VARCHAR2(50)  DEFAULT USER,
  NU_CARGA         INTEGER,
  IN_ESTA_REGI     INTEGER       DEFAULT 0
) 
PARTITION BY RANGE (NU_PERI_MES)
(
 PARTITION P_HM_AGENCIA_NEGOCIOS_201601 VALUES LESS THAN (201602)   TABLESPACE ODS_DATA_01,
 PARTITION P_HM_AGENCIA_NEGOCIOS_MAX    VALUES LESS THAN (MAXVALUE) TABLESPACE ODS_DATA_01
);

COMMENT ON TABLE ODS.HM_AGENCIA_NEGOCIOS IS 'TABLA DE AGENCIAS.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.NU_PERI_MES    IS 'PERIODO CORRESPONDIENTE A LA DISTRIBUCION DE AGENCIAS EN FORMATO YYYYMM.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.CO_AGENCIA     IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.DE_AGENCIA     IS 'DESCRIPCION DE LA AGENCIA.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.DE_TERRITORIO  IS 'DESCRIPCION DEL TERRITORIO.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.DE_REGION      IS 'DESCRIPCION DE LA REGION.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.DE_OLA         IS 'DESCRIPCION OLA DEL PROYECTO CLIENTE SOY.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.DE_TIPO_AGEN   IS 'DESCRIPCION DEL TIPO DE AGENCIA.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.DE_TIPO_MOVI   IS 'DESCRIPCION DEL TIPO DE MOVILIDAD DE LOS CLIENTES ALREDEDOR DE AGENCIA Y QUE UTILIZAN PARA LLEGAR AL BANCO.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.CO_AGEN_CARG   IS 'CODIGO DE AGENCIA A LA QUE REPORTA.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.DE_ZONA        IS 'DESCRIPCION DE LA ZONA.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.FE_ACTU_MES    IS 'FECHA DE ACTUALIZACION MENSUAL DE LA TABLA.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.CO_ACTU_USER   IS 'USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.NU_CARGA       IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.HM_AGENCIA_NEGOCIOS.IN_ESTA_REGI   IS 'ESTADO DEL REGISTRO.';


-- ================================================
-- Creacion de Tabla ODS.MD_GEOLOCALIZACION_AGENCIA
-- ================================================
CREATE TABLE ODS.MD_GEOLOCALIZACION_AGENCIA
(
  CO_AGENCIA       NUMBER(15)    DEFAULT 0,
  DE_LONGITUD      VARCHAR2(50)  DEFAULT '.',
  DE_LATITUD       VARCHAR2(50)  DEFAULT '.',
  FE_ACTU_DIA      DATE          DEFAULT SYSDATE,
  CO_ACTU_USER     VARCHAR2(50)  DEFAULT USER,
  NU_CARGA         INTEGER,
  IN_ESTA_REGI     INTEGER       DEFAULT 0
) TABLESPACE ODS_DATA_01;

COMMENT ON TABLE ODS.MD_GEOLOCALIZACION_AGENCIA IS 'TABLA DE AGENCIAS.';
COMMENT ON COLUMN ODS.MD_GEOLOCALIZACION_AGENCIA.CO_AGENCIA     IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN ODS.MD_GEOLOCALIZACION_AGENCIA.DE_LONGITUD    IS 'COORDENADA QUE REPRESENTA LA POSICION HORIZONTAL DE LA AGENCIA.';
COMMENT ON COLUMN ODS.MD_GEOLOCALIZACION_AGENCIA.DE_LATITUD     IS 'COORDENADA QUE REPRESENTA LA POSICION VERTICAL DE LA AGENCIA.';
COMMENT ON COLUMN ODS.MD_GEOLOCALIZACION_AGENCIA.FE_ACTU_DIA    IS 'FECHA DE ACTUALIZACION DIARIA DE LA TABLA.';
COMMENT ON COLUMN ODS.MD_GEOLOCALIZACION_AGENCIA.CO_ACTU_USER   IS 'USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.MD_GEOLOCALIZACION_AGENCIA.NU_CARGA       IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.MD_GEOLOCALIZACION_AGENCIA.IN_ESTA_REGI   IS 'ESTADO DEL REGISTRO.';


-- ============================================
-- Creacion de Tabla BDS.D_GEN_AGENCIA_NEGOCIOS
-- ============================================
CREATE TABLE BDS.D_GEN_AGENCIA_NEGOCIOS
(
  NU_PERI_MES      NUMBER(6)     DEFAULT 0,
  CO_AGENCIA       NUMBER(15)    DEFAULT 0,
  DE_AGENCIA       VARCHAR2(150) DEFAULT '.',
  DE_TERRITORIO    VARCHAR2(150) DEFAULT '.',
  DE_REGION        VARCHAR2(150) DEFAULT '.',
  DE_OLA           VARCHAR2(150) DEFAULT '.',
  DE_TIPO_AGEN     VARCHAR2(150) DEFAULT '.',
  DE_TIPO_MOVI     VARCHAR2(150) DEFAULT '.',
  CO_AGEN_CARG     NUMBER(15)    DEFAULT 0,
  DE_ZONA          VARCHAR2(150) DEFAULT '.',
  DE_LONGITUD      VARCHAR2(50)  DEFAULT '.',
  DE_LATITUD       VARCHAR2(50)  DEFAULT '.',
  FE_ACTU_MES      DATE          DEFAULT SYSDATE,
  CO_ACTU_USER     VARCHAR2(50)  DEFAULT USER,
  NU_CARGA         INTEGER,
  IN_ESTA_REGI     INTEGER       DEFAULT 0
) 
PARTITION BY RANGE (NU_PERI_MES)
(
 PARTITION P_GEN_AGENCIA_NEGOCIOS_201601 VALUES LESS THAN (201602)   TABLESPACE BDS_DATA_01,
 PARTITION P_GEN_AGENCIA_NEGOCIOS_MAX    VALUES LESS THAN (MAXVALUE) TABLESPACE BDS_DATA_01
);

COMMENT ON TABLE BDS.D_GEN_AGENCIA_NEGOCIOS IS 'TABLA DIMENSION GENERICA DE AGENCIAS.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.NU_PERI_MES    IS 'PERIODO CORRESPONDIENTE A LA DISTRIBUCION DE AGENCIAS EN FORMATO YYYYMM.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.CO_AGENCIA     IS 'CODIGO DE AGENCIA.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.DE_AGENCIA     IS 'DESCRIPCION DE LA AGENCIA.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.DE_TERRITORIO  IS 'DESCRIPCION DEL TERRITORIO.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.DE_REGION      IS 'DESCRIPCION DE LA REGION.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.DE_OLA         IS 'DESCRIPCION OLA DEL PROYECTO CLIENTE SOY.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.DE_TIPO_AGEN   IS 'DESCRIPCION DEL TIPO DE AGENCIA.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.DE_TIPO_MOVI   IS 'TIPO DE MOVILIDAD DE LOS CLIENTES ALREDEDOR DE AGENCIA Y QUE UTILIZAN PARA LLEGAR AL BANCO.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.CO_AGEN_CARG   IS 'CODIGO DE AGENCIA A LA QUE REPORTA.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.DE_ZONA        IS 'DESCRIPCION DE LA ZONA.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.DE_LONGITUD    IS 'COORDENADA QUE REPRESENTA LA POSICION HORIZONTAL DE LA AGENCIA.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.DE_LATITUD     IS 'COORDENADA QUE REPRESENTA LA POSICIÓN VERTICAL DE LA AGENCIA.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.FE_ACTU_MES    IS 'FECHA DE ACTUALIZACION MENSUAL DE LA TABLA.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.CO_ACTU_USER   IS 'USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.NU_CARGA       IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN BDS.D_GEN_AGENCIA_NEGOCIOS.IN_ESTA_REGI   IS 'ESTADO DEL REGISTRO.';