
--BROAD STG
--===============

CREATE TABLE STG.T_SALDOS_CONTA
(
  CUENTA        NUMBER(15) 		DEFAULT (0),
  MONEDA        NUMBER(5) 		DEFAULT (0),
  SUCURSAL      NUMBER(5) 		DEFAULT (0),
  PRODUCTO      NUMBER(5) 		DEFAULT (0),
  JTS_OID       NUMBER(15) 		DEFAULT (0),
  C1803         NUMBER(15) 		DEFAULT (0),  
  C1670         NUMBER(5) 		DEFAULT (0),
  C9314         NUMBER(1)		DEFAULT (0),  
  C7294         NUMBER(15,2) 	DEFAULT (0),
  TZ_LOCK		NUMBER(15) 		DEFAULT 0,
  FE_ACTU_DIA   DATE 			DEFAULT SYSDATE,
  CO_ACTU_USER  VARCHAR2(50)	DEFAULT '.',
  NU_CARGA      INT				DEFAULT 0,
  IN_ESTA_REG   INT				DEFAULT 0
)
NOLOGGING TABLESPACE STG_DATA_01
  PCTFREE 0
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 160K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );
COMMENT ON TABLE  STG.T_SALDOS_CONTA  				IS 'TABLA SALDOS DE TOPAZ CON INFORMACION DE AHORROS Y CREDITOS REDUCIDO';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.CUENTA  		IS 'CUENTA.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.MONEDA    		IS 'MONEDA.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.SUCURSAL 		IS 'SUCURSAL.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.PRODUCTO 		IS 'PRODUCTO.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.JTS_OID  		IS 'JTS_OID.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.C1803    		IS 'CLIENTE.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.C1670  		IS 'ANALISTA.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.C9314  		IS 'TIPO DE PRODUCTO.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.C7294  		IS 'MONTO RESERVA DE NEGOCIO.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.TZ_LOCK 	 	IS 'INDICADOR DE ESTADO DE REGISTRO.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.FE_ACTU_DIA 	IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.CO_ACTU_USER 	IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.NU_CARGA  		IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN STG.T_SALDOS_CONTA.IN_ESTA_REG	IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE STG.T_CASIENTOMANUAL
(
  TZ_LOCK       NUMBER(15)		DEFAULT 0,
  C5558         DATE,
  C5559         DATE,
  C5560         VARCHAR2(8)		DEFAULT '.',
  C5561         VARCHAR2(8)		DEFAULT '.',
  C5562         NUMBER(12,2)	DEFAULT 0,
  C5563         VARCHAR2(50)	DEFAULT '.',
  C5564         VARCHAR2(1)		DEFAULT '.',
  C5565         FLOAT			DEFAULT 0,
  MONEDA        NUMBER(5)		DEFAULT 0,
  IDASIENTO     NUMBER(15)		DEFAULT 0,
  EXTENDIDO     VARCHAR2(1)		DEFAULT '.',
  SISTEMA       VARCHAR2(10)	DEFAULT '.',
  ASIENTO       NUMBER(10)		DEFAULT 0,
  FE_ACTU_DIA   DATE 			DEFAULT SYSDATE,
  CO_ACTU_USER  VARCHAR2(50)	DEFAULT '.',
  NU_CARGA      INT				DEFAULT 0,
  IN_ESTA_REG   INT				DEFAULT 0
)
NOLOGGING TABLESPACE STG_DATA_01
  PCTFREE 0
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 160K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

COMMENT ON TABLE  STG.T_CASIENTOMANUAL				IS 'TABLA CON INFORMACION DE LOS ASIENTOS MANUALES DE TOPAZ';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.TZ_LOCK      IS 'INDICADOR DE ESTADO DEL REGISTRO';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.C5558        IS 'FECHA DE INGRESO';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.C5559        IS 'FECHA DE PROCESO';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.C5560        IS 'USUARIO DE INGRESO';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.C5561        IS 'USUARIO AUTORIZADOR';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.C5562        IS 'IMPORTE TOTAL';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.C5563        IS 'DETALLE';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.C5564        IS 'ESTADO';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.C5565        IS 'NUMERADOR';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.MONEDA       IS 'CODIGO DE MONEDA DEL REGISTRO';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.IDASIENTO    IS 'NUMERO DE ASIENTO DEL SISTEMA ORIGEN';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.EXTENDIDO    IS 'EXTENDIDO';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.SISTEMA      IS 'INDICA SISTEMA ORIGEN DEL REGISTRO';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.ASIENTO      IS 'NUMERO DE ASIENTO GENERADO EN TOPAZ';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.FE_ACTU_DIA  IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.CO_ACTU_USER IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.NU_CARGA     IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN STG.T_CASIENTOMANUAL.IN_ESTA_REG  IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE STG.T_BS_HISTORIA_PLAZO_CONTA
(
  TZ_LOCK                NUMBER(15)		DEFAULT 0,
  RUBROCONTABLE          NUMBER(15)		DEFAULT 0,
  SUCURSALMOV            NUMBER(8)		DEFAULT 0,
  FECHAPROCESOMOV        DATE,
  NROASIENTOMOV          NUMBER(8)		DEFAULT 0,
  NUMEROMOV              NUMBER(8)		DEFAULT 0,
  PRODUCTO               NUMBER(5)		DEFAULT 0,
  FECHAVALOR             DATE,
  CAPITALORIGINAL        NUMBER(15,2)	DEFAULT 0,
  CANTIDADCUOTAS         NUMBER(4)		DEFAULT 0,
  DIVISOR                NUMBER(4)		DEFAULT 0,
  PERIODO                NUMBER(4)		DEFAULT 0,
  TASAINTERES            FLOAT			DEFAULT 0,
  CAPITALPAGADO          NUMBER(15,2)	DEFAULT 0,
  INTERESPAGADO          NUMBER(15,2)	DEFAULT 0,
  TIPOMOV                VARCHAR2(1)	DEFAULT '.',
  MONTOORIG              NUMBER(15,2)	DEFAULT 0,
  FECHAVTOFINAL          DATE,
  MORAPAGADA             NUMBER(19,4)	DEFAULT 0,
  FECHASALDO             DATE,
  FECHAPRIMERVTO         DATE,
  CUOTA                  NUMBER(15,2)	DEFAULT 0,
  TASAMORA               FLOAT,
  TASACOMISION           FLOAT,
  TIPOPRESTAMO           VARCHAR2(1)	DEFAULT '.',
  TIPOAJUSTE             VARCHAR2(1)	DEFAULT '.',
  BONIFICACION           NUMBER(15,2)	DEFAULT 0,
  SIGNO                  VARCHAR2(1)	DEFAULT '.',
  COMISIONPAGADA         NUMBER(15,2)	DEFAULT 0,
  IMPUESTOPAGADO         NUMBER(15,2)	DEFAULT 0,
  CAPITALADELANTADO      NUMBER(15,2)	DEFAULT 0,
  INTERESRECALCULADO     NUMBER(15,2)	DEFAULT 0,
  INTERESESPECIAL        NUMBER(15,2)	DEFAULT 0,
  SALDOS_JTS_OID         NUMBER(10)		DEFAULT 0,
  JTS_OID                NUMBER(10) 	DEFAULT 0 NOT NULL,
  RUBROANTERIOR          NUMBER(15)		DEFAULT 0,
  ALGORITMO              NUMBER(2)		DEFAULT 0,
  CUOTABALONO            NUMBER(4)      DEFAULT (0) NOT NULL,
  CUOTABALOND            NUMBER(4)      DEFAULT (0) NOT NULL,
  GASTOBONIFICADO        NUMBER(15,2)   DEFAULT (0) NOT NULL,
  CUOTANOBON             NUMBER(5)      DEFAULT (0),
  GASTOS_RECALCULADOS    NUMBER(15,2)   DEFAULT (0) NOT NULL,
  GASTOS_PAGADOS         NUMBER(15,2)   DEFAULT (0) NOT NULL,
  DIADEPAGO              NUMBER(2)      DEFAULT (0),
  EQUIVALENTEMN          NUMBER(15,2)	DEFAULT 0,
  C9379                  NUMBER(19,4)	DEFAULT 0,
  C1243                  NUMBER(12)     DEFAULT (0),
  C9179                  NUMBER(1)      DEFAULT (0) NOT NULL,
  ICMORA_PAGADO          NUMBER(15,2)   DEFAULT (0),
  TASA_ICMORA            NUMBER(11,7)   DEFAULT (0),
  ICMORA_DEV_ENTREGADO   NUMBER(15,2)   DEFAULT (0),
  ID_HISTORICO_TARIFARIO NUMBER(15)		DEFAULT 0,
  CONDONACION            VARCHAR2(1)    DEFAULT ('N') NOT NULL,
  FE_ACTU_DIA            DATE           DEFAULT SYSDATE,
  CO_ACTU_USER           VARCHAR2(50)	DEFAULT '.',
  NU_CARGA               INT			DEFAULT 0,
  IN_ESTA_REG            INT			DEFAULT 0
)
NOLOGGING TABLESPACE STG_DATA_01
  PCTFREE 0
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 160K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

COMMENT ON TABLE  STG.T_BS_HISTORIA_PLAZO_CONTA							  IS 'TABLA HISTORICA CON INFORMACION DE LOS MOVIMIENTOS DE PRESTAMOS';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.TZ_LOCK                   IS 'INDICADOR DE ESTADO DEL REGISTRO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.RUBROCONTABLE             IS 'RUBRO CONTABLE DEL SALDO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.SUCURSALMOV               IS 'SUCURSAL DEL MOVIMIENTO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.FECHAPROCESOMOV           IS 'FECHA DE PROCESO MOVIMIENTO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.NROASIENTOMOV             IS 'NUMERO DE ASIENTO MOVIMIENTO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.NUMEROMOV                 IS 'NUMERO DE MOVIMIENTO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.PRODUCTO                  IS 'PRODUCTO DE SALDO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.FECHAVALOR                IS 'FECHA VALOR';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CAPITALORIGINAL           IS 'CAPITAL ORIGINAL';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CANTIDADCUOTAS            IS 'CANTIDAD DE CUOTAS';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.DIVISOR                   IS 'DIVISOR';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.PERIODO                   IS 'PERIODO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.TASAINTERES               IS 'TASA DE INTERES';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CAPITALPAGADO             IS 'CAPITAL PAGADO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.INTERESPAGADO             IS 'INTERES PAGADO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.TIPOMOV                   IS 'TIPO DE MOVIMIENTO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.MONTOORIG                 IS 'MONTO ORIGINAL';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.FECHAVTOFINAL             IS 'FECHA VENCIMIENTO FINAL';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.MORAPAGADA                IS 'MORA PAGADA';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.FECHASALDO                IS 'FECHA DEL SALDO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.FECHAPRIMERVTO            IS 'FECHA PRIMER VTO.';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CUOTA                     IS 'CUOTA';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.TASAMORA                  IS 'TASA MORA';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.TASACOMISION              IS 'TASA COMISION';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.TIPOPRESTAMO              IS 'TIPO PRESTAMO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.TIPOAJUSTE                IS 'TIPO AJUSTE';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.BONIFICACION              IS 'BONIFICACION';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.SIGNO                     IS 'SIGNO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.COMISIONPAGADA            IS 'COMISION PAGADA';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.IMPUESTOPAGADO            IS 'IMPUESTO PAGADO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CAPITALADELANTADO         IS 'CAPITAL ADELANTADO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.INTERESRECALCULADO        IS 'INTERES RECALCULADO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.INTERESESPECIAL           IS 'INTERES ESPECIAL';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.SALDOS_JTS_OID            IS 'CAMPO DE RELACION CON EL SALDO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.JTS_OID                   IS 'ID JTS';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.RUBROANTERIOR             IS 'RUBRO CONTABLE ANTERIOR';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.ALGORITMO                 IS 'ALGORITMO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CUOTABALONO               IS 'CUOTA BALON ORIGEN';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CUOTABALOND               IS 'CUOTA BALON DESTINO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.GASTOBONIFICADO           IS 'GASTO BONIFICADO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CUOTANOBON                IS 'CUOTAS NO  BONIFICAR';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.GASTOS_RECALCULADOS       IS 'GASTOS RECALCULADOS';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.GASTOS_PAGADOS            IS 'GASTOS PAGADOS';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.DIADEPAGO                 IS 'DIA DE PAGO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.EQUIVALENTEMN             IS 'EQUIVALENTE EN MONEDA NACIONAL';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.C9379                     IS 'MORA DEVENGADA ENTREGADA';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.C1243                     IS 'CONTRA CUENTA';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.C9179                     IS 'APLICA ECUACION FINANCIERA';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.ICMORA_PAGADO             IS 'INT.COMP.MORA PAGADO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.TASA_ICMORA               IS 'TASA INT.COMP.MORA';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.ICMORA_DEV_ENTREGADO      IS 'INT.COMP.MORA DEVENGADO ENTREGADO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.ID_HISTORICO_TARIFARIO    IS 'CODIGO HIST. TARIFARIO';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CONDONACION               IS 'CONDONACION';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.FE_ACTU_DIA               IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.CO_ACTU_USER              IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.NU_CARGA                  IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN STG.T_BS_HISTORIA_PLAZO_CONTA.IN_ESTA_REG               IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


-- TRADER
--===============


CREATE TABLE STG.BR_TDL_0001_CONTROL_DWH
(
  FE_PROCESO      NUMBER(8),
  TI_DATOS        VARCHAR2(1),
  NO_APLICACION   VARCHAR2(3),
  NO_RUTINA       VARCHAR2(150),
  NO_PROCESO      VARCHAR2(60),
  NU_REGISTROS    NUMBER(15),
  FE_SISTEMA      NUMBER(8),
  HO_SISTEMA      VARCHAR2(8),
  ST_PROCESO      VARCHAR2(1)
)
ORGANIZATION EXTERNAL
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY DIR_IN_TRADER
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    BADFILE '%a_%p.bad'
    LOGFILE '%a_%p.log'
    NOLOGFILE
    FIELDS TERMINATED BY '|' LRTRIM
    MISSING FIELD VALUES ARE NULL
    REJECT ROWS WITH ALL NULL FIELDS
  )
  location (DIR_IN_TRADER:'TDL_0001_CONTROL_DWH.ctrl')
)
reject limit UNLIMITED; 

---

CREATE TABLE STG.T_TDL_0001_CONTROL_DWH
(
  FE_PROCESO    NUMBER(8),
  TI_DATOS      VARCHAR2(1),
  NO_APLICACION VARCHAR2(3),
  NO_RUTINA     VARCHAR2(150),
  NO_PROCESO    VARCHAR2(60),
  NU_REGISTROS  NUMBER(15),
  FE_SISTEMA    NUMBER(8),
  HO_SISTEMA    VARCHAR2(8),
  ST_PROCESO    VARCHAR2(1),
  FE_ACTU_DIA   DATE          DEFAULT SYSDATE,
  CO_ACTU_USER  VARCHAR2(50)  DEFAULT '.',
  NU_CARGA      INTEGER       DEFAULT 0,
  IN_ESTA_REG   INTEGER       DEFAULT 0
)
TABLESPACE STG_DATA_01 NOLOGGING;


---


CREATE TABLE STG.BR_TDL_0001_TRAMA_DWH
(
  COCTACONTABLE        NUMBER(30),
  FEREGCONTABLE        NUMBER(8),
  FEVALOROPERACION     NUMBER(8),
  COCLIENTETRADER      NUMBER(15),
  COCLIENTETOPAZ       NUMBER(15),
  COCARTERA            NUMBER(15),
  NOCARTERA            VARCHAR2(150),
  NUDOCUMENTO          NUMBER(15),
  NUDOCORIGEN          NUMBER(15),
  NUASIENTO            NUMBER(10),
  COMONEDA             NUMBER(5),
  COPRODUCTO           NUMBER(5),
  NOPRODUCTO           VARCHAR2(150),
  CORUBROCONTABLE      NUMBER(4),
  TICARGOABONO         VARCHAR2(1),
  MOCONTABLE           NUMBER(15,2),
  COOPETRANSAC         VARCHAR2(30),
  NOOPETRANSAC         VARCHAR2(150),
  COAGENCIAOPERACION   NUMBER(5),
  COASESORNEGOCIO      VARCHAR2(20),
  NOASESORNEGOCIO      VARCHAR2(150),
  COOPERACION          VARCHAR2(15),
  FERUTINAHOST         NUMBER(8),
  FEACTUALIZACIONTABLA NUMBER(8)
)
ORGANIZATION EXTERNAL
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY DIR_IN_TRADER
  ACCESS PARAMETERS 
  (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    BADFILE '%a_%p.bad'
    LOGFILE '%a_%p.log'
    NOLOGFILE
    FIELDS TERMINATED BY '|' LRTRIM
    MISSING FIELD VALUES ARE NULL
    REJECT ROWS WITH ALL NULL FIELDS
  )
  location (DIR_IN_TRADER:'TDL_0001_TRAMA_DWH.csv')
)
reject limit UNLIMITED;


---


CREATE TABLE STG.T_CONTABLE_TRADER
(
  COCTACONTABLE        NUMBER(30),
  FEREGCONTABLE        NUMBER(8),
  FEVALOROPERACION     NUMBER(8),
  COCLIENTETRADER      NUMBER(15),
  COCLIENTETOPAZ       NUMBER(15),
  COCARTERA            NUMBER(15),
  NOCARTERA            VARCHAR2(150),
  NUDOCUMENTO          NUMBER(15),
  NUDOCORIGEN          NUMBER(15),
  NUASIENTO            NUMBER(10),
  COMONEDA             NUMBER(5),
  COPRODUCTO           NUMBER(5),
  NOPRODUCTO           VARCHAR2(150),
  CORUBROCONTABLE      NUMBER(4),
  TICARGOABONO         VARCHAR2(1),
  MOCONTABLE           NUMBER(15,2),
  COOPETRANSAC         VARCHAR2(30),
  NOOPETRANSAC         VARCHAR2(150),
  COAGENCIAOPERACION   NUMBER(5),
  COASESORNEGOCIO      VARCHAR2(20),
  NOASESORNEGOCIO      VARCHAR2(150),
  COOPERACION          VARCHAR2(15),
  FERUTINAHOST         NUMBER(8),
  FEACTUALIZACIONTABLA NUMBER(8),
  FE_ACTU_DIA          DATE             DEFAULT SYSDATE,
  CO_ACTU_USER         VARCHAR2(50)     DEFAULT '.',
  NU_CARGA             INTEGER          DEFAULT 0,
  IN_ESTA_REG          INTEGER          DEFAULT 0
)
TABLESPACE STG_DATA_01 NOLOGGING;

COMMENT ON TABLE  STG.T_CONTABLE_TRADER						   IS 'TABLA TEMPORAL DEL DATA ENTRY STG.BR_TDL_0001_TRAMA_DWH CON INFORMACION DE MOVIMIENTOS DE TRADER';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COCTACONTABLE          IS 'NUMERO DE CUENTA CONTABLE.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.FEREGCONTABLE          IS 'FECHA DE REGISTRO CONTABLE EN TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.FEVALOROPERACION       IS 'FECHA VALOR DE LA OPERACION DE TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COCLIENTETRADER        IS 'CODIGO DEL CLIENTE TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COCLIENTETOPAZ         IS 'CODIGO DEL CLIENTE TOPAZ.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COCARTERA              IS 'CODIGO DE CARTERA TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.NOCARTERA              IS 'DESCRIPCION DE LA CARTERA.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.NUDOCUMENTO            IS 'NUMERO DE TRANSACCION DE LA LINEA DE TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.NUDOCORIGEN            IS 'NUMERO DE TRANSACCION ORIGEN HACE REFERENCIA SI SE ORIGINA DE UNA TRANSACCION ANTERIOR.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.NUASIENTO              IS 'NUMERO DE ASIENTO ASOCIADO AL PAGO.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COMONEDA               IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COPRODUCTO             IS 'CODIGO DE PRODUCTO ES PROPIO DE TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.NOPRODUCTO             IS 'DESCRIPCION DEL PRODUCTO.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.CORUBROCONTABLE        IS 'CODIGO DEL RUBRO DE CUENTA CONTABLE.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.TICARGOABONO           IS 'TIPO DE CARGO DE ABONO (H/D).';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.MOCONTABLE             IS 'MONTO CONTABLE.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COOPETRANSAC           IS 'CODIGO DE TRANSACCION DE TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.NOOPETRANSAC           IS 'DESCRIPCION DE TRANSACCION DE TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COAGENCIAOPERACION     IS 'CODIGO DE SUCURSAL.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COASESORNEGOCIO        IS 'CODIGO DEL ANALISTA DE NEGOCIO DE TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.NOASESORNEGOCIO        IS 'NOMBRE DEL ANALISTA DE TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.COOPERACION            IS 'CODIGO DE OPERACION PROPIO DE TRADER. ES LA NOMENCLATURA QUE MANEJA LA MESA DE DINERO PARA LOS INSTRUMENTOS QUE OPERAN.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.FERUTINAHOST           IS 'FECHA DE PROCESO DEL ARCHIVO TRADER.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.FEACTUALIZACIONTABLA   IS 'FECHA CONTABLE INFORMADA DE TRADER (FECHA DEL LOTE ENVIADO)';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.FE_ACTU_DIA            IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.CO_ACTU_USER           IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.NU_CARGA               IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN STG.T_CONTABLE_TRADER.IN_ESTA_REG            IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE ODS.TD_CONTABLE_TRADER
(
  NU_PERI_MES       NUMBER(6)     DEFAULT 0,
  FE_PROCESO        DATE,
  NU_CUEN_CONT      NUMBER(30)    DEFAULT 0,
  CO_RUBR_CUEN_CONT NUMBER(4)     DEFAULT 0, 
  FE_MOVIMIENTO      DATE,
  FE_VALOR          DATE, 
  CO_CLIE_TRAD      NUMBER(15)    DEFAULT 0,
  CO_CLIENTE        NUMBER(15)    DEFAULT 0,
  CO_CARTERA        NUMBER(15)    DEFAULT 0,
  DE_CARTERA        VARCHAR2(150) DEFAULT '.',
  NU_TRANSACCION    NUMBER(15)    DEFAULT 0,
  NU_TRAN_ORIG      NUMBER(15)    DEFAULT 0,
  NU_ASIENTO        NUMBER(10)    DEFAULT 0, 
  CO_MONEDA         NUMBER(5)     DEFAULT 0,
  CO_PRODUCTO       NUMBER(5)     DEFAULT 0, 
  DE_PRODUCTO       VARCHAR2(150) DEFAULT '.',
  CO_SUCURSAL       NUMBER(5)     DEFAULT 0, 
  CO_ANAL_TRAD      NUMBER(20)    DEFAULT 0,
  CO_ANAL_TRAD_ORIG VARCHAR2(20)  DEFAULT '.',
  NO_ANAL_TRAD      VARCHAR2(150) DEFAULT '.',
  CO_OPER_TRAD      VARCHAR2(15)  DEFAULT '.',
  CO_TRAN_TRAD      VARCHAR2(30)  DEFAULT '.', 
  DE_TRAN_TRAD      VARCHAR2(150) DEFAULT '.', 
  TI_SIGNO		    VARCHAR2(1)   DEFAULT '.',
  MO_CONTABLE       NUMBER(15,2)  DEFAULT 0, 
  IN_ESTA_PROD      NUMBER(1)     DEFAULT 0,
  FE_PROC_TRAD      DATE,
  FE_CONT_TRAD      DATE, 
  FE_ACTU_DIA       DATE          DEFAULT SYSDATE,
  CO_ACTU_USER      VARCHAR2(50)  DEFAULT '.',
  NU_CARGA          INTEGER       DEFAULT 0, 
  IN_ESTA_REG       INTEGER       DEFAULT 0
)
TABLESPACE ODS_DATA_01 NOLOGGING;

COMMENT ON TABLE  ODS.TD_CONTABLE_TRADER			   		IS 'TABLA TEMPORAL DIARIA CON LOS MOVIMIENTOS DE TRADER'; 
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.NU_PERI_MES        IS 'NUMERO DE PERIODO. SE GENERA A PARTIR DEL AÑO Y MES DE LA FECHA EXTRACCION EN FORMATO YYYYMM.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.FE_PROCESO         IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_RUBR_CUEN_CONT  IS 'CODIGO DEL RUBRO DE CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_CLIE_TRAD       IS 'CODIGO DEL CLIENTE TRADER.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_CLIENTE         IS 'CODIGO DEL CLIENTE.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_MONEDA          IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_PRODUCTO        IS 'CODIGO DE PRODUCTO ES PROPIO DE TRADER.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_SUCURSAL        IS 'CODIGO DE SUCURSAL.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_CARTERA         IS 'CODIGO DE CARTERA TRADER.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_TRAN_TRAD       IS 'CODIGO DE TRANSACCION DE TRADER.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_ANAL_TRAD       IS 'CODIGO DEL ANALISTA DE NEGOCIO DE TRADER, SOLO SE CARGA CUANDO ES NUMERICO.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_ANAL_TRAD_ORIG  IS 'CODIGO EL ANALISTA DE NEGOCIO TRADER TAL CUAL APARECE DEL ARCHIVO DE CARGA.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_OPER_TRAD       IS 'CODIGO DE OPERACION PROPIO DE TRADER. ES LA NOMENCLATURA QUE MANEJA LA MESA DE DINERO PARA LOS INSTRUMENTOS QUE OPERAN.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.NO_ANAL_TRAD       IS 'NOMBRE DEL ANALISTA DE TRADER.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.DE_PRODUCTO        IS 'DESCRIPCION DEL PRODUCTO.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.DE_CARTERA         IS 'DESCRIPCION DE LA CARTERA.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.DE_TRAN_TRAD       IS 'DESCRIPCION DE TRANSACCION DE TRADER.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.NU_CUEN_CONT       IS 'NUMERO DE CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.NU_TRANSACCION     IS 'NUMERO DE TRANSACCION DE LA LINEA DE TRADER.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.NU_TRAN_ORIG       IS 'NUMERO DE TRANSACCION ORIGEN HACE REFERENCIA SI SE ORIGINA DE UNA TRANSACCION ANTERIOR.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.NU_ASIENTO         IS 'NUMERO DE ASIENTO ASOCIADO AL PAGO.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.TI_SIGNO 		    IS 'TIPO DE OPERACION (H/D).';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.IN_ESTA_PROD       IS 'INDICADOR DEL ESTADO DE CARGA DEL PRODUCTO.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.FE_MOVIMIENTO      IS 'FECHA DE PROCESO DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.FE_VALOR           IS 'FECHA VALOR.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.FE_PROC_TRAD       IS 'FECHA DE PROCESO DEL APLICATIVO TRADER.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.FE_CONT_TRAD       IS 'FECHA CONTABLE INFORMADA DE TRADER (FECHA DEL LOTE ENVIADO).';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.MO_CONTABLE        IS 'MONTO CONTABLE.'; 
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.FE_ACTU_DIA        IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.CO_ACTU_USER       IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.NU_CARGA           IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.TD_CONTABLE_TRADER.IN_ESTA_REG        IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE ODS.HD_CONTABLE_TRADER
(
  NU_PERI_MES       NUMBER(6)     DEFAULT 0,
  FE_PROCESO        DATE,
  NU_CUEN_CONT      NUMBER(30)    DEFAULT 0,
  CO_RUBR_CUEN_CONT NUMBER(4)     DEFAULT 0, 
  FE_MOVIMIENTO      DATE,
  FE_VALOR          DATE, 
  CO_CLIE_TRAD      NUMBER(15)    DEFAULT 0,
  CO_CLIENTE        NUMBER(15)    DEFAULT 0,
  CO_CARTERA        NUMBER(15)    DEFAULT 0,
  DE_CARTERA        VARCHAR2(150) DEFAULT '.',
  NU_TRANSACCION    NUMBER(15)    DEFAULT 0,
  NU_TRAN_ORIG      NUMBER(15)    DEFAULT 0,
  NU_ASIENTO        NUMBER(10)    DEFAULT 0, 
  CO_MONEDA         NUMBER(5)     DEFAULT 0,
  CO_PRODUCTO       NUMBER(5)     DEFAULT 0, 
  DE_PRODUCTO       VARCHAR2(150) DEFAULT '.',
  CO_SUCURSAL       NUMBER(5)     DEFAULT 0, 
  CO_ANAL_TRAD      NUMBER(20)    DEFAULT 0,
  CO_ANAL_TRAD_ORIG VARCHAR2(20)  DEFAULT '.',
  NO_ANAL_TRAD      VARCHAR2(150) DEFAULT '.',
  CO_OPER_TRAD      VARCHAR2(15)  DEFAULT '.',
  CO_TRAN_TRAD      VARCHAR2(30)  DEFAULT '.', 
  DE_TRAN_TRAD      VARCHAR2(150) DEFAULT '.', 
  TI_SIGNO    	    VARCHAR2(1)   DEFAULT '.',
  MO_CONTABLE       NUMBER(15,2)  DEFAULT 0, 
  IN_ESTA_PROD      NUMBER(1)     DEFAULT 0,
  FE_PROC_TRAD      DATE,
  FE_CONT_TRAD      DATE, 
  FE_ACTU_DIA       DATE          DEFAULT SYSDATE,
  CO_ACTU_USER      VARCHAR2(50)  DEFAULT '.',
  NU_CARGA          INTEGER       DEFAULT 0, 
  IN_ESTA_REG       INTEGER       DEFAULT 0 
)
NOLOGGING TABLESPACE ODS_DATA_01 
PARTITION BY RANGE (FE_PROCESO)
(      
   PARTITION P_HD_CONTABLE_TRADER_20200101 VALUES LESS THAN (TO_DATE('2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) TABLESPACE ODS_DATA_01 NOLOGGING,
   PARTITION P_HD_CONTABLE_TRADER_MAX VALUES LESS THAN (MAXVALUE) TABLESPACE ODS_DATA_01 NOLOGGING
);

COMMENT ON TABLE  ODS.HD_CONTABLE_TRADER			   		IS 'TABLA HISTORICA DIARIA CON LOS MOVIMIENTOS DE TRADER'; 
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.NU_PERI_MES        IS 'NUMERO DE PERIODO. SE GENERA A PARTIR DEL AÑO Y MES DE LA FECHA EXTRACCION EN FORMATO YYYYMM.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.FE_PROCESO         IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_RUBR_CUEN_CONT  IS 'CODIGO DEL RUBRO DE CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_CLIE_TRAD       IS 'CODIGO DEL CLIENTE TRADER.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_CLIENTE         IS 'CODIGO DEL CLIENTE.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_MONEDA          IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_PRODUCTO        IS 'CODIGO DE PRODUCTO ES PROPIO DE TRADER.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_SUCURSAL        IS 'CODIGO DE SUCURSAL.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_CARTERA         IS 'CODIGO DE CARTERA TRADER.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_TRAN_TRAD       IS 'CODIGO DE TRANSACCION DE TRADER.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_ANAL_TRAD       IS 'CODIGO DEL ANALISTA DE NEGOCIO DE TRADER, SOLO SE CARGA CUANDO ES NUMERICO.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_ANAL_TRAD_ORIG  IS 'CODIGO EL ANALISTA DE NEGOCIO TRADER TAL CUAL APARECE DEL ARCHIVO DE CARGA.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_OPER_TRAD       IS 'CODIGO DE OPERACION PROPIO DE TRADER. ES LA NOMENCLATURA QUE MANEJA LA MESA DE DINERO PARA LOS INSTRUMENTOS QUE OPERAN.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.NO_ANAL_TRAD       IS 'NOMBRE DEL ANALISTA DE TRADER.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.DE_PRODUCTO        IS 'DESCRIPCION DEL PRODUCTO.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.DE_CARTERA         IS 'DESCRIPCION DE LA CARTERA.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.DE_TRAN_TRAD       IS 'DESCRIPCION DE TRANSACCION DE TRADER.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.NU_CUEN_CONT       IS 'NUMERO DE CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.NU_TRANSACCION     IS 'NUMERO DE TRANSACCION DE LA LINEA DE TRADER.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.NU_TRAN_ORIG       IS 'NUMERO DE TRANSACCION ORIGEN HACE REFERENCIA SI SE ORIGINA DE UNA TRANSACCION ANTERIOR.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.NU_ASIENTO         IS 'NUMERO DE ASIENTO ASOCIADO AL PAGO.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.TI_SIGNO		    IS 'TIPO DE OPERACION (H/D).';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.IN_ESTA_PROD       IS 'INDICADOR DEL ESTADO DE CARGA DEL PRODUCTO.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.FE_MOVIMIENTO      IS 'FECHA DE PROCESO DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.FE_VALOR           IS 'FECHA VALOR.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.FE_PROC_TRAD       IS 'FECHA DE PROCESO DEL ARCHIVO TRADER.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.FE_CONT_TRAD       IS 'FECHA CONTABLE INFORMADA DE TRADER (FECHA DEL LOTE ENVIADO).';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.MO_CONTABLE        IS 'MONTO CONTABLE.'; 
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.FE_ACTU_DIA        IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.CO_ACTU_USER       IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.NU_CARGA           IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.HD_CONTABLE_TRADER.IN_ESTA_REG        IS 'INDICADOR DEL ESTADO DEL REGISTRO.';



--BROAD ODS
--===============

CREATE TABLE ODS.TP_BROAD_ASIENTOS
(
  NU_PERI_MES   NUMBER(6)	DEFAULT 0,
  FE_MOVIMIENTO DATE,
  FE_VALOR      DATE,  
  CO_CLIENTE    NUMBER(15)	  DEFAULT 0,
  CO_MONEDA     NUMBER(5)	  DEFAULT 0,
  CO_PRODUCTO   NUMBER(5)	  DEFAULT 0,
  CO_SUCURSAL   NUMBER(15)	  DEFAULT 0,
  CO_SUCU_ORIG  NUMBER(15)	  DEFAULT 0,
  CO_OPERATIVA  NUMBER(5)	  DEFAULT 0,  
  NU_CUENTA     NUMBER(15)	  DEFAULT 0,
  NU_CUEN_CLIE  NUMBER(30)	  DEFAULT 0,  
  NU_CUEN_CONT  NUMBER(30)	  DEFAULT 0,  
  NU_ASIENTO    NUMBER(15)	  DEFAULT 0,  
  NU_TRREAL     NUMBER(5)	  DEFAULT 0,
  NU_ORDINAL    NUMBER(10)	  DEFAULT 0,
  NU_TRVIRTUAL  NUMBER(15)	  DEFAULT 0,
  NU_TRTIPO     NUMBER(5)	  DEFAULT 0,
  TI_MOVI_CONTA VARCHAR2(1)	  DEFAULT '.',  
  MO_IMPORTE    NUMBER(15,2)  DEFAULT 0,
  MO_IMPO_MN    NUMBER(15,2)  DEFAULT 0,  
  TI_SIGNO      VARCHAR2(1)	  DEFAULT '.',
  TI_AJUSTE     VARCHAR2(1)	  DEFAULT '.',
  DE_REFE_ASIE  VARCHAR2(500) DEFAULT '.',
  DE_ASIENTO    VARCHAR2(500) DEFAULT '.',
  FE_ACTU_DIA   DATE          DEFAULT SYSDATE,
  CO_ACTU_USER  VARCHAR2(50)  DEFAULT '.',
  NU_CARGA      INTEGER       DEFAULT 0,
  IN_ESTA_REG   INTEGER       DEFAULT 0
)
NOLOGGING TABLESPACE ODS_DATA_01
  PCTFREE 0
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 160K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
  );

COMMENT ON TABLE  ODS.TP_BROAD_ASIENTOS			   	   IS 'TABLA TEMPORAL DE PROCESO, CONTIENE LOS ASIENTOS A SER PROCESADOS PARA GENERAR LA BROAD DE FINANZAS'; 
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_PERI_MES    IS 'NUMERO DE PERIODO. SE GENERA A PARTIR DEL ANO Y MES DE LA FECHA EXTRACCION EN FORMATO YYYYMM.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.FE_MOVIMIENTO  IS 'FECHA DE PROCESO DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.FE_VALOR       IS 'FECHA VALOR.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.CO_CLIENTE     IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.CO_MONEDA      IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.CO_PRODUCTO    IS 'CODIGO DE PRODUCTO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.CO_SUCURSAL    IS 'CODIGO DE SUCURSAL ACTUAL.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.CO_SUCU_ORIG   IS 'CODIGO DE SUCURSAL ORIGEN.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.CO_OPERATIVA   IS 'CODIGO OPERATIVA.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_CUENTA      IS 'NUMERO DE CUENTA/PRESTAMO DEL CLIENTE O CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_CUEN_CLIE   IS 'NUMERO DE CUENTA/PRESTAMO DEL CLIENTE OBTENIDO DE LA DESCRIPCION DEL ASIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_CUEN_CONT   IS 'NUMERO DE CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_ASIENTO     IS 'NUMERO DE ASIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_TRREAL      IS 'NUMERO DE LA TRANSACCION REAL DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_ORDINAL     IS 'NUMERO ORDINAL DE SALDOS.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_TRVIRTUAL   IS 'NUMERO DE TRANSACCION VIRTUAL DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_TRTIPO      IS 'NUMERO DEL TIPO DE TRANSACCION DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.TI_MOVI_CONTA  IS 'TIPO DE MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.MO_IMPORTE     IS 'MONTO DE IMPORTE DE LA TRANSACCION.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.MO_IMPO_MN     IS 'MONTO DE IMPORTE DE LA TRANSACCION EN MONEDA NACIONAL.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.TI_SIGNO       IS 'TIPO DE OPERACION SI ES DEBITO/CREDITO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.TI_AJUSTE      IS 'TIPO DE AJUSTE DE FIN DE MES.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.DE_REFE_ASIE   IS 'DESCRIPCION DE LA REFERENCIA DEL ASIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.DE_ASIENTO     IS 'DESCRIPCION DEL ASIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.FE_ACTU_DIA    IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.CO_ACTU_USER   IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.NU_CARGA       IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_ASIENTOS.IN_ESTA_REG    IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE ODS.TP_BROAD_DETALLE
(
  ID_MOVIMIENTO     NUMBER(15)    DEFAULT 0,
  FE_MOVIMIENTO     DATE,
  FE_VALOR          DATE,
  CO_CLIENTE        NUMBER(15)    DEFAULT 0,
  CO_MONEDA         NUMBER(5)     DEFAULT 0,
  CO_PRODUCTO       NUMBER(5)     DEFAULT 0,
  CO_SUCURSAL       NUMBER(15)    DEFAULT 0,
  CO_OPERATIVA      NUMBER(5)     DEFAULT 0,
  CO_ANALISTA       NUMBER(8)     DEFAULT 0,
  CO_RUBR_CUEN_CONT NUMBER(4)     DEFAULT 0,
  NU_CUENTA         NUMBER(15)    DEFAULT 0,
  NU_CUEN_CONT      NUMBER(30)    DEFAULT 0,
  NU_ASIENTO        NUMBER(15)    DEFAULT 0,  
  NU_TRREAL         NUMBER(5)     DEFAULT 0,
  NU_ORDINAL        NUMBER(10)    DEFAULT 0,
  NU_TRVIRTUAL      NUMBER(15)    DEFAULT 0,
  NU_TRTIPO         NUMBER(5)     DEFAULT 0,    
  TI_MOVI_CONTA     VARCHAR2(1)   DEFAULT '.',
  TI_APLICACION     VARCHAR2(15)  DEFAULT '.',
  TI_CLAS_CUEN_CONT VARCHAR2(15)  DEFAULT '.',
  MO_IMPORTE        NUMBER(15,2)  DEFAULT 0,
  MO_IMPO_MN        NUMBER(15,2)  DEFAULT 0,  
  TI_SIGNO          VARCHAR2(1)   DEFAULT '.',  
  TI_AJUSTE         VARCHAR2(1)   DEFAULT '.',  
  DE_REFE_ASIE      VARCHAR2(500) DEFAULT '.',
  DE_ASIENTO        VARCHAR2(500) DEFAULT '.',    
  FE_ACTU_DIA       DATE          DEFAULT SYSDATE,
  CO_ACTU_USER      VARCHAR2(50)  DEFAULT '.',
  NU_CARGA          INTEGER       DEFAULT 0,
  IN_ESTA_REG       INTEGER       DEFAULT 0  
)
NOLOGGING TABLESPACE ODS_DATA_01 
PCTFREE 0
  INITRANS 1
  MAXTRANS 255
  STORAGE
  (
    INITIAL 160K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
);

COMMENT ON TABLE  ODS.TP_BROAD_DETALLE			   	   	  IS 'TABLA TEMPORAL DE PROCESO, CONTIENE EL CRUCE CON LA TABLA HD_DETALLE_CONTABILIDAD PARA OBTENER EL DETALLE OPERATIVO DE LOS ASIENTOS'; 
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.ID_MOVIMIENTO      IS 'IDENTIFICADOR DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.FE_MOVIMIENTO      IS 'FECHA DE PROCESO DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.FE_VALOR           IS 'FECHA VALOR.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.CO_CLIENTE         IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.CO_MONEDA          IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.CO_PRODUCTO        IS 'CODIGO DE PRODUCTO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.CO_SUCURSAL        IS 'CODIGO DE SUCURSAL ACTUAL.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.CO_OPERATIVA       IS 'CODIGO OPERATIVA.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.CO_ANALISTA        IS 'CODIGO DEL ANALISTA.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.CO_RUBR_CUEN_CONT  IS 'CODIGO DEL RUBRO DE CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.NU_CUENTA          IS 'NUMERO DE CUENTA/PRESTAMO DEL CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.NU_CUEN_CONT       IS 'NUMERO DE CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.NU_ASIENTO         IS 'NUMERO DE ASIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.NU_TRREAL          IS 'NUMERO DE LA TRANSACCION REAL DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.NU_ORDINAL         IS 'NUMERO ORDINAL DE SALDOS.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.NU_TRVIRTUAL       IS 'NUMERO DE TRANSACCION VIRTUAL DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.NU_TRTIPO          IS 'NUMERO DEL TIPO DE TRANSACCION DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.TI_MOVI_CONTA      IS 'TIPO DE MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.TI_APLICACION      IS 'TIPO DE LA APLCACION ORIGEN (TOPAZ / TRADERLIVE / EBS) DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.TI_CLAS_CUEN_CONT  IS 'TIPO DE LA CLASE DE LA CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.MO_IMPORTE         IS 'MONTO DE IMPORTE DE LA TRANSACCION.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.MO_IMPO_MN         IS 'MONTO DE IMPORTE DE LA TRANSACCION EN MONEDA NACIONAL.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.TI_SIGNO           IS 'TIPO DE OPERACION SI ES DEBITO/CREDITO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.TI_AJUSTE          IS 'TIPO DE AJUSTE DE FIN DE MES.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.DE_REFE_ASIE       IS 'DESCRIPCION DE LA REFERENCIA DEL ASIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.DE_ASIENTO         IS 'DESCRIPCION DEL ASIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.FE_ACTU_DIA        IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.CO_ACTU_USER       IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.NU_CARGA           IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_DETALLE.IN_ESTA_REG        IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE ODS.TP_BROAD_INFORMACION_AHORROS
(
  ID_MOVIMIENTO   NUMBER(15)    DEFAULT 0,
  CO_CLIENTE      NUMBER(15)    DEFAULT 0,
  CO_PRODUCTO     NUMBER(5)     DEFAULT 0,
  CO_ANALISTA     NUMBER(8)     DEFAULT 0,
  FE_ACTU_DIA     DATE          DEFAULT SYSDATE,
  CO_ACTU_USER    VARCHAR2(50)  DEFAULT '.',
  NU_CARGA        INTEGER       DEFAULT 0,
  IN_ESTA_REG     INTEGER       DEFAULT 0
)
NOLOGGING TABLESPACE ODS_DATA_01
    PCTFREE 0
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 8M
      NEXT 1M
      MINEXTENTS 1
      MAXEXTENTS UNLIMITED
    );

COMMENT ON TABLE  ODS.TP_BROAD_INFORMACION_AHORROS		   	   	  IS 'TABLA TEMPORAL DE PROCESO, CONTIENE INFORMACION COMPLEMENTARIA DE AHORROS PARA LA GENERACION DE LA BROAD'; 
COMMENT ON COLUMN ODS.TP_BROAD_INFORMACION_AHORROS.ID_MOVIMIENTO  IS 'IDENTIFICADOR DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_INFORMACION_AHORROS.CO_CLIENTE     IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_INFORMACION_AHORROS.CO_PRODUCTO    IS 'CODIGO DE PRODUCTO.';
COMMENT ON COLUMN ODS.TP_BROAD_INFORMACION_AHORROS.CO_ANALISTA    IS 'CODIGO DEL ANALISTA.';
COMMENT ON COLUMN ODS.TP_BROAD_INFORMACION_AHORROS.FE_ACTU_DIA    IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN ODS.TP_BROAD_INFORMACION_AHORROS.CO_ACTU_USER   IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_INFORMACION_AHORROS.NU_CARGA       IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_INFORMACION_AHORROS.IN_ESTA_REG    IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE ODS.TP_BROAD_HISTORIA_PLAZO
(
  ID_MOVIMIENTO   NUMBER(15)      DEFAULT 0,
  CO_CLIENTE      NUMBER(15)      DEFAULT 0,  
  CO_PRODUCTO     NUMBER(5)       DEFAULT 0,
  CO_ANALISTA     NUMBER(8)       DEFAULT 0,
  NU_CUENTA       NUMBER(15)      DEFAULT 0,
  FE_ACTU_DIA     DATE            DEFAULT SYSDATE,
  CO_ACTU_USER    VARCHAR2(50)    DEFAULT '.',
  NU_CARGA        INTEGER         DEFAULT 0,
  IN_ESTA_REG     INTEGER         DEFAULT 0  
) 
NOLOGGING TABLESPACE ODS_DATA_01
    PCTFREE 0
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 8M
      NEXT 1M
      MINEXTENTS 1
      MAXEXTENTS UNLIMITED
    );

COMMENT ON TABLE  ODS.TP_BROAD_HISTORIA_PLAZO		   	   	 IS 'TABLA TEMPORAL DE PROCESO, CONTIENE INFORMACION COMPLEMENTARIA DE HISTORIA PLAZO PARA LA GENERACION DE LA BROAD'; 
COMMENT ON COLUMN ODS.TP_BROAD_HISTORIA_PLAZO.ID_MOVIMIENTO  IS 'IDENTIFICADOR DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_HISTORIA_PLAZO.CO_CLIENTE     IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_HISTORIA_PLAZO.CO_PRODUCTO    IS 'CODIGO DE PRODUCTO.';
COMMENT ON COLUMN ODS.TP_BROAD_HISTORIA_PLAZO.CO_ANALISTA    IS 'CODIGO DEL ANALISTA.';
COMMENT ON COLUMN ODS.TP_BROAD_HISTORIA_PLAZO.NU_CUENTA      IS 'NUMERO DE CUENTA/PRESTAMO DEL CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_HISTORIA_PLAZO.FE_ACTU_DIA    IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN ODS.TP_BROAD_HISTORIA_PLAZO.CO_ACTU_USER   IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_HISTORIA_PLAZO.NU_CARGA       IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_HISTORIA_PLAZO.IN_ESTA_REG    IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE ODS.TP_BROAD_MOVIMIENTO_DEBITO
(
  ID_MOVIMIENTO   NUMBER(15)    DEFAULT 0,
  CO_CLIENTE      NUMBER(15)    DEFAULT 0,  
  CO_PRODUCTO     NUMBER(5)     DEFAULT 0,
  CO_ANALISTA     NUMBER(8)     DEFAULT 0,
  NU_CUENTA       NUMBER(15)    DEFAULT 0,
  FE_ACTU_DIA     DATE          DEFAULT SYSDATE,
  CO_ACTU_USER    VARCHAR2(50)  DEFAULT '.',
  NU_CARGA        INTEGER       DEFAULT 0,
  IN_ESTA_REG     INTEGER       DEFAULT 0
)  
NOLOGGING TABLESPACE ODS_DATA_01
    PCTFREE 0
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 8M
      NEXT 1M
      MINEXTENTS 1
      MAXEXTENTS UNLIMITED
    );

COMMENT ON TABLE  ODS.TP_BROAD_MOVIMIENTO_DEBITO		   	    IS 'TABLA TEMPORAL DE PROCESO, CONTIENE INFORMACION COMPLEMENTARIA MOVIMIENTOS CONTABLES DE DEBITO PARA LA GENERACION DE LA BROAD'; 
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_DEBITO.ID_MOVIMIENTO  IS 'IDENTIFICADOR DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_DEBITO.CO_CLIENTE     IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_DEBITO.CO_PRODUCTO    IS 'CODIGO DE PRODUCTO.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_DEBITO.CO_ANALISTA    IS 'CODIGO DEL ANALISTA.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_DEBITO.NU_CUENTA      IS 'NUMERO DE CUENTA/PRESTAMO DEL CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_DEBITO.FE_ACTU_DIA    IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_DEBITO.CO_ACTU_USER   IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_DEBITO.NU_CARGA       IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_DEBITO.IN_ESTA_REG    IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE ODS.TP_BROAD_MOVIMIENTO_CREDITO
(
  ID_MOVIMIENTO   NUMBER(15)    DEFAULT 0,
  CO_CLIENTE      NUMBER(15)    DEFAULT 0,  
  CO_PRODUCTO     NUMBER(5)     DEFAULT 0,
  CO_ANALISTA     NUMBER(8)     DEFAULT 0,
  NU_CUENTA       NUMBER(15)    DEFAULT 0,
  FE_ACTU_DIA     DATE          DEFAULT SYSDATE,
  CO_ACTU_USER    VARCHAR2(50)  DEFAULT '.',
  NU_CARGA        INTEGER       DEFAULT 0,
  IN_ESTA_REG     INTEGER       DEFAULT 0
)  
NOLOGGING TABLESPACE ODS_DATA_01
    PCTFREE 0
    INITRANS 1
    MAXTRANS 255
    STORAGE
    (
      INITIAL 8M
      NEXT 1M
      MINEXTENTS 1
      MAXEXTENTS UNLIMITED
    );

COMMENT ON TABLE  ODS.TP_BROAD_MOVIMIENTO_CREDITO		   	     IS 'TABLA TEMPORAL DE PROCESO, CONTIENE INFORMACION COMPLEMENTARIA MOVIMIENTOS CONTABLES DE CREDITO PARA LA GENERACION DE LA BROAD'; 
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_CREDITO.ID_MOVIMIENTO  IS 'IDENTIFICADOR DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_CREDITO.CO_CLIENTE     IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_CREDITO.CO_PRODUCTO    IS 'CODIGO DE PRODUCTO.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_CREDITO.CO_ANALISTA    IS 'CODIGO DEL ANALISTA.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_CREDITO.NU_CUENTA      IS 'NUMERO DE CUENTA/PRESTAMO DEL CLIENTE.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_CREDITO.FE_ACTU_DIA    IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_CREDITO.CO_ACTU_USER   IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_CREDITO.NU_CARGA       IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.TP_BROAD_MOVIMIENTO_CREDITO.IN_ESTA_REG    IS 'INDICADOR DEL ESTADO DEL REGISTRO.';


---


CREATE TABLE ODS.HD_BROAD_CONTABLE
(
  NU_PERI_MES       NUMBER(6)         DEFAULT 0,
  FE_PROCESO        DATE,
  FE_MOVIMIENTO     DATE,
  FE_VALOR          DATE,
  CO_RUBR_CUEN_CONT NUMBER(4)         DEFAULT 0,
  CO_CLIENTE        NUMBER(15)        DEFAULT 0,
  CO_PRODUCTO       NUMBER(5)         DEFAULT 0,
  CO_SUCURSAL       NUMBER(15)        DEFAULT 0,
  CO_ANALISTA       NUMBER(8)         DEFAULT 0,
  CO_MONEDA         NUMBER(5)         DEFAULT 0,
  CO_OPERATIVA      NUMBER(5)         DEFAULT 0,
  NU_ASIENTO        NUMBER(15)        DEFAULT 0,  
  NU_CUEN_CONT      NUMBER(30)        DEFAULT 0,
  NU_CUENTA         NUMBER(15)        DEFAULT 0,
  NU_TRREAL         NUMBER(5)         DEFAULT 0,
  NU_ORDINAL        NUMBER(10)        DEFAULT 0,
  NU_TRVIRTUAL      NUMBER(15)        DEFAULT 0,
  NU_TRTIPO         NUMBER(5)         DEFAULT 0,
  TI_APLICACION     VARCHAR2(15)      DEFAULT '.',
  TI_CLAS_CUEN_CONT VARCHAR2(15)      DEFAULT '.',
  TI_MOVI_CONTA     VARCHAR2(1)       DEFAULT '.',
  MO_IMPORTE        NUMBER(15,2)      DEFAULT 0,
  MO_IMPO_MN        NUMBER(15,2)      DEFAULT 0,
  TI_SIGNO          VARCHAR2(1)       DEFAULT '.',
  TI_AJUSTE         VARCHAR2(1)       DEFAULT '.',  
  DE_REFE_ASIE      VARCHAR2(500)    DEFAULT '.',
  DE_ASIENTO        VARCHAR2(500)     DEFAULT '.',
  FE_ACTU_DIA       DATE              DEFAULT SYSDATE,
  CO_ACTU_USER      VARCHAR2(50)      DEFAULT '.',
  NU_CARGA          INTEGER           DEFAULT 0,
  IN_ESTA_REG       INTEGER           DEFAULT 0
)
PARTITION BY RANGE (NU_PERI_MES)
(
  partition P_HD_BROAD_CONTABLE_202001 values less than (202002)
    nologging  tablespace ODS_DATA_01
    pctfree 0
    initrans 1
    maxtrans 255,
  partition P_HD_BROAD_CONTABLE_MAX values less than (MAXVALUE)
    nologging  tablespace ODS_DATA_01
    pctfree 0
    initrans 1
    maxtrans 255
);
COMMENT ON TABLE  ODS.HD_BROAD_CONTABLE		   	     	   IS 'TABLA HISTORICA MENSUAL CON INFORMACION DETALLADA A NIVEL OPERATIVO-CONTABLE DE ACTIVOS Y PASIVOS'; 
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.NU_PERI_MES        IS 'NUMERO DE PERIODO. SE GENERA A PARTIR DEL ANO Y MES DE LA FECHA EXTRACCION EN FORMATO YYYYMM.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.FE_PROCESO         IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.FE_MOVIMIENTO      IS 'FECHA DE PROCESO DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.FE_VALOR           IS 'FECHA VALOR.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.CO_RUBR_CUEN_CONT  IS 'CODIGO DEL RUBRO DE CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.CO_CLIENTE         IS 'CODIGO DE CLIENTE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.CO_PRODUCTO        IS 'CODIGO DE PRODUCTO.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.CO_SUCURSAL        IS 'CODIGO DE SUCURSAL.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.CO_ANALISTA        IS 'CODIGO DEL ANALISTA.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.CO_MONEDA          IS 'CODIGO DE MONEDA.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.CO_OPERATIVA       IS 'CODIGO OPERATIVA.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.NU_ASIENTO         IS 'NUMERO DE ASIENTO.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.NU_CUEN_CONT       IS 'NUMERO DE CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.NU_CUENTA          IS 'NUMERO DE CUENTA/PRESTAMO DEL CLIENTE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.NU_TRREAL          IS 'NUMERO DE LA TRANSACCION REAL DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.NU_ORDINAL         IS 'NUMERO ORDINAL DE SALDOS.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.NU_TRVIRTUAL       IS 'NUMERO DE TRANSACCION VIRTUAL DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.NU_TRTIPO          IS 'NUMERO DEL TIPO DE TRANSACCION DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.TI_APLICACION      IS 'TIPO DE LA APLCACION ORIGEN (TOPAZ / TRADERLIVE / EBS) DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.TI_CLAS_CUEN_CONT  IS 'TIPO DE LA CLASE DE LA CUENTA CONTABLE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.TI_MOVI_CONTA      IS 'TIPO DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.MO_IMPORTE         IS 'MONTO DE IMPORTE ORIGEN DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.MO_IMPO_MN         IS 'MONTO DE IMPORTE ORIGEN DEL MOVIMIENTO EN MONEDA NACIONAL.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.TI_SIGNO           IS 'TIPO DE OPERACION SI ES DEBITO/CREDITO.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.TI_AJUSTE          IS 'TIPO DE AJUSTE DE FIN DE MES.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.DE_REFE_ASIE       IS 'DESCRIPCION DE LA REFERENCIA DEL ASIENTO.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.DE_ASIENTO         IS 'DESCRIPCION DEL ASIENTO.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.FE_ACTU_DIA        IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.CO_ACTU_USER       IS 'CODIGO USUARIO DE CARGA AL DWH.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.NU_CARGA           IS 'NUMERO IDENTIFICADOR DE CARGA DWH.';
COMMENT ON COLUMN ODS.HD_BROAD_CONTABLE.IN_ESTA_REG        IS 'INDICADOR DEL ESTADO DEL REGISTRO.';
