DECLARE 
  lv_error          NUMBER;
  lv_mensaje_error  VARCHAR2(20000);
  ld_fecproceso     DATE;
  ld_fecinicial     VARCHAR2(25);
  ld_fecfinal       VARCHAR2(25);
  lv_sql            VARCHAR2(1000);  
		
  CURSOR C1 IS
			SELECT TO_CHAR(FE_REGI_SOLI,'YYYYMM') AS MES_REGI_SOLI
				FROM ODS.MD_SOLICITUDES
				WHERE FE_REGI_SOLI < '06/06/2020'  
				GROUP BY TO_CHAR(FE_REGI_SOLI,'YYYYMM') 
				ORDER BY 1
				;
BEGIN

--CREA PARTICIONES
  ODS.PKG_ODS_GENERICO.SP_GEN_PARTICIONES(
                                            V_TABLA_OWNER =>  'ODS',
                                            V_NOM_TABLA => 'HD_SOLICITUDES',
                                            V_CAMPO_PARTICIONADO => 'FE_PROCESO',
                                            V_TIPO_CAMPO_PARTICIONADO => 'DATE',
                                            V_FRECUENCIA_PARTICION => 'DIARIA',
                                            V_NOMBRE_PARTICION => 'P_SOLICITUDES_',
                                            V_NUM_PARTICIONES_MAX => 20000,
                                            V_TABLESPACE_PARTICION => 'ODS_DATA_01',
                                            V_ERROR => lv_error,
                                            V_MENSAJE_ERROR => lv_mensaje_error           
                                          );

--REINDEXADO
  ODS.PKG_ODS_GENERICO.SP_REGENERA_INDICE(  V_ESQUEMA => 'ODS',
                                            V_NOMTABLA => 'HD_SOLICITUDES',
                                            V_ERROR => lv_error);

--PRIMERA CARGA: 06/06/2019 - 1
	ld_fecproceso := TO_DATE('05/06/2020','DD/MM/YYYY');
	
	FOR R1 IN C1 LOOP
		IF  R1.MES_REGI_SOLI IS NULL THEN
		    lv_sql := 'WHERE FE_REGI_SOLI IS NULL ';
		ELSE
			ld_fecinicial := TO_CHAR(TO_DATE(R1.MES_REGI_SOLI||'01 23:59:59','YYYYMMDD HH24:MI:SS')-1,'YYYYMMDD HH24:MI:SS');
		    ld_fecfinal   := TO_CHAR(LAST_DAY(TO_DATE(R1.MES_REGI_SOLI||'01 00:00:00','YYYYMMDD HH24:MI:SS'))+1,'YYYYMMDD HH24:MI:SS');
			IF R1.MES_REGI_SOLI <> '202006' THEN
			   lv_sql := 'WHERE FE_REGI_SOLI > TO_DATE('''||ld_fecinicial||''',''YYYYMMDD HH24:MI:SS'') AND FE_REGI_SOLI < TO_DATE('''||ld_fecfinal||''',''YYYYMMDD HH24:MI:SS'') ';
			ELSE
			   lv_sql := 'WHERE FE_REGI_SOLI > TO_DATE('''||ld_fecinicial||''',''YYYYMMDD HH24:MI:SS'') AND FE_REGI_SOLI < TO_DATE(''20200606 00:00:00'',''YYYYMMDD HH24:MI:SS'') ';
			END IF; 
		
		END IF;
		
      EXECUTE IMMEDIATE

      '
		  MERGE INTO ODS.HD_SOLICITUDES HD 
		  USING ( 
		  SELECT 
		  NU_PERI_MES, NU_SOLICITUD, CO_CLIENTE, CO_ESTA_SOLI, 
		  CO_TIPO_PRES, NU_METODOLOGIA, CO_ANALISTA, CO_TIPO_SOLI, 
		  NU_CUOT_GRAC, NU_DIA_PAGO, NU_DEPENDIENTES, IN_CAMPANAS, 
		  NU_PUNT_CUAL, FE_REGI_SOLI, MO_SALARIO, MO_SOLICITADO, 
		  NU_PLAZ_SOLI, VL_ENDEUDAMIENTO, VL_TIPO_CAMB_OFI, FE_REGI_PRES, 
		  VL_TASA_OPTI, FE_VENC_LINE, MO_TOTA_GAST, CO_MOTI_RECH, 
		  DE_COME_RECH, CO_PRODUCTO, CO_COND_CLIE, VL_TASA_MINI, 
		  VL_TASA_MAXI, MO_APROBADO, CO_SUCURSAL, VL_TASA, IN_CONGLOMERADO, 
		  DE_PROP_DEST, FE_ACTU_DIA, CO_MONEDA, FE_EVAL_SOLI, CO_TIPO_GRAC, 
		  CO_FORM_DESE, NU_PLAZ_APROB, FE_APRO_SOLI, CO_TIPO_CRED, 
		  MO_DEUD_SOLI, IN_EVALUACION, IN_APROBACION, IN_DESEMBOLSO, 
		  CO_USUA_TOPA_REGI, CO_USUA_TOPA_EVAL, CO_USUA_TOPA_APRO, 
		  MO_PRESTAMO, MO_CUOTA, NU_CUOTAS
		  FROM ODS.MD_SOLICITUDES '||lv_sql||' 
		   ) MD ON (HD.NU_SOLICITUD = MD.NU_SOLICITUD)  
		  WHEN NOT MATCHED THEN
				INSERT ( 
				HD.NU_PERI_MES, HD.NU_SOLICITUD, HD.CO_CLIENTE, HD.CO_ESTA_SOLI, 
				HD.CO_TIPO_PRES, HD.NU_METODOLOGIA, HD.CO_ANALISTA, HD.CO_TIPO_SOLI, 
				HD.NU_CUOT_GRAC, HD.NU_DIA_PAGO, HD.NU_DEPENDIENTES, HD.IN_CAMPANAS, 
				HD.NU_PUNT_CUAL, HD.FE_REGI_SOLI, HD.MO_SALARIO, HD.MO_SOLICITADO, 
				HD.NU_PLAZ_SOLI, HD.VL_ENDEUDAMIENTO, HD.VL_TIPO_CAMB_OFI, 
				HD.FE_REGI_PRES, HD.VL_TASA_OPTI, HD.FE_VENC_LINE, HD.MO_TOTA_GAST, 
				HD.CO_MOTI_RECH, HD.DE_COME_RECH, HD.CO_PRODUCTO, HD.CO_COND_CLIE, 
				HD.VL_TASA_MINI, HD.VL_TASA_MAXI, HD.MO_APROBADO, HD.CO_SUCURSAL, 
				HD.VL_TASA, HD.IN_CONGLOMERADO, HD.DE_PROP_DEST, HD.FE_ACTU_DIA, 
				HD.CO_MONEDA, HD.FE_EVAL_SOLI, HD.CO_TIPO_GRAC, HD.CO_FORM_DESE, 
				HD.NU_PLAZ_APROB, HD.FE_APRO_SOLI, HD.CO_TIPO_CRED, HD.MO_DEUD_SOLI, 
				HD.IN_EVALUACION, HD.IN_APROBACION, HD.IN_DESEMBOLSO, 
				HD.CO_USUA_TOPA_REGI, HD.CO_USUA_TOPA_EVAL, HD.CO_USUA_TOPA_APRO, 
				HD.MO_PRESTAMO, HD.MO_CUOTA, HD.NU_CUOTAS, HD.FE_PROCESO )
				VALUES (
				MD.NU_PERI_MES, MD.NU_SOLICITUD, MD.CO_CLIENTE, MD.CO_ESTA_SOLI, 
				MD.CO_TIPO_PRES, MD.NU_METODOLOGIA, MD.CO_ANALISTA, 
				MD.CO_TIPO_SOLI, MD.NU_CUOT_GRAC, MD.NU_DIA_PAGO, 
				MD.NU_DEPENDIENTES, MD.IN_CAMPANAS, MD.NU_PUNT_CUAL, 
				MD.FE_REGI_SOLI, MD.MO_SALARIO, MD.MO_SOLICITADO, 
				MD.NU_PLAZ_SOLI, MD.VL_ENDEUDAMIENTO, MD.VL_TIPO_CAMB_OFI, 
				MD.FE_REGI_PRES, MD.VL_TASA_OPTI, MD.FE_VENC_LINE, 
				MD.MO_TOTA_GAST, MD.CO_MOTI_RECH, MD.DE_COME_RECH, 
				MD.CO_PRODUCTO, MD.CO_COND_CLIE, MD.VL_TASA_MINI, 
				MD.VL_TASA_MAXI, MD.MO_APROBADO, MD.CO_SUCURSAL, MD.VL_TASA, 
				MD.IN_CONGLOMERADO, MD.DE_PROP_DEST, MD.FE_ACTU_DIA, 
				MD.CO_MONEDA, MD.FE_EVAL_SOLI, MD.CO_TIPO_GRAC, MD.CO_FORM_DESE, 
				MD.NU_PLAZ_APROB, MD.FE_APRO_SOLI, MD.CO_TIPO_CRED, 
				MD.MO_DEUD_SOLI, MD.IN_EVALUACION, MD.IN_APROBACION, 
				MD.IN_DESEMBOLSO, MD.CO_USUA_TOPA_REGI, MD.CO_USUA_TOPA_EVAL, 
				MD.CO_USUA_TOPA_APRO, MD.MO_PRESTAMO, MD.MO_CUOTA, MD.NU_CUOTAS,
				TO_DATE('''||TO_CHAR(ld_fecproceso,'YYYYMMDD')||''',''YYYYMMDD'') ) '
        ;
        COMMIT;

	END LOOP;
	
  ODS.PKG_ODS_GENERICO.SP_ESTADISTICAS_PARTITION(V_FECHA_INICIO => ld_fecproceso,
												   V_FECHA_FIN => ld_fecproceso,
												   V_TABLA_OWNER => 'ODS', 
												   V_NOM_TABLA => 'HD_SOLICITUDES',
												   V_FRECUENCIA_PARTICION => 'DIARIA',
												   V_NOMBRE_PARTICION => 'P_SOLICITUDES_',
												   V_ERROR => lv_error,
												   V_MENSAJE_ERROR => lv_mensaje_error);
	
   ODS.PKG_ODS_GENERICO.SP_REGENERA_INDICE(V_ESQUEMA => 'ODS',
                           V_NOMTABLA => 'HD_SOLICITUDES',
                           V_ERROR => lv_error);                      
END;
/
