--Insertar Valores en Tabla D_RIE_TRAMO_DETERIORO
INSERT INTO BDS.D_RIE_TRAMO_DETERIORO VALUES (1,'T CASTIGO', SYSDATE);
INSERT INTO BDS.D_RIE_TRAMO_DETERIORO VALUES (2,'T 000 - 000',SYSDATE);
INSERT INTO BDS.D_RIE_TRAMO_DETERIORO VALUES (3,'T 001 - 030',SYSDATE);
INSERT INTO BDS.D_RIE_TRAMO_DETERIORO VALUES (4,'T 031 - 060',SYSDATE);
INSERT INTO BDS.D_RIE_TRAMO_DETERIORO VALUES (5,'T 061 - 090',SYSDATE);
INSERT INTO BDS.D_RIE_TRAMO_DETERIORO VALUES (6,'T 091 - 120',SYSDATE);
INSERT INTO BDS.D_RIE_TRAMO_DETERIORO VALUES (7,'T 121 - 150',SYSDATE);
INSERT INTO BDS.D_RIE_TRAMO_DETERIORO VALUES (8,'T 151 - MÁS',SYSDATE);
INSERT INTO BDS.D_RIE_TRAMO_DETERIORO VALUES (9,'T CANCELADO',SYSDATE);

COMMIT;
