----Tablas ODS
CREATE INDEX ODS.HM_CIERRE_32_N1 ON ODS.HM_CIERRE_32 (NU_PERI_MES,NU_PRESTAMO)  TABLESPACE ODS_IDX_01; 
CREATE INDEX ODS.HM_CANAL_COBRANZA_N1 ON ODS.HM_CANAL_COBRANZA (NU_PERI_MES,NU_PRESTAMO)  TABLESPACE ODS_IDX_01; 
----Tablas BDS
CREATE INDEX BDS.L_RIE_CANAL_COBRANZA_N1 ON BDS.L_RIE_CANAL_COBRANZA(NU_PERI_MES, NU_PRESTAMO) TABLESPACE BDS_IDX_01;
CREATE INDEX BDS.L_RIE_CIERRE_32_N1 ON BDS.L_RIE_CIERRE_32 (NU_PERI_MES, NU_PRESTAMO) TABLESPACE BDS_IDX_01;




