------------------------------------------
CREATE TABLE ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL
(
  NU_PERI_MES       NUMBER(15)    DEFAULT 0,
  FE_ULTI_DIA_MES   DATE          DEFAULT TO_DATE('01010001','DDMMYYYY'),
  FE_APER_CUEN      DATE          DEFAULT TO_DATE('01010001','DDMMYYYY'),
  NU_PRESTAMO       NUMBER(15)    DEFAULT 0,
  CO_CLIENTE        NUMBER(15)    DEFAULT 0,
  MO_APRO_DESE      NUMBER(15,2)  DEFAULT 0,
  MO_DESEMBOLSADO   NUMBER(15,2)  DEFAULT 0,
  DE_MONEDA         VARCHAR2(150) DEFAULT '.',
  TI_DESEMBOLSO     VARCHAR2(100) DEFAULT '.',
  MO_RECU_SALD      NUMBER(15,2)  DEFAULT 0,
  MO_DESE_CAJA      NUMBER(15,2)  DEFAULT 0,
  CO_SUCU_ORIG      NUMBER(15)    DEFAULT 0,
  MO_SOLICITADO     NUMBER(15,2)  DEFAULT 0,
  NU_DIA_PROG_PAGO  NUMBER(15)    DEFAULT 0,
  NO_CLIENTE        VARCHAR2(100) DEFAULT '.',
  NO_VIA_DESE_PLAT  VARCHAR2(100) DEFAULT '.',
  NO_SUCU_ORIG      VARCHAR2(100) DEFAULT '.',
  NU_ASIE_PLAT      NUMBER(15)    DEFAULT 0,
  CO_USUA_DESE_PLAT VARCHAR2(50)  DEFAULT '.',
  CO_FUNC_DESE_PLAT NUMBER(15)    DEFAULT 0,
  NO_USUA_DESE_PLAT VARCHAR2(100) DEFAULT '.',
  CO_SUCU_DESE_PLAT NUMBER(15)    DEFAULT 0,
  NO_SUCU_DESE_PLAT VARCHAR2(100) DEFAULT '.',
  NU_ASIE_CAJA      NUMBER(15)    DEFAULT 0,
  CO_USUA_DESE_CAJA VARCHAR2(50)  DEFAULT '.',
  CO_FUNC_DESE_CAJA NUMBER(15)    DEFAULT 0,
  NO_USUA_DESE_CAJA VARCHAR2(100) DEFAULT '.',
  CO_SUCU_DESE_CAJA NUMBER(15)    DEFAULT 0,
  NO_SUCU_DESE_CAJA VARCHAR2(100) DEFAULT '.',
  FE_ACTU_MES       DATE          DEFAULT TO_DATE('01010001','DDMMYYYY'),
  FE_DESE_PLAT      DATE          DEFAULT TO_DATE('01010001','DDMMYYYY'),
  FE_DESE_CAJA      DATE          DEFAULT TO_DATE('01010001','DDMMYYYY'),
  NU_SOLICITUD      NUMBER(15)    DEFAULT 0,
  NU_PARTICIPANTES  NUMBER(15)    DEFAULT 0,
  DE_CARG_USUA_PLAT VARCHAR2(150) DEFAULT '.',
  DE_CARG_USUA_CAJA VARCHAR2(150) DEFAULT '.',
  NU_LINE_CRED      NUMBER(15),
  MO_CUOTA          NUMBER(15,2),
  NU_CUOTAS         NUMBER(15),
  FE_DESEMBOLSO     DATE,
  CO_REFINANCIACION VARCHAR2(1),
  CO_GRUP_EXCE      NUMBER(15),
  CO_USUA_TOPA_DESE VARCHAR2(10) 
)
PARTITION BY RANGE (NU_PERI_MES)
(
  PARTITION P_DESEMBOLSO_201401 VALUES LESS THAN (201402) TABLESPACE ODS_DATA_01
);
-- Add comments to the table 
COMMENT ON TABLE ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL IS 'DESEMBOLSOS DE PRESTAMOS REALIZADOS';
-- Add comments to the columns 
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NU_PERI_MES IS 'PERIODO DEL MES DE CARGA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.FE_ULTI_DIA_MES IS 'ULTIMO DIA DEL MES DEL PERIODO DE CARGA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.FE_APER_CUEN IS 'FECHA DE APERTURA DE LA CUENTA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NU_PRESTAMO IS 'NUMERO DE PRESTAMO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_CLIENTE IS 'CODIGO CLIENTE';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.MO_APRO_DESE IS 'MONTO APROBADO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.MO_DESEMBOLSADO IS 'MONTO DESEMBOLSADO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.DE_MONEDA IS 'CODIGO DE MONEDA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.TI_DESEMBOLSO IS 'TIPO DE DESEMBOLSO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.MO_RECU_SALD IS 'MONTO RECURRENTE CON SALDO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.MO_DESE_CAJA IS 'MONTO DESEMBOLSADO EN CAJA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_SUCU_ORIG IS 'CODIGO SUCURSAL DE ORIGEN EN PLATAFORMA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.MO_SOLICITADO IS 'MONTO SOLICITADO DEL CREDITO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NU_DIA_PROG_PAGO IS 'DIA DE PROGRAMACION DE PAGO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NO_CLIENTE IS 'NOMBRE DEL CLIENTE';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NO_VIA_DESE_PLAT IS 'VIA DEL DESEMBOLSO PLATAFORMA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NO_SUCU_ORIG IS 'NOMBRE SUCURSAL DE ORIGEN';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NU_ASIE_PLAT IS 'ASIENTO DESEMBOLSO PLATAFORMA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_USUA_DESE_PLAT IS 'CODIGO USUARIO DESEMBOLSO EN PLATAFORMA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_FUNC_DESE_PLAT IS 'CODIGO FUNCIONARIO DESEMBOLSO PLATAFORMA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NO_USUA_DESE_PLAT IS 'NOMBRE USUARIO DEL DESEMBOLSO PLATAFORMA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_SUCU_DESE_PLAT IS 'CODIGO SUCURSAL DEL DESEMBOLSO PLATAFORMA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NO_SUCU_DESE_PLAT IS 'NOMBRE SUCURSAL DEL DESEMBOLSO PLATAFORMA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NU_ASIE_CAJA IS 'ASIENTO DESEMBOLSADO EN VENTANILLA O CAJA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_USUA_DESE_CAJA IS 'CODIGO USUARIO DESEMBOLSADO CAJA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_FUNC_DESE_CAJA IS 'CODIGO FUNCIONARIO DESEMBOLSADO EN VENTANILLA O CAJA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NO_USUA_DESE_CAJA IS 'NOMBRE USUARIO DESEMBOLSADO CAJA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_SUCU_DESE_CAJA IS 'CODIGO SUCURSAL DESEMBOLSADO CAJA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NO_SUCU_DESE_CAJA IS 'NOMBRE SUCURSAL DESEMBOLSADO CAJA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.FE_ACTU_MES IS 'FECHA DE CARGA O FECHA DE PROCESO.';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.FE_DESE_PLAT IS 'FECHA DE DESEMBOLSO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.FE_DESE_CAJA IS 'FECHA DE DESEMBOLSADO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NU_SOLICITUD IS 'NUMERO DE SOLICITUD';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NU_PARTICIPANTES IS 'NUMERO DE PARTICIPANTE';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.DE_CARG_USUA_PLAT IS 'DESCRIPCION DEL CARGO DEL USUARIO DESEMBOLSO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.DE_CARG_USUA_CAJA IS 'DESCRIPCION DEL CARGO DEL USUARIO DESEMBOLSADO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NU_LINE_CRED IS 'NUMERO DE LINEA DE CREDITO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.MO_CUOTA IS 'MONTO CUOTA';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.NU_CUOTAS IS 'NUMERO DE CUOTAS';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.FE_DESEMBOLSO IS 'FECHA DE DESEMBOLSO';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_REFINANCIACION IS 'REFINANCIACION';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_GRUP_EXCE IS 'CODIGO DE GRUPO DE EXCEPCIONES';
COMMENT ON COLUMN ODS.TM_HD_DESEMBOLSO_CARGA_INICIAL.CO_USUA_TOPA_DESE IS 'CODIGO USUARIO TOPAZ QUE REALIZO EL DESEMBOLSO';


------------------------------------------
CREATE TABLE ODS.TG_BITACORA_PRE_PRESTAMO
(
  NU_SOLICITUD      NUMBER(15),
  FE_PROCESO        DATE,
  TX_HORA_PROC      VARCHAR2(12),
  CO_USUA_TOPA      VARCHAR2(10),
  DE_DETALLEDOS     VARCHAR2(60)
)
TABLESPACE ODS_DATA_01;
	
COMMENT ON TABLE ODS.TG_BITACORA_PRE_PRESTAMO IS 'TABLA TEMPORAL DE BITACORA DE PRE-PRESTAMOS';
-- Add comments to the columns 
COMMENT ON COLUMN ODS.TG_BITACORA_PRE_PRESTAMO.NU_SOLICITUD IS 'NUMERO DE SOLICITUD.';
COMMENT ON COLUMN ODS.TG_BITACORA_PRE_PRESTAMO.FE_PROCESO IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN ODS.TG_BITACORA_PRE_PRESTAMO.TX_HORA_PROC IS 'HORA DE PROCESO.';
COMMENT ON COLUMN ODS.TG_BITACORA_PRE_PRESTAMO.CO_USUA_TOPA IS 'CODIGO DEL USUARIO DE TOPAZ.';
COMMENT ON COLUMN ODS.TG_BITACORA_PRE_PRESTAMO.DE_DETALLEDOS IS 'DESCRIPCION DEL DETALLE 2 DEL PROCESO DE PRE-PRESTAMO.';

CREATE TABLE ODS.TP_HD_DESEMBOLSO_BKP_CARGA_INI PCTFREE 0 NOLOGGING TABLESPACE TEMPORAL_PROD AS SELECT * FROM ODS.HD_DESEMBOLSO;

CREATE OR REPLACE VIEW DWHADM.SL_BITACORASOLICITUD AS
SELECT TZ_LOCK,
       NUMSOLICITUD,
       FECHA,
       HORA,
       USUARIO,
       EVENTO,
       DETALLEUNO,
       DETALLEDOS
FROM EDYFICAR.SL_BITACORASOLICITUD@DWHPROD_TPZPROD;