

GRANT SELECT ON STG.BR_TDL_0001_CONTROL_DWH TO DWHADM;
GRANT SELECT ON STG.BR_TDL_0001_TRAMA_DWH 	TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON STG.T_TDL_0001_CONTROL_DWH TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON STG.T_CONTABLE_TRADER      TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.TD_CONTABLE_TRADER     TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.HD_CONTABLE_TRADER     TO DWHADM;

GRANT SELECT, INSERT, UPDATE, DELETE ON STG.T_CASIENTOMANUAL          		TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON STG.T_BS_HISTORIA_PLAZO_CONTA 		TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON STG.T_SALDOS_CONTA            		TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.HD_BROAD_CONTABLE         		TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.TP_BROAD_DETALLE          		TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.TP_BROAD_HISTORIA_PLAZO   		TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.TP_BROAD_MOVIMIENTO_CREDITO		TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.TP_BROAD_MOVIMIENTO_DEBITO		TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.TP_BROAD_INFORMACION_AHORROS  	TO DWHADM;
GRANT SELECT, INSERT, UPDATE, DELETE ON ODS.TP_BROAD_ASIENTOS         		TO DWHADM;
 
