-- Create/Recreate indexes 
CREATE INDEX ODS.HD_PRESTAMOS_REFINANCIADOS_N1 ON ODS.HD_PRESTAMOS_REFINANCIADOS (NU_SOLICITUD) TABLESPACE ODS_IDX_01;
CREATE INDEX ODS.HD_PRESTAMOS_REFINANCIADOS_N2 ON ODS.HD_PRESTAMOS_REFINANCIADOS (NU_PRESTAMO)  TABLESPACE ODS_IDX_01; 
CREATE INDEX ODS.TP_BITACORA_PRE_PRESTAMO_N1   ON ODS.TP_BITACORA_PRE_PRESTAMO   (NU_SOLICITUD) TABLESPACE ODS_IDX_01;
CREATE INDEX ODS.HD_CLIENTES_N1                ON ODS.HD_CLIENTES                (CO_CLIENTE)   TABLESPACE ODS_IDX_01;
CREATE INDEX ODS.HD_SOLICITUDES_N1             ON ODS.HD_SOLICITUDES             (NU_SOLICITUD) TABLESPACE ODS_IDX_01;
CREATE INDEX ODS.HD_DESEMBOLSO_N2              ON ODS.HD_DESEMBOLSO              (NU_SOLICITUD) TABLESPACE ODS_IDX_01;
