CREATE UNIQUE INDEX ODS.UK_MD_CAMPANA_VIGENCIA_N1   ON ODS.MD_CAMPANA_VIGENCIA   (CO_UNIC_CAMP) TABLESPACE ODS_IDX_01;
CREATE UNIQUE INDEX ODS.UK_MD_CRM_CAMPANA_N1     	ON ODS.MD_CRM_CAMPANA        (CO_CAMPANA) TABLESPACE ODS_IDX_01;
CREATE UNIQUE INDEX ODS.UK_MD_CANAL_N1     			ON ODS.MD_CANAL              (CO_CANAL) TABLESPACE ODS_IDX_01;
CREATE UNIQUE INDEX ODS.UK_MD_RESULTADO_CONTACTO_N1 ON ODS.MD_RESULTADO_CONTACTO (CO_RESP_CANA) TABLESPACE ODS_IDX_01;
CREATE UNIQUE INDEX ODS.UK_MD_GRUPO_PRODUCTO_N1     ON ODS.MD_GRUPO_PRODUCTO     (CO_PRODUCTO) TABLESPACE ODS_IDX_01;
CREATE UNIQUE INDEX ODS.UK_MD_PRODUCTO_CAMPANA_N1   ON ODS.MD_PRODUCTO_CAMPANA   (CO_RELA_PROD_CAMP,NU_PERI_INIC) TABLESPACE ODS_IDX_01;
