--CREACION DE TABLAS

CREATE TABLE DWHADM.PARAMETROS_DE 
 (ID_DATA_ENTR NUMBER, 
  CO_MESA NUMBER,
  IN_REPROCESO NUMBER,
  IN_ESTADO NUMBER,
  NO_DATA_ENTR VARCHAR2(50), 
  NO_TABL_EXTE VARCHAR2(50), 
  NO_TABL_STG VARCHAR2(50), 
  DE_OWNER VARCHAR2(50), 
  DE_DESC_CORT VARCHAR2(250),   
  TX_FRECUENCIA VARCHAR2(50)   
   );
  ALTER TABLE DWHADM.PARAMETROS_DE ADD PRIMARY KEY (ID_DATA_ENTR);
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.ID_DATA_ENTR IS 'ID DEL DATA ENTRY';
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.CO_MESA IS 'CODIGO DE LA MESA';
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.NO_DATA_ENTR IS 'NOMBRE DEL DATA ENTRY';
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.NO_TABL_EXTE IS 'NOMBRE DE LA TABLA EXTERNA';
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.NO_TABL_STG IS 'NOMBRE DE LA TABLA EN STG';
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.IN_REPROCESO IS 'INDICADOR DE REPROCESO (S/N)';
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.IN_ESTADO IS 'ESTADO DEL DATA ENTRY';
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.TX_FRECUENCIA IS 'FRECUENCIA DE EJECUCION';
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.DE_OWNER IS 'PROPIETARIO DEL DATA ENTRY';
   COMMENT ON COLUMN DWHADM.PARAMETROS_DE.DE_DESC_CORT IS 'DESCRIPCION CORTA DEL DATA ENTRY';
   COMMENT ON TABLE DWHADM.PARAMETROS_DE  IS 'TABLA PARAMETROS DE LOS DATA ENTRYS';

CREATE TABLE DWHADM.RESULTADO_CARGA_DE 
 (ID_DATA_ENTR NUMBER, 
  CO_MESA NUMBER, 
  FE_EJECUCION DATE,
  IN_ESTADO NUMBER,
  NO_DATA_ENTR VARCHAR2(50),
  DE_ERROR VARCHAR2(250),
   FOREIGN KEY (ID_DATA_ENTR)
    REFERENCES DWHADM.PARAMETROS_DE (ID_DATA_ENTR) ENABLE
   );
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE.ID_DATA_ENTR IS 'ID DEL DATA ENTRY';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE.CO_MESA IS 'CODIGO DE LA MESA';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE.NO_DATA_ENTR IS 'NOMBRE DEL DATA ENTRY';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE.FE_EJECUCION IS 'FECHA DE EJECUCION';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE.IN_ESTADO IS 'ESTADO DE LA EJECUCION';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE.DE_ERROR IS 'DESCRIPCION DEL ERROR';
   COMMENT ON TABLE DWHADM.RESULTADO_CARGA_DE  IS 'TABLA DEL RESULTADO DE LA EJECUCION DEL DATA ENTRY';

CREATE TABLE DWHADM.RESULTADO_CARGA_DE_HIST 
 (ID_DATA_ENTR NUMBER, 
  CO_MESA NUMBER, 
  FE_EJECUCION DATE, 
  IN_ESTADO NUMBER,
  NO_DATA_ENTR VARCHAR2(50),   
  DE_ERROR VARCHAR2(250), 
   FOREIGN KEY (ID_DATA_ENTR)
    REFERENCES DWHADM.PARAMETROS_DE (ID_DATA_ENTR) ENABLE
   );
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE_HIST.ID_DATA_ENTR IS 'ID DEL DATA ENTRY';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE_HIST.CO_MESA IS 'CODIGO DE LA MESA';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE_HIST.NO_DATA_ENTR IS 'NOMBRE DEL DATA ENTRY';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE_HIST.FE_EJECUCION IS 'FECHA DE EJECUCION';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE_HIST.IN_ESTADO IS 'ESTADO DE LA EJECUCION';
   COMMENT ON COLUMN DWHADM.RESULTADO_CARGA_DE_HIST.DE_ERROR IS 'DESCRIPCION DEL ERROR';
   COMMENT ON TABLE DWHADM.RESULTADO_CARGA_DE_HIST  IS 'TABLA HISTORICA DEL RESULTADO DE LA EJECUCION DEL DATA ENTRY';
   
 CREATE TABLE DWHADM.ARCHIVOS_CARGA_DE 
 (ID_ARCH_CARG NUMBER, 
  FE_EJECUCION DATE,
  NO_ARCH_ORIG VARCHAR2(250), 
  NO_ARCH_BACK VARCHAR2(250)  
  );
  ALTER TABLE DWHADM.ARCHIVOS_CARGA_DE ADD PRIMARY KEY (ID_ARCH_CARG);
  COMMENT ON COLUMN DWHADM.ARCHIVOS_CARGA_DE.ID_ARCH_CARG IS 'ID DE ARCHIVO DE CARGA';
  COMMENT ON COLUMN DWHADM.ARCHIVOS_CARGA_DE.NO_ARCH_ORIG IS 'NOMBRE DE ARCHIVO';
  COMMENT ON COLUMN DWHADM.ARCHIVOS_CARGA_DE.NO_ARCH_BACK IS 'NOMBRE DE ARCHIVO CON FECHA DE EJECUCION';
  COMMENT ON COLUMN DWHADM.ARCHIVOS_CARGA_DE.FE_EJECUCION IS 'FECHA DE EJECUCION';