INSERT INTO DWHADM.PARAMETROS_DE (ID_DATA_ENTR, CO_MESA, NO_DATA_ENTR, NO_TABL_EXTE, NO_TABL_STG, IN_REPROCESO, IN_ESTADO, TX_FRECUENCIA, DE_OWNER, DE_DESC_CORT)
VALUES (DWHADM.SEC_PARAMETROS_DE.NEXTVAL, 300, 'CAMPANA', 'DE_CAMPANA', 'T_CAMPANA', 0, 1, 'DIARIO', 'CRM', 'TABLA MAESTRA DE CAMPAÑAS');

INSERT INTO DWHADM.PARAMETROS_DE (ID_DATA_ENTR, CO_MESA, NO_DATA_ENTR, NO_TABL_EXTE, NO_TABL_STG, IN_REPROCESO, IN_ESTADO, TX_FRECUENCIA, DE_OWNER, DE_DESC_CORT)
VALUES (DWHADM.SEC_PARAMETROS_DE.NEXTVAL, 300, 'CANAL', 'DE_CANAL', 'T_CANAL', 0, 1, 'DIARIO', 'CRM', 'TABLA MAESTRA DE CANALES');

INSERT INTO DWHADM.PARAMETROS_DE (ID_DATA_ENTR, CO_MESA, NO_DATA_ENTR, NO_TABL_EXTE, NO_TABL_STG, IN_REPROCESO, IN_ESTADO, TX_FRECUENCIA, DE_OWNER, DE_DESC_CORT)
VALUES (DWHADM.SEC_PARAMETROS_DE.NEXTVAL, 300, 'CAMPAÑA VIGENCIA', 'DE_CAMPANA_VIGENCIA', 'T_CAMPANA_VIGENCIA', 0, 1, 'DIARIO', 'CRM', 'TABLA QUE ALMACENA LA VIGENCIA DE LAS CAMPAÑAS EN DETERMINADO PERIODO');

INSERT INTO DWHADM.PARAMETROS_DE (ID_DATA_ENTR, CO_MESA, NO_DATA_ENTR, NO_TABL_EXTE, NO_TABL_STG, IN_REPROCESO, IN_ESTADO, TX_FRECUENCIA, DE_OWNER, DE_DESC_CORT)
VALUES (DWHADM.SEC_PARAMETROS_DE.NEXTVAL, 300, 'RELACION PRODUCTO CAMPANA', 'DE_REL_PROD_CAMPANA', 'T_REL_PROD_CAMPANA', 0, 1, 'DIARIO', 'CRM', 'TABLA QUE GUARDA LA RELACIÓN DE PRODUCTO CON CAMPAÑA EN PERIODO DETERMINADO');

INSERT INTO DWHADM.PARAMETROS_DE (ID_DATA_ENTR, CO_MESA, NO_DATA_ENTR, NO_TABL_EXTE, NO_TABL_STG, IN_REPROCESO, IN_ESTADO, TX_FRECUENCIA, DE_OWNER, DE_DESC_CORT)
VALUES (DWHADM.SEC_PARAMETROS_DE.NEXTVAL, 300, 'RESULTADO CONTACTO', 'DE_RESULTADO_CONTACTO', 'T_RESULTADO_CONTACTO', 0, 1, 'DIARIO', 'CRM', 'TABLA CRM PARA INSCRIBIR POSIBLES RESPUESTAS DE LA RETROALIMENTACIÓN POR CANAL TIPIFICADO CON UNA RESPUESTA Y RESULTADO DEL CONTACTO ESTANDARIZADOS.');

INSERT INTO DWHADM.PARAMETROS_DE (ID_DATA_ENTR, CO_MESA, NO_DATA_ENTR, NO_TABL_EXTE, NO_TABL_STG, IN_REPROCESO, IN_ESTADO, TX_FRECUENCIA, DE_OWNER, DE_DESC_CORT)
VALUES (DWHADM.SEC_PARAMETROS_DE.NEXTVAL, 300, 'MARKETING PRODUCTOS', 'DE_MKT_PRODUCTOS', 'T_MKT_PRODUCTOS', 0, 1, 'DIARIO', 'CRM', 'TABLA DE CATÁLOGO DE PRODUCTOS POR CLASIFICACIÓN DE GRUPOS');

COMMIT;