CREATE UNIQUE INDEX BDS.UK_TABLAS_TRUNCO_RETOMA_N1 ON BDS.T_TABLAS_TRUNCO_RETOMA (ID_ETAPA, ID_FASE, ID_SUBFASE, DE_NOMBREFISICO) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.F_RIE_REF_EXTREMO_N1 ON BDS.F_RIE_REF_EXTREMO (NU_PRES_ORIG, NU_PRES_FINA) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.F_RIE_COSECHA_D_N1 ON BDS.F_RIE_COSECHA_D (FE_PROCESO, NU_PRESTAMO)  TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.F_RIE_COSECHA_M_N1 ON BDS.F_RIE_COSECHA_M (NU_PERI_MES, NU_PRESTAMO) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.F_RIE_ADMISION_CREDITOS_N1 ON BDS.F_RIE_ADMISION_CREDITOS (NU_SOLICITUD, NU_PRESTAMO) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.T_RIE_ADMISION_CREDITOS_N1 ON BDS.T_RIE_ADMISION_CREDITOS (NU_SOLICITUD, NU_PRESTAMO) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.C_RIE_DESEMBOLSO_N1 ON BDS.C_RIE_DESEMBOLSO (NU_SOLICITUD, NU_PRESTAMO) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.C_RIE_SOLICITUDES_DIA_N1 ON BDS.C_RIE_SOLICITUDES_DIA (FE_PROCESO, NU_SOLICITUD) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.L_RIE_PRESTAMOS_EXTORNADOS_N1 ON BDS.L_RIE_PRESTAMOS_EXTORNADOS (FE_PROCESO, NU_PRESTAMO) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.L_RIE_AUSENTE_HM_EGP_N1 ON BDS.L_RIE_AUSENTE_HM_EGP (FE_PROCESO, NU_PRESTAMO) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.F_RIE_PRESTAMOS_REFINANCIAD_N1 ON BDS.F_RIE_PRESTAMOS_REFINANCIADOS (FE_PROCESO, NU_PRESTAMO) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.D_GEN_LINEA_CREDITO_N1 ON BDS.D_GEN_LINEA_CREDITO (NU_LINE_CRED) TABLESPACE BDS_IDX_01;

CREATE INDEX BDS.D_GEN_TIPO_CAMBIO_N1 ON BDS.D_GEN_TIPO_CAMBIO (FE_COTIZACION, CO_TIPO_CAMB, CO_MONEDA) TABLESPACE BDS_IDX_01;
