--ALTER CAMBIO TABLAS T
ALTER TABLE STG.T_CO_PRODUCTOS
ADD (C8021 VARCHAR2(5),
	 C6272 NUMBER(22),
	 C6275 NUMBER(15,2),
	 C6291 NUMBER(15,2),
	 C7998 DATE,
	 C8002 VARCHAR2(5));
COMMENT ON COLUMN STG.T_CO_PRODUCTOS.C8021 IS 'ESTADO';
COMMENT ON COLUMN STG.T_CO_PRODUCTOS.C6272 IS 'TIPO DE BLOQUEO';
COMMENT ON COLUMN STG.T_CO_PRODUCTOS.C6275 IS 'MONTO MINIMO';
COMMENT ON COLUMN STG.T_CO_PRODUCTOS.C6291 IS 'MONTO MAXIMO/DEPOSITO MINIMO';
COMMENT ON COLUMN STG.T_CO_PRODUCTOS.C7998 IS 'FECHA DE INICIO'; 
COMMENT ON COLUMN STG.T_CO_PRODUCTOS.C8002 IS 'LINEA DE CREDITO';

ALTER TABLE STG.T_DESEMBOLSO
ADD(COD_ANA     NUMBER(22), 
    COD_PRO     NUMBER(10,0),
    VL_TCEA     NUMBER(11,7),
    NU_PLA_DIAS NUMBER(6)
);

COMMENT ON COLUMN STG.T_DESEMBOLSO.COD_ANA     iS 'CODIGO DE ANALISTA';
COMMENT ON COLUMN STG.T_DESEMBOLSO.COD_PRO     IS 'CODIGO DE PRODUCTO'; 
COMMENT ON COLUMN STG.T_DESEMBOLSO.VL_TCEA     IS 'TASA DE INTERES'; 
COMMENT ON COLUMN STG.T_DESEMBOLSO.NU_PLA_DIAS IS 'PLAZO SOLICITADO EN DIAS'; 

--ALTER CAMBIO TABLAS ODS
ALTER TABLE ODS.MD_PRODUCTO_01 
DROP (FE_ACTU_DIA);

ALTER TABLE ODS.MD_PRODUCTO_01
ADD (FE_INICIAL   DATE,
	 ST_PRODUCTO  VARCHAR2(5),
	 TX_LINE_CRED VARCHAR2(5),
	 TI_BLOQUEO   NUMBER(22),
	 MO_MAXIMO    NUMBER (15,2),
	 MO_MINIMO    NUMBER (15,2),
	 TI_TASA      VARCHAR2(5),
	 NU_RUBR_OPER INTEGER,
	 FE_ACTU_DIA  DATE DEFAULT SYSDATE);

COMMENT ON COLUMN ODS.MD_PRODUCTO_01.FE_INICIAL   IS 'FECHA DE INICIO'; 
COMMENT ON COLUMN ODS.MD_PRODUCTO_01.ST_PRODUCTO  IS 'ESTADO DEL PRODUCTO';
COMMENT ON COLUMN ODS.MD_PRODUCTO_01.TX_LINE_CRED IS 'LINEA DE CREDITO';
COMMENT ON COLUMN ODS.MD_PRODUCTO_01.TI_BLOQUEO   IS 'TIPO DE BLOQUEO';
COMMENT ON COLUMN ODS.MD_PRODUCTO_01.MO_MAXIMO    IS 'MONTO MAXIMO/DEPOSITO MINIMO';
COMMENT ON COLUMN ODS.MD_PRODUCTO_01.MO_MINIMO    IS 'MONTO MINIMO';
COMMENT ON COLUMN ODS.MD_PRODUCTO_01.TI_TASA      IS 'TIPO DE TASA'; 
COMMENT ON COLUMN ODS.MD_PRODUCTO_01.NU_RUBR_OPER IS 'RUBRO OPERATIVO DEL PRODUCTO';
COMMENT ON COLUMN ODS.MD_PRODUCTO_01.FE_ACTU_DIA  IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
 
ALTER TABLE ODS.HD_DESEMBOLSO
ADD(CO_ANALISTA  NUMBER(22), 
    CO_PRODUCTO  NUMBER(10,0),
    VL_TCEA      NUMBER(11,7),
    NU_PLAZ_DIAS NUMBER(6)
);

COMMENT ON COLUMN ODS.HD_DESEMBOLSO.CO_ANALISTA  IS 'CODIGO DE ANALISTA';
COMMENT ON COLUMN ODS.HD_DESEMBOLSO.CO_PRODUCTO  IS 'CODIGO DE PRODUCTO'; 
COMMENT ON COLUMN ODS.HD_DESEMBOLSO.VL_TCEA      IS 'TASA DE INTERES'; 
COMMENT ON COLUMN ODS.HD_DESEMBOLSO.NU_PLAZ_DIAS IS 'PLAZO SOLICITADO EN DIAS'; 