/*TABLA T*/
CREATE TABLE STG.T_GRL_DETALLE_CONTABILIDAD
(
  TZ_LOCK                NUMBER(15)  NOT NULL,
  JTS_OID                NUMBER(12)  NOT NULL,
  MOV_ASIENTO            NUMBER(10)  NOT NULL,
  MOV_FECHA_PROCESO      DATE        NOT NULL,
  MOV_SUCURSAL           NUMBER(5)   NOT NULL,
  MOV_OPERACION          NUMBER(5)   NOT NULL,
  MOV_TRREAL             NUMBER(5)   NOT NULL,
  MOV_ORDINAL            NUMBER(10)  NOT NULL,
  MOV_TIPO               VARCHAR2(1) NOT NULL,
  MOV_SIGNO              VARCHAR2(1),
  MOV_MONEDA             NUMBER(5),
  MOV_IMPORTE            NUMBER(15,2),
  MOV_EQUIVALENTE_MN     NUMBER(15,2),
  MOV_RUBRO_CONTABLE     NUMBER(15),
  SALDO_ORIG_SUCURSAL    NUMBER(5)   NOT NULL,
  SALDO_ORIG_CUENTA      NUMBER(15)  NOT NULL,
  SALDO_ORIG_MONEDA      NUMBER(5)   NOT NULL,
  SALDO_ORIG_PRODUCTO    NUMBER(11)  NOT NULL,
  SALDO_ORIG_OPERACION   NUMBER(15)  NOT NULL,
  SALDO_ORIG_ORDINAL     NUMBER(5)   NOT NULL,
  ESQUEMA_CONTABLE_CAMPO NUMBER(5),
  ESQUEMA_CONTABLE_LINEA NUMBER(5),
  SALDO_DEST_SUCURSAL    NUMBER(5)   NOT NULL,
  SALDO_DEST_CUENTA      NUMBER(15)  NOT NULL,
  SALDO_DEST_MONEDA      NUMBER(5)   NOT NULL,
  SALDO_DEST_PRODUCTO    NUMBER(11)  NOT NULL,
  SALDO_DEST_OPERACION   NUMBER(15)  NOT NULL,
  SALDO_DEST_ORDINAL     NUMBER(5)   NOT NULL,
  CARGOS_ID_CARGO        NUMBER(4),
  CARGOS_ID_IMPUESTO     NUMBER(4),
  CLIENTE_ORIGEN         NUMBER(12), 
  JTS_OID_CUENTA_ORIGEN  NUMBER(12)
)
NOLOGGING TABLESPACE STG_DATA_01; 

 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.TZ_LOCK IS 'ESTADO DEL REGISTRO';    
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.JTS_OID IS 'AUTO NUMERADOR  JTS_OID';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_ASIENTO IS 'NUMERO DE ASIENTO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_FECHA_PROCESO IS 'FECHA DE PROCESO DEL ASIENTO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_SUCURSAL IS 'SUCURSAL DEL ASIENTO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_OPERACION IS 'NUMERO DE OPERACION DEL ASIENTO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_TRREAL IS 'TRANSACCION REAL DEL MOVIMIENTO ORIGINAL';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_ORDINAL IS 'ORDINAL DEL MOVIMIENTO ORIGINAL';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_TIPO IS 'TIPO DEL MOVIMIENTO ORIGINAL';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_SIGNO IS 'SE HEREDA DE LA INSTRUCCION SI ES DEBITO O CREDITO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_MONEDA IS 'MONEDA DEL MOVIMIENTO ORIGINAL';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_IMPORTE IS 'IMPORTE DEL MOVIMIENTO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_EQUIVALENTE_MN IS 'EQUIVALENTE EN MONEDA NACIONAL DEL MOVIMIENTO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.MOV_RUBRO_CONTABLE IS 'RUBRO CONTABLE DEL MOVIMIENTO ORIGINAL';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_ORIG_SUCURSAL IS 'SUCURSAL DEL SALDO ORIGEN';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_ORIG_CUENTA IS 'CUENTA DEL SALDO ORIGEN';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_ORIG_MONEDA IS 'MONEDA DEL SALDO ORIGEN';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_ORIG_PRODUCTO IS 'PRODUCTO DEL SALDO ORIGEN';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_ORIG_OPERACION IS 'OPERACION DEL SALDO ORIGEN';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_ORIG_ORDINAL IS 'ORDINAL DEL SALDO ORIGEN';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.ESQUEMA_CONTABLE_CAMPO IS 'CAMPO DEL ESQUEMA CONTABLE QUE GENERO EL DETALLE';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.ESQUEMA_CONTABLE_LINEA IS 'LINEA DEL ESQUEMA CONTABLE QUE GENERO EL DETALLE';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_DEST_SUCURSAL IS 'SUCURSAL DEL SALDO DESTINO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_DEST_CUENTA IS 'CUENTA DEL SALDO DESTINO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_DEST_MONEDA IS 'MONEDA DEL SALDO DESTINO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_DEST_PRODUCTO IS 'PRODUCTO DEL SALDO DESTINO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_DEST_OPERACION IS 'OPERACION DEL SALDO DESTINO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.SALDO_DEST_ORDINAL IS 'ORDINAL DEL SALDO DESTINO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.CARGOS_ID_CARGO IS 'IDENTIFICADOR DEL CARGO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.CARGOS_ID_IMPUESTO IS 'IDENTIFICADOR DEL IMPUESTO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.CLIENTE_ORIGEN IS 'CLIENTE QUE ORIGINO EL MOVIMIENTO';
 COMMENT ON COLUMN STG.T_GRL_DETALLE_CONTABILIDAD.JTS_OID_CUENTA_ORIGEN IS 'INDICADOR DE LA CUENTA ORIGEN';


/*TABLA TD*/
CREATE TABLE ODS.TD_DETALLE_CONTABILIDAD
(
NU_PERI_MES NUMBER(6) DEFAULT 0,
FE_PROCESO DATE NOT NULL,
CO_OPERATIVA NUMBER(15) DEFAULT 0,
NU_ASIENTO NUMBER(15) DEFAULT 0,
CO_CLIENTE NUMBER(15) DEFAULT 0,
IN_JTS_OID	NUMBER(12) DEFAULT	0,
FE_VALOR DATE,	
CO_SUCURSAL NUMBER(5) DEFAULT 0,
NU_TRREAL NUMBER(5) DEFAULT 0,
NU_ORDINAL NUMBER(10) DEFAULT 0,
TI_MOVI_CONTA VARCHAR2(1) DEFAULT '.',
IN_SIGNO VARCHAR2(1)	DEFAULT '.',
CO_MONEDA NUMBER(5) DEFAULT	0,
MO_IMPORTE NUMBER(15,2) DEFAULT 0,
MO_IMPO_MN NUMBER(15,2) DEFAULT 0,
CO_CUEN_CONT NUMBER(30) DEFAULT 0,
CO_SUCU_ORIG NUMBER(5) DEFAULT 0,
NU_CUEN_ORIG NUMBER(15) DEFAULT 0,
CO_MONE_ORIG NUMBER(5) DEFAULT 0,
CO_PROD_ORIG NUMBER(5) DEFAULT 0,
NU_OPER_ORIG NUMBER(15) DEFAULT 0,
NU_ORDI_ORIG NUMBER(10) DEFAULT 0,
CO_SUCU_DEST NUMBER(5) DEFAULT 0,
NU_CUEN_DEST NUMBER(15) DEFAULT 0,
CO_MONE_DEST NUMBER(5) DEFAULT 0,
CO_PROD_DEST NUMBER(5) DEFAULT 0,
NU_OPER_DEST NUMBER(15) DEFAULT 0,
NU_ORDI_DEST NUMBER(10) DEFAULT 0,
CO_CARGO NUMBER(5) DEFAULT 0,
DE_REFE_ASIE VARCHAR2(500) DEFAULT '.',
IN_JTS_OID_CUEN_ORIG	NUMBER(15) DEFAULT 0,
FE_ACTU_DIA	DATE	DEFAULT Sysdate
)
NOLOGGING TABLESPACE ODS_DATA_01; 


COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_PERI_MES IS 'NUMERO DE PERIODO. SE GENERA A PARTIR DEL AÑO Y MES DE LA FECHA EXTRACCION EN FORMATO YYYYMM.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.FE_PROCESO IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_OPERATIVA IS 'CODIGO DE OPERATIVA.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_ASIENTO IS 'NUMERO DE ASIENTO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_CLIENTE IS 'CODIGO DE CLIENTE QUE ORIGINO EL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.IN_JTS_OID IS 'INDICADOR DE LA TRAZA CONTABLE GENERADO POR TOPAZ.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.FE_VALOR IS 'FECHA DE VALOR.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_SUCURSAL IS 'CODIGO SUCURSAL.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_TRREAL IS 'NUMERO DE LA TRANSACCION REAL DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_ORDINAL IS 'NUMERO ORDINAL DE SALDOS.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.TI_MOVI_CONTA IS 'TIPO DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.IN_SIGNO IS 'INDICADOR DE OPERACION SI ES DEBITO/CREDITO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_MONEDA IS 'MONEDA DEL MOVIMIENTO ORIGINAL.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.MO_IMPORTE IS 'MONTO DE IMPORTE DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.MO_IMPO_MN IS 'MONTO DE IMPORTE DEL MOVIMIENTO EQUIVALENTE EN MONEDA NACIONAL.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_CUEN_CONT IS 'CODIGO DEL RUBRO CONTABLE DEL MOVIMIENTO ORIGINAL.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_SUCU_ORIG IS 'CODIGO DE SUCURSAL DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_CUEN_ORIG IS 'NUMERO DE CUENTA DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_MONE_ORIG IS 'CODIGO MONEDA DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_PROD_ORIG IS 'CODIGO DE PRODUCTO DEL SALDO ORIGEN';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_OPER_ORIG IS 'NUMERO DE OPERACIÓN DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_ORDI_ORIG IS 'NUMERO ORDINAL DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_SUCU_DEST IS 'CODIGO DE SUCURSAL DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_CUEN_DEST IS 'NUMERO DE CUENTA DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_MONE_DEST IS 'CODIGO DE MONEDA DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_PROD_DEST IS 'CODIGO DE PRODUCTO DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_OPER_DEST IS 'NUMERO DE OPERACION DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.NU_ORDI_DEST IS 'NUMERO ORDINAL DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.CO_CARGO IS 'CODIGO DEL CARGO DEL ANALISTA.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.DE_REFE_ASIE IS 'DESCRIPCION DE LA REFERENCIA DEL ASIENTO.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.IN_JTS_OID_CUEN_ORIG IS 'INDICADOR DE LA CUENTA ORIGEN.';
COMMENT ON COLUMN ODS.TD_DETALLE_CONTABILIDAD.FE_ACTU_DIA IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';
 

/*TABLA HD*/
CREATE TABLE ODS.HD_DETALLE_CONTABILIDAD
(
NU_PERI_MES NUMBER(6) DEFAULT 0,
FE_PROCESO DATE NOT NULL,
CO_OPERATIVA NUMBER(15) DEFAULT 0,
NU_ASIENTO NUMBER(15) DEFAULT 0,
CO_CLIENTE NUMBER(15) DEFAULT 0,
IN_JTS_OID NUMBER(12) DEFAULT 0,
FE_VALOR DATE,	
CO_SUCURSAL NUMBER(5) DEFAULT 0,
NU_TRREAL NUMBER(5) DEFAULT 0,
NU_ORDINAL NUMBER(10) DEFAULT 0,
TI_MOVI_CONTA VARCHAR2(1) DEFAULT '.',
IN_SIGNO VARCHAR2(1)	DEFAULT '.',
CO_MONEDA NUMBER(5) DEFAULT	0,
MO_IMPORTE NUMBER(15,2) DEFAULT 0,
MO_IMPO_MN NUMBER(15,2) DEFAULT 0,
CO_CUEN_CONT NUMBER(30) DEFAULT 0,
CO_SUCU_ORIG NUMBER(5) DEFAULT 0,
NU_CUEN_ORIG NUMBER(15) DEFAULT 0,
CO_MONE_ORIG NUMBER(5) DEFAULT 0,
CO_PROD_ORIG NUMBER(5) DEFAULT 0,
NU_OPER_ORIG NUMBER(15) DEFAULT 0,
NU_ORDI_ORIG NUMBER(10) DEFAULT 0,
CO_SUCU_DEST NUMBER(5) DEFAULT 0,
NU_CUEN_DEST NUMBER(15) DEFAULT 0,
CO_MONE_DEST NUMBER(5) DEFAULT 0,
CO_PROD_DEST NUMBER(5) DEFAULT 0,
NU_OPER_DEST NUMBER(15) DEFAULT 0,
NU_ORDI_DEST NUMBER(10) DEFAULT 0,
CO_CARGO NUMBER(5) DEFAULT 0,
DE_REFE_ASIE VARCHAR2(500) DEFAULT '.',
FE_ACTU_DIA	DATE	DEFAULT Sysdate
) NOLOGGING TABLESPACE ODS_DATA_01 
PARTITION BY RANGE (FE_PROCESO)
(      
PARTITION P_HD_DETALLE_CONTAB_20200101 VALUES LESS THAN (TO_DATE('2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) TABLESPACE ODS_DATA_01 NOLOGGING,
PARTITION P_HD_DETALLE_CONTAB_MAX VALUES LESS THAN (MAXVALUE) TABLESPACE ODS_DATA_01 NOLOGGING
);

COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_PERI_MES IS 'NUMERO DE PERIODO. SE GENERA A PARTIR DEL AÑO Y MES DE LA FECHA EXTRACCION EN FORMATO YYYYMM.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.FE_PROCESO IS 'FECHA DE PROCESO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_OPERATIVA IS 'CODIGO DE OPERATIVA.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_ASIENTO IS 'NUMERO DE ASIENTO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_CLIENTE IS 'CODIGO DE CLIENTE QUE ORIGINO EL MOVIMIENTO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.IN_JTS_OID IS 'INDICADOR DE LA TRAZA CONTABLE GENERADO POR TOPAZ.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.FE_VALOR IS 'FECHA DE VALOR.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_SUCURSAL IS 'CODIGO SUCURSAL.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_TRREAL IS 'NUMERO DE LA TRANSACCION REAL DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_ORDINAL IS 'NUMERO ORDINAL DE SALDOS.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.TI_MOVI_CONTA IS 'TIPO DEL MOVIMIENTO CONTABLE.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.IN_SIGNO IS 'INDICADOR DE OPERACION SI ES DEBITO/CREDITO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_MONEDA IS 'MONEDA DEL MOVIMIENTO ORIGINAL.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.MO_IMPORTE IS 'MONTO DE IMPORTE DEL MOVIMIENTO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.MO_IMPO_MN IS 'MONTO DE IMPORTE DEL MOVIMIENTO EQUIVALENTE EN MONEDA NACIONAL.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_CUEN_CONT IS 'CODIGO DEL RUBRO CONTABLE DEL MOVIMIENTO ORIGINAL.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_SUCU_ORIG IS 'CODIGO DE SUCURSAL DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_CUEN_ORIG IS 'NUMERO DE CUENTA DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_MONE_ORIG IS 'CODIGO MONEDA DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_PROD_ORIG IS 'CODIGO DE PRODUCTO DEL SALDO ORIGEN';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_OPER_ORIG IS 'NUMERO DE OPERACIÓN DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_ORDI_ORIG IS 'NUMERO ORDINAL DEL SALDO ORIGEN.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_SUCU_DEST IS 'CODIGO DE SUCURSAL DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_CUEN_DEST IS 'NUMERO DE CUENTA DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_MONE_DEST IS 'CODIGO DE MONEDA DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_PROD_DEST IS 'CODIGO DE PRODUCTO DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_OPER_DEST IS 'NUMERO DE OPERACION DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.NU_ORDI_DEST IS 'NUMERO ORDINAL DEL SALDO DESTINO.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.CO_CARGO IS 'CODIGO DEL CARGO DEL ANALISTA.';
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.DE_REFE_ASIE IS 'DESCRIPCION DE LA REFERENCIA DEL ASIENTO.'; 
COMMENT ON COLUMN ODS.HD_DETALLE_CONTABILIDAD.FE_ACTU_DIA IS 'FECHA DE ACTUALIZACION DEL REGISTRO.';



